{"hash": "ea17fc818437a7cd4a644dc10653147b", "result": {"engine": "jupyter", "markdown": "---\ntitle: \"A bubble through a packed bed\"\nsubtitle: \"Buoyancy against capillarity in a liquid-saturated packing: the bubble squeezes through the throats, and the gas volume is conserved to the projection's own divergence residual while the colour inside the grains stays exactly zero.\"\nauthor: \"Peclet\"\ndate: \"2026-09-02\"\ncategories: [flow, dem, vof, two-phase, porous-media, wetting, IBM, multi-method, gpu]\njupyter: python3\n---\n\n\n\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/computational-chemical-engineering/peclet-examples/blob/main/examples/bubble-through-packing/index.ipynb){target=\"_blank\"}\n&nbsp;Wants a GPU build: two $64\\times64\\times160$ two-phase runs of a few thousand steps\neach, plus three shorter ones.\n\n## What you'll learn\n\nThis is the page where the pieces meet. A **`dem`** packing becomes a signed distance\nfield; the **cut-cell immersed boundary** turns that field into openness-weighted\npressure and transport operators; the **geometric VoF** transports a gas/liquid\ninterface *through* those cut cells; a **static contact angle** tells the interface\nwhat to do where it meets a grain; and **momentum-consistent transport** carries\n$\\rho\\mathbf{u}$ with the same fluxes at a density ratio of 100. Nothing here is a\nbenchmark with a published number \u2014 it is the composition itself, and the honest\nquestion is whether the conservation statements survive it.\n\nThey do \u2014 and the geometry does something to the bubble worth watching. It rises freely,\nmeets the underside of the bed, is **held there** until the buoyant head builds enough to\nforce a throat, and then works its way up through the pore space at a fraction of its\nfree speed. That is @eq-entry below, playing out. How large each of those two costs \u2014 the\nwait and the drag \u2014 turns out to be depends *sharply* on the bed, and \u00a73 measures both and\nshows how far they move between two beds built by the identical protocol. Through all of\nit the gas volume is conserved to **machine precision**, the colour inside the grains is\n**exactly zero** to the last bit, and the pressure projection never comes close to its\niteration cap. \u00a75 repeats the whole packed run at density ratio **1000**.\n\nThe page also runs the same bubble in the **same column with no packing**, which is the\nonly yardstick available here \u2014 every number about the bed is a number *relative to the\nfree rise*.\n\n## The problem\n\nA gas bubble of diameter $D$ is released at the bottom of a closed, liquid-saturated\ncolumn and rises through a random packing of spheres whose diameter is comparable to\nits own. Three groups fix the physics.\n\nThe **E\u00f6tv\u00f6s** and **Morton** numbers say what shape a *free* bubble takes\n[@clift1978]:\n\n$$\n\\mathrm{Eo} = \\frac{\\Delta\\rho\\, g\\, D^{2}}{\\sigma},\n\\qquad\n\\mathrm{Mo} = \\frac{g\\,\\mu_\\ell^{4}\\,\\Delta\\rho}{\\rho_\\ell^{2}\\sigma^{3}} ,\n\\qquad\n\\mathrm{Re} = \\frac{\\rho_\\ell U_g D}{\\mu_\\ell},\\quad U_g=\\sqrt{gD} .\n$$ {#eq-groups}\n\nAt $\\mathrm{Eo}=10$ and $\\mathrm{Mo}=10^{-3}$ a free bubble is firmly **ellipsoidal** \u2014\ndeformable, not a spherical cap, not a wobbling one. That is the regime chosen here,\nbecause a bubble that cannot deform cannot pass a throat narrower than itself.\n\nThe third group is the one the packing adds. To push its nose into a pore throat of\nradius $r_t$ against a **wetting** liquid ($\\theta$ measured through the liquid), the\ngas must overcome the Young\u2013Laplace entry pressure, and the head it has available is\nthe hydrostatic head over its own vertical extent $L$:\n\n$$\n\\underbrace{\\frac{2\\sigma\\cos\\theta}{r_t}}_{\\text{capillary entry}}\n\\;<\\;\n\\underbrace{\\Delta\\rho\\,g\\,L}_{\\text{buoyant head}}\n\\qquad\\Longleftrightarrow\\qquad\nL \\;>\\; \\frac{2\\cos\\theta}{\\mathrm{Eo}}\\,\\frac{D^{2}}{r_t} .\n$$ {#eq-entry}\n\n@eq-entry is the whole story of the page in one line: it says the bubble must\n**elongate** to a length set by $D^2/r_t$ before it can enter, and it is why the run\nbelow shows a bubble that stretches, necks, and leaves fragments behind. It is also\nthe criterion that decides the scene \u2014 see the callout after the geometry.\n\nThe governing equations are the usual one-fluid form with a single variable density and\nviscosity and a singular interfacial force, restricted to the fluid part of each cell by\nthe openness weights $\\varepsilon$ (cell fluid fraction) and $o_f$ (face openness):\n\n$$\n\\partial_t(\\rho\\mathbf{u}) + \\nabla\\!\\cdot\\!(\\rho\\mathbf{u}\\mathbf{u})\n  = -\\nabla p + \\nabla\\!\\cdot\\!\\big[\\mu(\\nabla\\mathbf{u}+\\nabla\\mathbf{u}^{\\mathsf T})\\big]\n  + \\rho\\mathbf{g} + \\sigma\\kappa\\,\\mathbf{n}\\,\\delta_S ,\n\\qquad\n\\partial_t (\\varepsilon C) + \\nabla\\!\\cdot\\!(o\\,C\\,\\mathbf{u}) = 0 ,\n$$ {#eq-ns}\n\nwith $C$ the **liquid** fraction of a cell's *fluid* volume \u2014 so the bubble is $C=0$,\nand the gas volume of the discrete field is $\\sum_i \\varepsilon_i (1-C_i)$.\n\n::: {#bootstrap .cell execution_count=1}\n``` {.python .cell-code code-summary=\"Environment bootstrap (installs peclet from PyPI on Colab/Binder)\"}\n# Makes this notebook run out-of-the-box on Colab/Binder. A real user just needs the\n# published package; this installs it on first run. Authors can instead point at local\n# source builds of the suite with PECLET_LOCAL_BUILD (os.pathsep-separated).\nimport importlib.util, os, subprocess, sys\n_local = os.environ.get(\"PECLET_LOCAL_BUILD\")\nif _local:\n    for p in _local.split(os.pathsep):\n        sys.path.insert(0, p)\nelif importlib.util.find_spec(\"peclet\") is None:\n    subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"-q\", \"peclet\"], check=True)\n```\n:::\n\n\n::: {#a3b7a35d .cell execution_count=2}\n``` {.python .cell-code}\nimport math, time\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom peclet import dem, flow\n\nplt.rcParams.update({\"figure.dpi\": 130, \"font.size\": 10, \"axes.grid\": True,\n                     \"grid.alpha\": 0.3, \"axes.axisbelow\": True,\n                     \"figure.facecolor\": \"white\", \"savefig.bbox\": \"tight\"})\nBLUE, RED, GREY, GREEN, ORANGE = \"#1f77b4\", \"#d62728\", \"0.80\", \"#2ca02c\", \"#ff7f0e\"\n```\n:::\n\n\n## The scene\n\nEverything is expressed in **cells**: peclet's grid spacing is 1 and its time unit is\nthe second, and this problem has no external length to match, so the dimensionless\ngroups of @eq-groups are imposed directly on solver-unit properties. The column is\n$64\\times64\\times160$ cells, **periodic in $x$ and $y$** and closed by no-slip walls at\ntop and bottom.\n\n::: {#scene .cell execution_count=3}\n``` {.python .cell-code}\nNX, NZ   = 64, 160          # column: 64 x 64 cross-section, 160 cells tall\nN_GRAIN  = 26               # grains in the bed\nR_JAM    = 0.171875 * NX    # 11.0 cells \u2014 the radius the grains JAM at in dem\nF_SDF    = 0.85             # SDF grain radius / contact radius (see the callout below)\nR_GRAIN  = F_SDF * R_JAM    # 9.35 cells \u2014 the radius the fluid solver sees\nZ_BED    = 0.5625 * NX      # 36.0 \u2014 bottom of the bed\nR_BUB    = 0.15625 * NX     # 10.0 cells \u2014 bubble radius (D = 20, D/W = 0.31)\nZ_BUB    = 0.28125 * NX     # 18.0 \u2014 bubble centre at release\nprint(f\"column {NX}x{NX}x{NZ}   bubble D = {2*R_BUB:.0f} cells (D/W = {2*R_BUB/NX:.2f})   \"\n      f\"grain D = {2*R_GRAIN:.1f} cells\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncolumn 64x64x160   bubble D = 20 cells (D/W = 0.31)   grain D = 18.7 cells\n```\n:::\n:::\n\n\n### Step 1 \u2014 the packing, from `dem`\n\nThe grains are dropped onto a floor plane in a laterally periodic column and settled\nwith friction: a **random loose** deposit, not a Lubachevsky\u2013Stillinger close packing\n(the [random packed bed](../random-packed-bed/index.qmd) page does that one). A column\nonly 3.3 grain diameters wide cannot hold a bulk packing anyway, and the loose deposit\nis the honest thing to build here.\n\n::: {#settle .cell execution_count=4}\n``` {.python .cell-code}\ndef settle_bed(n=N_GRAIN, W=float(NX), Rj=R_JAM, seed=11, steps=4000, dt=5e-3):\n    \"\"\"Drop `n` grains onto a floor in an x/y-periodic column; return the settled centres.\"\"\"\n    s = dem.Simulation(8 * n)                     # headroom for the periodic ghost band\n    s.initialize(shape_type=1, radius=1.0)\n    s.set_global_scale(Rj)\n    s.set_domain((0.0, 0.0, -20.0), (W, W, 400.0))\n    s.enable_periodicity(True, True, False)       # z is closed by the floor plane\n    s.set_gravity(0.0, 0.0, -9.81)\n    s.add_plane(0.0, 0.0, 0.0, 0.0, 0.0, 1.0)     # the floor\n    s.set_material_params(0.05, 0.0, 0.6)         # restitution / tangential / friction\n    s.set_solver_iterations(8, 8)\n    rng = np.random.default_rng(seed)\n    P = np.zeros((n, 3))\n    P[:, :2] = rng.uniform(0.0, W, (n, 2))\n    P[:, 2] = Rj * 1.2 + 2.35 * Rj * (np.arange(n) // 4) + rng.uniform(-1.5, 1.5, n)\n    s.set_positions(np.ascontiguousarray(P.astype(np.float32)))\n    s.set_inv_mass(np.full(n, 1.0, np.float32))\n    s.set_dt(dt)\n    for _ in range(steps):\n        s.step(dt)\n    return np.asarray(s.get_positions())[:n, :3].astype(float), float(s.max_overlap())\n\nt0 = time.time()\nCENTRES, OVERLAP = settle_bed()\nBED_LO, BED_HI = CENTRES[:, 2].min() - R_JAM, CENTRES[:, 2].max() + R_JAM\nprint(f\"{N_GRAIN} grains settled in {time.time()-t0:.0f} s   max overlap {OVERLAP:.4f} cells \"\n      f\"(contact radius {R_JAM:.2f})\")\nprint(f\"jammed bed height {BED_HI-BED_LO:.1f} cells, solid fraction at contact \"\n      f\"{N_GRAIN*4/3*math.pi*R_JAM**3/(NX*NX*(BED_HI-BED_LO)):.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n26 grains settled in 166 s   max overlap 0.0194 cells (contact radius 11.00)\njammed bed height 70.5 cells, solid fraction at contact 0.502\n```\n:::\n:::\n\n\n### Step 2 \u2014 the packing as a signed distance field\n\nThe fluid solver only ever sees $\\varphi$, the signed distance ($\\varphi>0$ is fluid),\nsampled periodically in $x$ and $y$ and translated so the bed sits above the release\npool.\n\n::: {#sdf .cell execution_count=5}\n``` {.python .cell-code}\ndef bed_sdf(centres, nx=NX, nz=NZ, Rg=R_GRAIN, z0=Z_BED):\n    \"\"\"Signed distance to the union of the grains; periodic in x and y.\"\"\"\n    W = float(nx)\n    P = centres.copy(); P[:, 2] += z0\n    g, gz = np.arange(nx) + 0.5, np.arange(nz) + 0.5\n    X, Y, Z = np.meshgrid(g, g, gz, indexing=\"ij\")\n    phi = np.full((nx, nx, nz), 1e30)\n    for k in range(len(P)):\n        dx = X - P[k, 0]; dx -= W * np.round(dx / W)\n        dy = Y - P[k, 1]; dy -= W * np.round(dy / W)\n        dz = Z - P[k, 2]\n        phi = np.minimum(phi, np.sqrt(dx * dx + dy * dy + dz * dz) - Rg)\n    return np.asfortranarray(phi)\n\nSDF = bed_sdf(CENTRES)\nBED_Z0 = Z_BED + R_JAM - R_GRAIN                     # lowest grain surface\nBED_Z1 = Z_BED + (BED_HI - BED_LO) - R_JAM + R_GRAIN  # highest grain surface\nLO, HI = int(Z_BED + R_GRAIN), int(Z_BED + (BED_HI - BED_LO) - R_GRAIN)   # the bed CORE\nEPS_BED = float((SDF[:, :, LO:HI] > 0).mean())\nprint(f\"bed occupies z = {BED_Z0:.1f} .. {BED_Z1:.1f} cells \"\n      f\"({(BED_Z1-BED_Z0)/(2*R_GRAIN):.1f} grain diameters deep)\")\nprint(f\"porosity over the bed core (z = {LO} .. {HI}):  eps = {EPS_BED:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nbed occupies z = 37.6 .. 104.8 cells (3.6 grain diameters deep)\nporosity over the bed core (z = 45 .. 97):  eps = 0.639\n```\n:::\n:::\n\n\nThe **pore-throat radius** is the quantity @eq-entry needs, and it is not the largest\npore: it is the *bottleneck of the widest connected path* from the bottom of the bed to\nthe top \u2014 the max\u2013min path of $\\varphi$, which a Dijkstra-like sweep computes exactly.\n\n::: {#throat .cell execution_count=6}\n``` {.python .cell-code}\nimport heapq\n\ndef percolation_throat(phi, klo, khi):\n    \"\"\"max over bottom->top paths of the minimum SDF along the path (26-connected,\n    periodic in x and y). The radius of the largest sphere that can be pushed through.\"\"\"\n    sub = phi[:, :, klo:khi]\n    nx, ny, nk = sub.shape\n    val = np.full(sub.shape, -np.inf)\n    h = [(-sub[i, j, 0], i, j, 0) for i in range(nx) for j in range(ny) if sub[i, j, 0] > 0]\n    for e in h:\n        val[e[1], e[2], 0] = -e[0]\n    heapq.heapify(h)\n    while h:\n        nv, i, j, k = heapq.heappop(h)\n        v = -nv\n        if v < val[i, j, k] - 1e-12:\n            continue\n        if k == nk - 1:\n            return v\n        for di in (-1, 0, 1):\n            for dj in (-1, 0, 1):\n                for dk in (-1, 0, 1):\n                    if di == dj == dk == 0:\n                        continue\n                    a, b, c = (i + di) % nx, (j + dj) % ny, k + dk\n                    if 0 <= c < nk and min(v, sub[a, b, c]) > val[a, b, c]:\n                        val[a, b, c] = min(v, sub[a, b, c])\n                        heapq.heappush(h, (-val[a, b, c], a, b, c))\n    return -np.inf\n\nEO, THETA = 10.0, 60.0                               # the run's Eotvos number and angle\nR_THROAT = percolation_throat(SDF, int(BED_Z0), int(BED_Z1) + 1)\nL_ENTRY = 2 * math.cos(math.radians(THETA)) / EO * (2 * R_BUB) ** 2 / R_THROAT\nprint(f\"percolation throat radius r_t = {R_THROAT:.2f} cells \"\n      f\"(throat diameter {2*R_THROAT:.1f} = {2*R_THROAT/(2*R_BUB):.2f} x the bubble diameter)\")\nprint(f\"capillary entry length from eq-entry at Eo = {EO:.0f}, theta = {THETA:.0f} deg: \"\n      f\"L > {L_ENTRY:.1f} cells, against a bubble diameter of {2*R_BUB:.0f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npercolation throat radius r_t = 5.67 cells (throat diameter 11.3 = 0.57 x the bubble diameter)\ncapillary entry length from eq-entry at Eo = 10, theta = 60 deg: L > 7.1 cells, against a bubble diameter of 20\n```\n:::\n:::\n\n\n::: {.callout-important}\n## Two scene choices that are physics, not cosmetics\n\n**The grains are sampled at 85 % of the radius they jam at.**\nA DEM contact is a *tangency*, and a tangency is a throat of exactly zero area: no\nfixed grid can represent it, and no bubble could ever pass it. Shrinking the grains\nabout their jammed centres by 15 % opens every grain\u2013grain contact into a throat of\nfinite width while leaving the microstructure \u2014 the centres, the coordination, the\ndisorder \u2014 exactly as `dem` produced it. It is the standard way to build a bed of\nprescribed porosity from a jammed configuration, and it is stated here because it moves\nthe porosity from 0\\.50\nat contact to 0\\.64 as sampled.\n\n**The throat is 0\\.57 bubble diameters wide, and\n@eq-entry then wants the bubble to stretch past\n7 cells to enter \u2014 a good fraction of its own diameter.** That is a\ndeliberate design point: much tighter and the entry pressure is never reached and the\nbubble is capillary-*trapped*; much wider and the packing does nothing. It is also a\n**resolution** point. The same scene at half this grid puts only\n5\\.7 cells across the bottleneck, which is fewer than a PLIC\nplane and a height-function curvature stencil can carry \u2014 so the resolution here is set\nby the throat, not by the bubble.\n:::\n\n### Step 3 \u2014 the bubble\n\nThe colour field is handed to the solver as **volume fractions**, subsampled $4^3$, not\nas a sampled indicator \u2014 the same discipline as every other VoF page here.\n\n::: {#colour .cell execution_count=7}\n``` {.python .cell-code}\ndef bubble_colour(nx=NX, nz=NZ, R=R_BUB, cz=Z_BUB, sub=4):\n    \"\"\"C = liquid fraction; the gas bubble is the C = 0 sphere at (nx/2, nx/2, cz).\"\"\"\n    q = (np.arange(sub) + 0.5) / sub\n    px = np.arange(nx)[:, None, None, None, None, None] + q[None, None, None, :, None, None]\n    py = np.arange(nx)[None, :, None, None, None, None] + q[None, None, None, None, :, None]\n    pz = np.arange(nz)[None, None, :, None, None, None] + q[None, None, None, None, None, :]\n    c = nx / 2.0\n    gas = ((px - c) ** 2 + (py - c) ** 2 + (pz - cz) ** 2) < R * R\n    return np.asfortranarray(1.0 - gas.mean(axis=(3, 4, 5)))\n```\n:::\n\n\n::: {#cell-fig-scene .cell execution_count=8}\n``` {.python .cell-code}\nC0 = bubble_colour()\nfig, (axg, axp) = plt.subplots(1, 2, figsize=(8.6, 4.6),\n                               gridspec_kw=dict(width_ratios=[1.05, 1]))\nx = np.arange(NX) + 0.5\nz = np.arange(NZ) + 0.5\naxg.contourf(x, z, (SDF[:, NX // 2, :] < 0).T, levels=[0.5, 1.5], colors=[\"0.72\"])\naxg.contour(x, z, SDF[:, NX // 2, :].T, levels=[0.0], colors=[\"0.35\"], linewidths=0.9)\naxg.contourf(x, z, (1 - C0[:, NX // 2, :]).T, levels=[0.5, 1.5], colors=[\"#cfe3f5\"])\naxg.contour(x, z, (1 - C0[:, NX // 2, :]).T, levels=[0.5], colors=[BLUE], linewidths=1.8)\nfor zz in (0, NZ):\n    axg.axhline(zz, color=\"0.1\", lw=3)\naxg.set(xlim=(0, NX), ylim=(0, NZ), aspect=\"equal\", xlabel=\"x  [cells]\",\n        ylabel=\"z  [cells]\", title=\"mid-plane of the SDF\")\naxg.grid(False)\nopen_frac = (SDF > 0).mean(axis=(0, 1))\ninscribed = SDF.max(axis=(0, 1))\naxp.plot(open_frac, z, color=BLUE, lw=1.6, label=\"open-area fraction of the plane\")\naxp2 = axp.twiny()\naxp2.plot(inscribed, z, color=ORANGE, lw=1.4, label=\"largest inscribed circle radius\")\naxp2.axvline(R_THROAT, ls=\"--\", color=RED, lw=1.2)\naxp2.set_xlabel(\"radius  [cells]\", color=ORANGE)\naxp2.set_xlim(0, 22)\naxp.set(ylim=(0, NZ), xlim=(0, 1.05), xlabel=\"open-area fraction\", ylabel=\"z  [cells]\")\naxp.set_title(\"what the bubble has to get through\", pad=26)\naxp.plot([], [], color=ORANGE, lw=1.4, label=\"largest inscribed circle\")\naxp.plot([], [], \"--\", color=RED, lw=1.2, label=f\"percolation throat $r_t$ = {R_THROAT:.1f}\")\naxp.legend(fontsize=7.5, loc=\"upper center\")\nplt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The scene. Left: the mid-plane of the signed distance field \u2014 grains grey, the released bubble blue, the no-slip floor and lid black, the sides periodic. Right: the open-area fraction of each horizontal plane (blue) and the radius of the largest inscribed circle in that plane (orange), with the percolation throat radius \u2014 the bottleneck of the widest connected path, which is what eq-entry uses \u2014 as the dashed line. Note that the per-plane inscribed circle is always optimistic: the widest spot in one plane need not connect to the widest spot in the next.](index_files/figure-html/fig-scene-output-1.png){#fig-scene}\n:::\n:::\n\n\n## The driver\n\nThe whole setup is a dozen or so calls, and five of them do something a single-phase\nrun never needs.\n\n- `set_solid(..., cutcell_pressure=True)` is **required**: the colour transport weights\n  every flux by the face openness and the staircase pressure operator has none, so the\n  solver raises rather than approximate it.\n- `set_contact_angle(60)` is the whole wetting model \u2014 a wetting liquid, so the gas is\n  pushed off the grains rather than sticking to them.\n- `enable_vof_momentum(rho_gas, rho_liquid)` advects $\\rho^c\\mathbf{u}$ with the *same*\n  geometric fluxes as $C$ [@rudman1998; @arrufat2021]. It composes with cut cells, and\n  it is on for every ratio-100 run here.\n- gravity is a **closure of the colour** \u2014 `set_property_model(\"force_z\", \u2026)` writes\n  $f_z=-\\rho(C)g$ every step, so it acts on the true local density.\n- the time step is re-picked **every step** at 40 % of the smaller of the two explicit\n  limits `vof_step_limits()` reports (Brackbill capillary [@brackbill1992] and the\n  Weymouth\u2013Yue interface CFL [@weymouth2010]). Every-step, not every-tenth-step as the\n  free-bubble pages do: a packing manufactures *local* velocity, and the first attempt at\n  this run died at exactly that \u2014 see the callout.\n\n::: {#driver .cell execution_count=9}\n``` {.python .cell-code}\nPRESS_CAP = 600\n\ndef column(packed=True, ratio=100.0, Eo=EO, Mo=1e-3, theta=THETA, g=2e-4,\n           T=4300.0, cls=flow.Solver, momentum=True, nx=NX, nz=NZ,\n           snap_at=(), movie_every=0, label=\"\"):\n    \"\"\"One bubble in one closed column. `packed=False` is the free-rise control.\"\"\"\n    D = 2 * R_BUB\n    rho_l, rho_g = 1.0, 1.0 / ratio\n    drho = rho_l - rho_g\n    sigma = drho * g * D * D / Eo                      # from @eq-groups\n    mu_l = (Mo * rho_l ** 2 * sigma ** 3 / (g * drho)) ** 0.25\n    mu_g = mu_l / ratio\n    Ug = math.sqrt(g * D)\n\n    s = cls(nx, nx, nz)\n    s.set_rho(rho_l); s.set_mu(mu_l)\n    s.set_domain_bc(4, 1, 0, 0, 0)                     # closed: no-slip floor\n    s.set_domain_bc(5, 1, 0, 0, 0)                     # closed: no-slip lid\n    if packed:\n        s.set_solid(SDF, cutcell_pressure=True)        # cut-cell IBM + cut-cell pressure\n    else:\n        s.set_pressure_geometry(np.full((nx, nx, nz), 10.0, order=\"F\"))\n    s.enable_vof()\n    s.set_vof(bubble_colour(nx, nz))\n    s.set_property_model(\"rho\", \"linear\", \"C\", [rho_g, rho_l - rho_g])\n    s.set_property_model(\"mu\", \"linear\", \"C\", [mu_g, mu_l - mu_g])\n    s.set_surface_tension(sigma)\n    if packed:\n        s.set_contact_angle(theta)                     # static, measured through the liquid\n    if momentum:\n        s.enable_vof_momentum(rho_g, rho_l)            # consistent rho*u transport\n    s.set_property_model(\"force_z\", \"linear\", \"C\",     # buoyancy f_z = -rho(C) g\n                         [-rho_g * g, -(rho_l - rho_g) * g])\n    s.set_pressure_chebyshev(True, PRESS_CAP, 1e-12)   # AFTER the rho closure (see below)\n\n    eps = (np.asarray(s.vof_geometry(0)) if s.vof_has_geometry()\n           else np.ones((nx, nx, nz)))                # cell FLUID fraction\n    zs = np.arange(nz) + 0.5\n    gas0 = eps * (1.0 - np.asarray(s.get_vof()))\n    V0 = gas0.sum()\n    ts, zc, vc, vol = [0.0], [float((gas0.sum(axis=(0, 1)) * zs).sum() / V0)], [0.0], [1.0]\n    snaps, frames, todo = {0.0: gas0.copy()}, [], list(snap_at)\n    iters, div, ncap, ncfl, nan, capped = 0, 0.0, 0, 0, False, 0\n    t, i, dt = 0.0, 0, 0.4 * s.capillary_dt()\n    s.set_dt(dt)\n    lim0 = s.vof_step_limits()\n    t0 = time.time()\n    aborted = \"\"\n    while t < T:\n        L = s.vof_step_limits()                        # EVERY step -- see the callout below\n        dt = 0.4 * min(L[\"cfl_dt\"], L[\"capillary_dt\"]); s.set_dt(dt)\n        ncap += int(L[\"capillary_binds\"]); ncfl += int(not L[\"capillary_binds\"])\n        try:\n            s.step()\n        except RuntimeError as e:                      # never let one run break the page\n            aborted = str(e).split(\"\\n\")[0]\n            break\n        t += dt; i += 1\n        it = s.last_pressure_iterations()\n        iters = max(iters, it)\n        capped += int(it >= PRESS_CAP)\n        if capped > 20:                                # a capped solve invalidates the run;\n            break                                      # stop burning GPU time on it\n        if i % 4 == 0 or (todo and t >= todo[0]):\n            gas = eps * (1.0 - np.asarray(s.get_vof()))\n            v = gas.sum()\n            if not np.isfinite(v):\n                nan = True; break\n            ts.append(t); vol.append(v / V0)\n            zc.append(float((gas.sum(axis=(0, 1)) * zs).sum() / v))\n            vc.append(float((gas * np.asarray(s.get_w())).sum() / v))\n            if todo and t >= todo[0]:\n                snaps[todo.pop(0)] = gas.copy()\n        if movie_every and i % movie_every == 0:\n            frames.append((eps * (1.0 - np.asarray(s.get_vof()))).astype(np.float16))\n        if i % 25 == 0:\n            div = max(div, s.max_open_divergence_projected())   # non-mutating\n    d = s.vof_diagnostics()\n    return dict(label=label, packed=packed, ratio=ratio, Eo=Eo, Mo=Mo, g=g, sigma=sigma,\n                mu_l=mu_l, Ug=Ug, D=D, Re=rho_l * Ug * D / mu_l, T=T, steps=i, nan=nan,\n                t=np.array(ts), zc=np.array(zc), vc=np.array(vc), vol=np.array(vol),\n                snaps=snaps, frames=frames, iters=iters, cap=PRESS_CAP, div=div,\n                capped=capped, aborted=aborted,\n                ncap=ncap, ncfl=ncfl, lim0=lim0, V0=V0, eps=eps, wall=time.time() - t0,\n                solid_sum=d[\"solid_sum\"], clipped=d[\"clipped_volume\"],\n                C=np.asarray(s.get_vof()).copy())\n```\n:::\n\n\n::: {.callout-important}\n## Three rules this page follows, and why each one is not optional\n\n**A run whose pressure solve hit its cap is not a result.** Every run records\n`last_pressure_iterations()` against a cap of 600 and the\n**non-mutating** `max_open_divergence_projected()`. Under variable density the pressure\ndriver is Chebyshev by default; it must be selected *after* `set_property_model(\"rho\", \u2026)`,\nbecause that call fires `set_density_mode`, which reselects the driver \u2014 a selection\nmade earlier is silently discarded. If Chebyshev caps, `set_pressure_fcg(True, \u2026)` is\nthe validated alternative on wall-bounded boxes, again selected last.\n\n**`PECLET_FLOW_EXACT_RESIDUAL=1` is set for every run on this page.** It replaces the\nfloat band form of the residual by the double flux form; on the Hysing case-2 benchmark\nit removed **7.5 orders** of flux divergence and moved no other digit of the result. At\ndensity ratio 1000 that is the difference between a divergence number that means\nsomething and one that does not.\n\n**The time step is re-picked every step.** `step()` enforces the Weymouth--Yue\nboundedness cap (interface CFL 0.25) by *raising*, not by clamping, and in a packing the\nface velocity is not a smooth function of time: a bubble breaking into a throat produces\na local jet. Re-picking `dt` every ten steps \u2014 which is what the free-bubble pages do,\nsafely \u2014 killed the first attempt at this run with\n`CFL = 0.377 exceeds the Weymouth-Yue boundedness cap 0.25`, i.e. the interface velocity\nhad grown by more than half within ten steps while `dt` still carried the capillary\nvalue. The fix is one line and it is in the driver above; the cost is one extra device\nreduction per step. This is logged in [`ISSUES.md`](../../ISSUES.md).\n\n**The column is closed.** Top and bottom are no-slip walls, so the non-zero-mean\nbuoyancy is balanced by a hydrostatic pressure gradient. In a *periodic* box the same\nmomentum-consistent cut-cell path is known to diverge after ~160 steps under an\nunbounded acceleration (an open question of the rung that introduced it); a closed\ncolumn is not a workaround for that, it is the configuration in which the question does\nnot arise, and it is also what a packed column physically is.\n:::\n\n## 1. The free rise \u2014 the control\n\nThe same bubble, the same fluids, the same closed column, no packing. Everything the\nbed does is measured against this.\n\n::: {#run-control .cell execution_count=10}\n``` {.python .cell-code}\nSNAPS = (600.0, 1200.0, 1800.0, 2400.0)      # snapshot times shared by both runs\nLATE  = (2900.0, 3300.0, 3700.0, 4200.0)     # the packed run keeps going\nctl = column(packed=False, T=2500.0, snap_at=SNAPS, label=\"free rise (no packing)\")\nprint(f\"control: {ctl['steps']} steps, t = {ctl['t'][-1]:.0f} of {ctl['T']:g}, \"\n      f\"{ctl['wall']:.0f} s{('   *** ABORTED: ' + ctl['aborted'] + ' ***') if ctl['aborted'] else ''}\")\nprint(f\"  Eo {ctl['Eo']:.0f}  Mo {ctl['Mo']:.0e}  Re {ctl['Re']:.1f}  \"\n      f\"sigma {ctl['sigma']:.3e}  mu_l {ctl['mu_l']:.3e}  U_g {ctl['Ug']:.4f}\")\nprint(f\"  gas volume V(T)/V(0) = {ctl['vol'][-1]:.10f}\")\nprint(f\"  pressure {ctl['iters']}/{ctl['cap']} \"\n      f\"{'OK' if ctl['iters'] < ctl['cap'] else '*** CAPPED -> INVALID ***'}, \"\n      f\"max|div(open u)| {ctl['div']:.2e}\")\nprint(f\"  centroid {ctl['zc'][0]:.1f} -> {ctl['zc'][-1]:.1f} cells \"\n      f\"({(ctl['zc'][-1]-ctl['zc'][0])/ctl['D']:.2f} bubble diameters)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncontrol: 2016 steps, t = 2501 of 2500, 1674 s\n  Eo 10  Mo 1e-03  Re 31.8  sigma 7.920e-03  mu_l 3.980e-02  U_g 0.0632\n  gas volume V(T)/V(0) = 1.0000000000\n  pressure 24/600 OK, max|div(open u)| 6.28e-15\n  centroid 18.0 -> 124.8 cells (5.34 bubble diameters)\n```\n:::\n:::\n\n\n## 2. Through the bed\n\n::: {#run-packed .cell execution_count=11}\n``` {.python .cell-code}\nbed = column(packed=True, snap_at=SNAPS + LATE, movie_every=25,\n             label=\"through the packing\")\nprint(f\"packed: {bed['steps']} steps, t = {bed['t'][-1]:.0f} of {bed['T']:g}, \"\n      f\"{bed['wall']:.0f} s{('   *** ABORTED: ' + bed['aborted'] + ' ***') if bed['aborted'] else ''}\")\nprint(f\"  gas volume V(T)/V(0) = {bed['vol'][-1]:.10f}   \"\n      f\"(drift {abs(bed['vol'][-1]-1):.1e})\")\nprint(f\"  colour inside the grains: {bed['solid_sum']:.3e}   \"\n      f\"clipped volume {bed['clipped']:.2e}\")\nprint(f\"  pressure {bed['iters']}/{bed['cap']} \"\n      f\"{'OK' if bed['iters'] < bed['cap'] else '*** CAPPED -> INVALID ***'}, \"\n      f\"max|div(open u)| {bed['div']:.2e}\")\nprint(f\"  dt limits at t=0: WY CFL {bed['lim0']['cfl_dt']:.3e}, \"\n      f\"capillary {bed['lim0']['capillary_dt']:.3e}  -> \"\n      f\"{'CAPILLARY' if bed['lim0']['capillary_binds'] else 'CFL'} binds\")\nprint(f\"  binding limit: capillary on {bed['ncap']} of {bed['ncap']+bed['ncfl']} re-picks, \"\n      f\"WY CFL on {bed['ncfl']}\")\nprint(f\"  centroid {bed['zc'][0]:.1f} -> {bed['zc'][-1]:.1f} cells \"\n      f\"({(bed['zc'][-1]-bed['zc'][0])/bed['D']:.2f} bubble diameters)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npacked: 3797 steps, t = 4300 of 4300, 2335 s\n  gas volume V(T)/V(0) = 1.0000000000   (drift 3.4e-15)\n  colour inside the grains: 0.000e+00   clipped volume 0.00e+00\n  pressure 23/600 OK, max|div(open u)| 2.83e-14\n  dt limits at t=0: WY CFL inf, capillary 3.186e+00  -> CAPILLARY binds\n  binding limit: capillary on 2585 of 3797 re-picks, WY CFL on 1212\n  centroid 18.0 -> 153.7 cells (6.79 bubble diameters)\n```\n:::\n:::\n\n\n::: {#cell-fig-frames .cell execution_count=12}\n``` {.python .cell-code}\ndef draw(ax, gas, title, show_solid, ylim=(0, 148)):\n    \"\"\"Grains: the mid-plane section. Gas: the SILHOUETTE, i.e. the maximum of the gas\n    indicator along y \u2014 so the interface is drawn wherever it is, not only where it\n    happens to cross the mid-plane. A bubble that squeezes through an off-centre throat\n    would otherwise vanish from the figure.\"\"\"\n    ax.set_facecolor(\"#eaf0f6\")\n    if show_solid:\n        ax.contourf(x, z, (SDF[:, NX // 2, :] < 0).T, levels=[0.5, 1.5], colors=[\"0.72\"])\n    g2 = gas.max(axis=1)\n    ax.contourf(x, z, g2.T, levels=[0.5, 1.5], colors=[\"#fdf3ef\"])\n    ax.contour(x, z, g2.T, levels=[0.5], colors=[RED], linewidths=1.5)\n    ax.set(xlim=(0, NX), ylim=ylim, aspect=\"equal\", xticks=[0, 32, 64], title=title)\n    ax.grid(False)\n\ndef fragments(gas, thr=0.5):\n    \"\"\"Number of connected gas blobs (6-connected) holding at least 1 % of the volume.\"\"\"\n    from scipy import ndimage\n    lab, n = ndimage.label(gas > thr)\n    if n == 0:\n        return 0\n    sz = np.bincount(lab.ravel())[1:]\n    return int((sz > 0.01 * sz.sum()).sum())\n\ntimes = [t for t in (0.0,) + SNAPS if t in ctl[\"snaps\"] and t in bed[\"snaps\"]]\nfig, axes = plt.subplots(2, len(times), figsize=(9.8, 7.6), sharey=True)\nfor j, tt in enumerate(times):\n    draw(axes[0, j], ctl[\"snaps\"][tt], f\"t = {tt:.0f}\", False)\n    draw(axes[1, j], bed[\"snaps\"][tt], \"\", True)\n    axes[1, j].set_xlabel(\"x  [cells]\")\naxes[0, 0].set_ylabel(\"free rise\\nz  [cells]\")\naxes[1, 0].set_ylabel(\"through the packing\\nz  [cells]\")\nplt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The gas silhouette (the C = \u00bd contour of the gas indicator projected along y) at five shared times, free rise (top) against the packing (bottom). Grains are drawn as the mid-plane section, so a grain outline and the gas can legitimately overlap in projection. The free bubble takes its ellipsoidal shape early and keeps it all the way up; the packed one loses its shape the moment it enters the bed and thereafter wears whatever shape the pore it is in gives it. The centroid and blob count at each of these times are tabulated under the next figure.](index_files/figure-html/fig-frames-output-1.png){#fig-frames}\n:::\n:::\n\n\n::: {#cell-fig-frames-bed .cell execution_count=13}\n``` {.python .cell-code}\nlate = [t for t in LATE if t in bed[\"snaps\"]]\nfig, axes = plt.subplots(1, len(late), figsize=(9.6, 5.2), sharey=True, squeeze=False)\naxes = axes[0]\nfor ax, tt in zip(axes, late):\n    g_ = bed[\"snaps\"][tt]\n    draw(ax, g_, f\"t = {tt:.0f}\\n{fragments(g_)} blob(s)\", True,\n         ylim=(0.6 * BED_Z0, min(NZ, BED_Z1 + 30)))\n    ax.set_xlabel(\"x  [cells]\")\naxes[0].set_ylabel(\"z  [cells]\")\nplt.tight_layout(); plt.show()\n\nprint(f\"{'t':>8} {'z_c':>8} {'blobs':>7}\")\nfor tt in sorted(bed[\"snaps\"]):\n    print(f\"{tt:8.0f} {float(np.interp(tt, bed['t'], bed['zc'])):8.2f} \"\n          f\"{fragments(bed['snaps'][tt]):7d}\")\n```\n\n::: {.cell-output .cell-output-display}\n![The packed run only, at four later times, on the same window and the same projected-silhouette convention. The window is fixed on the bed, so a panel is empty when the bubble has already risen out of it \u2014 the centroid column of the table below says where it is. The number of connected gas blobs holding at least 1 % of the volume is printed under each panel, so 'it broke up' is a measurement rather than an impression.](index_files/figure-html/fig-frames-bed-output-1.png){#fig-frames-bed}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n       t      z_c   blobs\n       0    18.00       1\n     600    36.13       1\n    1200    52.86       1\n    1800    65.51       1\n    2400    79.24       1\n    2900    97.67       1\n    3300   114.61       1\n    3700   131.58       1\n    4200   151.52       1\n```\n:::\n:::\n\n\n## 3. The numbers\n\n::: {#cell-fig-history .cell execution_count=14}\n``` {.python .cell-code}\ndef terminal(r, frac=0.5):\n    \"\"\"mean colour-weighted rise velocity over the last (1 - frac) of the run\"\"\"\n    return float(r[\"vc\"][r[\"t\"] > frac * r[\"t\"][-1]].mean())\n\ndef arrest(r, ref):\n    \"\"\"longest stretch with V_c below a quarter of `ref`; returns (t_start, t_end).\"\"\"\n    m = r[\"vc\"] < 0.25 * ref\n    best, cur = (0, 0), None\n    for k, f in enumerate(m):\n        cur = k if (cur is None and f) else cur\n        if cur is not None and (not f or k == len(m) - 1):\n            if k - cur > best[1] - best[0]:\n                best = (cur, k)\n            cur = None\n    return float(r[\"t\"][best[0]]), float(r[\"t\"][best[1]])\n\nV_FREE = terminal(ctl)\nT_STALL, T_BREAK = arrest(bed, V_FREE)\nZ_STALL = float(np.interp(T_STALL, bed[\"t\"], bed[\"zc\"]))\nZ_BREAK = float(np.interp(T_BREAK, bed[\"t\"], bed[\"zc\"]))\nprint(f\"free terminal rise velocity V_c = {V_FREE:.5f} cells/s = {V_FREE/ctl['Ug']:.3f} U_g\")\nprint(f\"the packed bubble's LONGEST arrest runs from t = {T_STALL:.0f} to t = {T_BREAK:.0f} \"\n      f\"({T_BREAK-T_STALL:.0f} time units = \"\n      f\"{(T_BREAK-T_STALL)/(2*R_BUB/V_FREE):.1f} free-rise diameters' worth of time)\")\nWHERE = (\"against the underside of the bed\"\n         if Z_STALL < BED_Z0 + R_BUB else\n         f\"{(Z_STALL - BED_Z0) / (2 * R_GRAIN):.1f} grain diameters inside the bed\")\nprint(f\"   it happens at z_c = {Z_STALL:.1f} -> {Z_BREAK:.1f} ({WHERE}); \"\n      f\"the bed spans z = {BED_Z0:.0f} .. {BED_Z1:.0f}\")\n\nfig, (a0, a1, a2) = plt.subplots(1, 3, figsize=(10.4, 3.6))\na0.axhspan(Z_BED + R_JAM - R_GRAIN, Z_BED + (BED_HI - BED_LO) - R_JAM + R_GRAIN,\n           color=\"0.85\", lw=0, zorder=0)\nfor r, col, lab in ((ctl, BLUE, \"free rise\"), (bed, RED, \"through the packing\")):\n    a0.plot(r[\"t\"], r[\"zc\"], color=col, lw=1.7, label=lab)\n    a1.plot(r[\"t\"], r[\"vc\"] / r[\"Ug\"], color=col, lw=1.4, label=lab)\n    a2.plot(r[\"t\"], (r[\"vol\"] - 1) * 1e15, color=col, lw=1.4, label=lab)\na1.axvspan(T_STALL, T_BREAK, color=\"0.85\", lw=0, zorder=0)\na1.text(0.5 * (T_STALL + T_BREAK), 0.93 * a1.get_ylim()[1], \"arrest\", ha=\"center\",\n        fontsize=8, color=\"0.35\")\na0.set(xlabel=\"t\", ylabel=\"centroid $z_c$  [cells]\", title=\"Centroid\")\na1.set(xlabel=\"t\", ylabel=r\"$V_c / U_g$\", title=\"Rise velocity\")\na2.set(xlabel=\"t\", ylabel=r\"$(V/V_0 - 1)\\times 10^{15}$\", title=\"Gas volume drift\")\na0.legend(fontsize=8, loc=\"upper left\")\na1.legend(fontsize=8, loc=\"lower right\")\nplt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfree terminal rise velocity V_c = 0.04570 cells/s = 0.723 U_g\nthe packed bubble's LONGEST arrest runs from t = 721 to t = 792 (71 time units = 0.2 free-rise diameters' worth of time)\n   it happens at z_c = 37.9 -> 38.7 (against the underside of the bed); the bed spans z = 38 .. 105\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![Bubble centroid (left) and colour-weighted rise velocity (centre) against time, free rise versus the packing; and the gas-volume drift (right \u2014 note the vertical scale, parts in 1e15). The grey band on the left panel is the bed; the shaded interval on the centre panel is the longest arrest, measured as the longest stretch in which the rise velocity stays below a quarter of the free terminal value. The free bubble reaches one terminal velocity and holds it; the packed one is that same bubble, interrupted.](index_files/figure-html/fig-history-output-2.png){#fig-history}\n:::\n:::\n\n\n::: {#tbl-summary .cell execution_count=15}\n``` {.python .cell-code}\nT_COMMON = float(min(ctl[\"t\"][-1], bed[\"t\"][-1]))     # compare over the SAME window\n\ndef mean_rise(r, tmax=None):\n    m = r[\"t\"] <= (tmax if tmax else r[\"t\"][-1])\n    return float((r[\"zc\"][m][-1] - r[\"zc\"][0]) / (r[\"t\"][m][-1] - r[\"t\"][0]))\n\nV_MOVING = float(bed[\"vc\"][bed[\"t\"] > T_BREAK].mean())   # packed, AFTER breakthrough\n\nprint(f\"{'':>26} {'steps':>7} {'z_c(T)':>9} {'rise/D':>8} {'V/V0 - 1':>11} \"\n      f\"{'solid C':>10} {'iters':>9} {'max|div|':>10} {'wall s':>8}\")\nfor r in (ctl, bed):\n    print(f\"{r['label']:>26} {r['steps']:7d} {r['zc'][-1]:9.2f} \"\n          f\"{(r['zc'][-1]-r['zc'][0])/r['D']:8.2f} {r['vol'][-1]-1:11.2e} \"\n          f\"{r['solid_sum']:10.1e} {r['iters']:6d}/{r['cap']} {r['div']:10.1e} \"\n          f\"{r['wall']:8.0f}\")\n\nSLOWDOWN = mean_rise(ctl, T_COMMON) / mean_rise(bed, T_COMMON)\nprint(f\"\\nover the common window t <= {T_COMMON:.0f}:\")\nprint(f\"   mean advance   free {mean_rise(ctl, T_COMMON):.5f}   packed \"\n      f\"{mean_rise(bed, T_COMMON):.5f}  cells/s   ->  factor {SLOWDOWN:.1f} slower\")\nprint(f\"   but AFTER breakthrough (t > {T_BREAK:.0f}) the packed bubble moves at \"\n      f\"{V_MOVING:.5f} = {V_MOVING/V_FREE:.2f} x the free terminal velocity\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                             steps    z_c(T)   rise/D    V/V0 - 1    solid C     iters   max|div|   wall s\n    free rise (no packing)    2016    124.77     5.34    7.21e-12    0.0e+00     24/600    6.3e-15     1674\n       through the packing    3797    153.74     6.79   -3.44e-15    0.0e+00     23/600    2.8e-14     2335\n\nover the common window t <= 2501:\n   mean advance   free 0.04269   packed 0.02523  cells/s   ->  factor 1.7 slower\n   but AFTER breakthrough (t > 792) the packed bubble moves at 0.03468 = 0.76 x the free terminal velocity\n```\n:::\n:::\n\n\nThree statements worth separating.\n\n**Conservation survives the composition.** The gas volume drifts by\n3\\.4e\\-15 relative over\n3797 steps in the packed run, against a projected flux\ndivergence of 2\\.8e\\-14 \u2014 the Weymouth\u2013Yue transport is exactly\nconservative and inherits the *projection's* residual, nothing more, exactly as it does\nin a bare box. The colour inside the grains is\n0\\.0e\\+00: the transport never leaks gas or liquid into the\nsolid, and the band the curvature stencils read is a separate working field. Note which\nrun is the tidier of the two: the **control**, with no solid at all, drifts by\n7\\.2e\\-12, three orders *worse* than the run with cut\ncells in it \u2014 visible as the sloping blue line in the right-hand panel above. Both are\nnegligible, and neither is explained by its own divergence number; the observation is\nrecorded in [`ISSUES.md`](../../ISSUES.md) rather than rationalised here.\n\n**The projection is comfortable.** 23 iterations against a cap\nof 600 at the worst step, on a variable-density operator with a\nhundredfold density contrast *and* cut cells. That is the number to watch when adapting\nthis: it is what would break first.\n\n**The bed costs a factor 1\\.7 in rise speed, and it charges in\ntwo separate currencies.** The first is a **capillary threshold**: the gas cannot enter a\nthroat until the head over its own vertical extent exceeds $2\\sigma\\cos\\theta/r_t$, so it\nflattens against the constriction and waits. The longest such arrest in this run holds the\nbubble from $t \\approx$ 721 to\n$t \\approx$ 792 \u2014\n0\\.2 free-rise bubble diameters' worth\nof time \u2014 at $z_c \\approx$ 38 cells,\nagainst the underside of the bed. The second currency is ordinary **drag**: what gets past travels on at\n0\\.76 of the free terminal velocity.\n\n**How the two shares divide is a property of the particular bed, and violently so.**\n`dem`'s contact solve accumulates with float atomics on the GPU, so it is not\nbit-reproducible: every execution of this page settles a *statistically equivalent*\npacking rather than the same one, which turns the page into its own small ensemble study.\nThe execution immediately before the one you are reading built a **denser** bed from the\nidentical protocol \u2014 porosity 0.61 against 0\\.64 here, percolation\nthroat 5.34 cells against 5\\.67 \u2014 and there the longest arrest\nlasted **1300** time units, three free-rise diameters, for a net factor **2.7** slower\nrather than 1\\.7. A six per cent difference in the bottleneck\nradius moved the waiting time by more than an order of magnitude. @eq-entry says it\nshould: the threshold scales as $D^{2}/r_t$ against a head the bubble can only raise by\ndeforming, and near the point where the two balance the waiting time is a very stiff\nfunction of the geometry. **That sensitivity, not any single number on this page, is the\ntransferable result** \u2014 and it is why a bubble column is so unforgiving of how its bed\nwas packed.\n\n## 4. The movie\n\nThe `C = \\tfrac12` isosurface of the gas, with the grains cut away at the mid-plane so\nthe interface stays visible.\n\n::: {#movie .cell execution_count=16}\n``` {.python .cell-code code-summary=\"PyVista offscreen renderer -> bubble_through_packing.mp4\"}\nimport pyvista as pv\nimport imageio.v2 as imageio\npv.global_theme.allow_empty_mesh = True\n\ndef render(gas, size=(528, 944)):\n    grid = pv.ImageData(dimensions=(NX + 1, NX + 1, NZ + 1))\n    grid.cell_data[\"gas\"] = np.asarray(gas, dtype=np.float64).flatten(order=\"F\")\n    grid.cell_data[\"solid\"] = np.asfortranarray(SDF).flatten(order=\"F\")\n    pt = grid.cell_data_to_point_data()\n    pl = pv.Plotter(off_screen=True, window_size=size)\n    pl.background_color = \"white\"\n    solid = pt.clip(normal=\"y\", origin=(NX / 2, 0.58 * NX, NZ / 2)).contour(\n        [0.0], scalars=\"solid\")                     # cut the grains open at the mid-plane\n    if solid.n_points:\n        pl.add_mesh(solid, color=\"#aab6c4\", smooth_shading=True, specular=0.3)\n    iso = pt.contour([0.5], scalars=\"gas\")          # the C = 1/2 gas isosurface\n    if iso.n_points:\n        pl.add_mesh(iso, color=\"#e8873a\", smooth_shading=True, specular=0.6)\n    pl.add_mesh(grid.outline(), color=\"#7a7a7a\", line_width=1.0)\n    pl.camera_position = \"xz\"\n    pl.camera.azimuth, pl.camera.elevation = 32.0, 14.0\n    pl.reset_camera(); pl.camera.zoom(1.45)\n    img = pl.screenshot(return_img=True)\n    pl.close()\n    return img\n\nMP4 = \"bubble_through_packing.mp4\"\nwriter = imageio.get_writer(MP4, fps=12, quality=8)\nfor gas in bed[\"frames\"]:\n    writer.append_data(render(gas))\nwriter.close()\nprint(f\"{len(bed['frames'])} frames -> {MP4}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n151 frames -> bubble_through_packing.mp4\n```\n:::\n:::\n\n\n::: {.callout-note}\n## The movie lives on YouTube, not in this repo\nPer [STYLE_GUIDE \u00a77](../../STYLE_GUIDE.md) videos are never committed. The cell above\nwrites `bubble_through_packing.mp4` next to this page when the notebook is executed;\nthe published version embeds it from YouTube. **The iframe below is a placeholder until\nthe upload is done** \u2014 the local file path is recorded in `PROGRESS.md`.\n:::\n\n\n\n\n```{=html}\n<!-- TODO(WO-U E7): replace with the YouTube iframe once the mp4 is uploaded.\n     Local file produced by the `movie` cell: examples/bubble-through-packing/bubble_through_packing.mp4 -->\n<div style=\"max-width:520px;margin:0 auto;padding:2.2rem 1rem;border:1px dashed #9aa4b1;border-radius:6px;text-align:center;color:#5a636e;font-size:0.92em;\">\n  <strong>Movie placeholder</strong><br>\n  The rendered animation is uploaded to YouTube and embedded here.<br>\n  Still frames from the same render follow below.\n</div>\n```\n\n::: {#cell-fig-stills .cell execution_count=17}\n``` {.python .cell-code}\npicks = np.linspace(0, len(bed[\"frames\"]) - 1, 4).astype(int)\nfig, axes = plt.subplots(1, len(picks), figsize=(10.0, 5.4))\nfor ax, k in zip(axes, picks):\n    ax.imshow(render(bed[\"frames\"][k], size=(400, 720)))\n    ax.axis(\"off\")\n    ax.set_title(f\"frame {k+1}/{len(bed['frames'])}\", fontsize=8)\nplt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Stills from the same render, evenly spaced through the run: the gas isosurface (orange) inside the packing, with the grains cut open at the mid-plane so the interface stays visible.](index_files/figure-html/fig-stills-output-1.png){#fig-stills}\n:::\n:::\n\n\n## 5. Density ratio 1000\n\nRatio 100 is the validated regime for the momentum-consistent cut-cell path. Ratio 1000\n\u2014 air in water \u2014 is the one everybody wants, so it is run, at the same $\\mathrm{Eo}$ and\n$\\mathrm{Mo}$ and for a shorter time, and reported whatever it does.\n\n::: {#run-1000 .cell execution_count=18}\n``` {.python .cell-code}\nbed1k = column(packed=True, ratio=1000.0, T=2200.0, label=\"packing, ratio 1000\")\nprint(f\"ratio 1000: {bed1k['steps']} steps, t = {bed1k['t'][-1]:.0f} of {bed1k['T']:g}, \"\n      f\"{bed1k['wall']:.0f} s\"\n      f\"{'   *** NON-FINITE, ABORTED ***' if bed1k['nan'] else ''}\"\n      f\"{'   *** PRESSURE CAPPED, ABORTED ***' if bed1k['capped'] > 20 else ''}\"\n      f\"{('   *** ' + bed1k['aborted'] + ' ***') if bed1k['aborted'] else ''}\")\nprint(f\"  gas volume V(T)/V(0) = {bed1k['vol'][-1]:.10f}\")\nprint(f\"  colour inside the grains {bed1k['solid_sum']:.2e}, \"\n      f\"clipped volume {bed1k['clipped']:.2e}\")\nprint(f\"  pressure {bed1k['iters']}/{bed1k['cap']} \"\n      f\"{'OK' if bed1k['iters'] < bed1k['cap'] else '*** CAPPED -> INVALID ***'}, \"\n      f\"max|div(open u)| {bed1k['div']:.2e}\")\nprint(f\"  centroid {bed1k['zc'][0]:.1f} -> {bed1k['zc'][-1]:.1f} cells\")\n\nm = bed[\"t\"] <= bed1k[\"t\"][-1]\nprint(f\"\\n{'over the same window':>26} {'z_c':>9} {'V/V0 - 1':>11} {'iters':>9} {'max|div|':>10}\")\nfor r, mm in ((bed, m), (bed1k, np.ones_like(bed1k[\"t\"], bool))):\n    print(f\"{r['label']:>26} {r['zc'][mm][-1]:9.2f} {r['vol'][mm][-1]-1:11.2e} \"\n          f\"{r['iters']:6d}/{r['cap']} {r['div']:10.1e}\")\n\nOK1K = not (bed1k[\"nan\"] or bed1k[\"aborted\"] or bed1k[\"iters\"] >= PRESS_CAP)\nR1K_VERDICT = (\"Nothing in that table moves when the density contrast goes up by a \"\n               \"factor of ten.\" if OK1K else\n               \"The ratio-1000 run did NOT survive its window, and the table above says \"\n               \"how far it got before it stopped.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nratio 1000: 1894 steps, t = 2198 of 2200, 1658 s\n  gas volume V(T)/V(0) = 1.0000000000\n  colour inside the grains 0.00e+00, clipped volume 0.00e+00\n  pressure 25/600 OK, max|div(open u)| 4.25e-14\n  centroid 18.0 -> 75.7 cells\n\n      over the same window       z_c    V/V0 - 1     iters   max|div|\n       through the packing     74.93    6.66e-16     23/600    2.8e-14\n       packing, ratio 1000     75.72   -3.00e-15     25/600    4.3e-14\n```\n:::\n:::\n\n\nNothing in that table moves when the density contrast goes up by a factor of ten\\. The\ngas volume drifts by\n3\\.0e\\-15 relative, the colour inside the grains is\n0\\.0e\\+00, the worst pressure solve is\n25 iterations out of 600, and over the\nwindow they share the two centroids differ by\n0\\.9 %.\nRatio 1000 is exactly where an *inconsistent* VoF momentum transport is known to come\napart [@rudman1998; @arrufat2021], so the reason this can be attempted at all is that\n`enable_vof_momentum` composes with the cut cells: the same geometric fluxes carry $C$\nand $\\rho^c\\mathbf{u}$, and the uniform-velocity identity that underwrites it is bitwise\nin a cut cell too. The thing to watch at this contrast is **not** the volume \u2014 the\ntransport's conservation is structural \u2014 but the **pressure iteration count**, because\nthe variable-coefficient Poisson operator's condition number grows with the density\nratio. That is the number the table puts next to it, and it is the one that would break\nfirst on a longer run or a tighter bed.\n\n## Collocated cross-check\n\npeclet also ships a cell-centred grid (`flow.SolverColocated`), and since rung V8 it\nruns two-phase flow: variable density inside the **approximate (ABC) projection**, with\nbuoyancy and surface tension applied as **face accelerations** and the colour advected\nby the projected face field.\n\n**The packed case cannot be run there, and that is a scope statement, not a defect.**\nRung V8 is **all-fluid**: the cut-cell colour transport \u2014 openness-weighted fluxes, the\nsolid-band fill, the contact-angle plane \u2014 exists on the staggered grid only, and the\ncomposition is refused rather than silently approximated.\n\n::: {#colocated-scope .cell execution_count=19}\n``` {.python .cell-code}\nn = 32\nq = np.arange(n) + 0.5\none_grain = np.asfortranarray(np.sqrt((q[:, None, None] - n / 2) ** 2\n                                      + (q[None, :, None] - n / 2) ** 2\n                                      + (q[None, None, :] - n / 2) ** 2) - 8.0)\nsc = flow.SolverColocated(n, n, n)\nsc.set_rho(1.0); sc.set_mu(0.1)\nsc.set_solid(one_grain, cutcell_pressure=True)     # ONE grain is enough to trip the guard\ntry:\n    sc.enable_vof()\n    print(\"enable_vof() succeeded \u2014 the packed case would run on the collocated grid\")\nexcept RuntimeError as e:\n    print(f\"enable_vof() after set_solid raised RuntimeError:\\n  {e}\")\ntry:\n    flow.SolverColocated(8, 8, 8).enable_vof_momentum(1.0, 100.0)\nexcept RuntimeError as e:\n    print(f\"\\nenable_vof_momentum on the collocated grid: RuntimeError\\n  {str(e)[:150]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nenable_vof() after set_solid raised RuntimeError:\n  enable_vof: geometric VoF on SolverColocated (rung V8) is ALL-FLUID only \u2014 an immersed solid needs the cut-cell face acceleration and the matching one-sided closures, which is a later rung. Use the staggered Solver (rung V5a supports cut cells).\n\nenable_vof_momentum on the collocated grid: RuntimeError\n  enable_vof_momentum: momentum-consistent VoF transport is STAGGERED-ONLY (rung V2b); the collocated construction is Favre-averaged face states, rung V\n```\n:::\n:::\n\n\nWhat *can* be cross-checked is the **control** \u2014 the free rise in the same closed\ncolumn, which is all-fluid. `enable_vof_momentum` is staggered-only, so the honest pair\nis the two grids with momentum consistency **off** on both.\n\n::: {#colocated-run .cell execution_count=20}\n``` {.python .cell-code}\nT_CO = 1500.0\nctl_nc = column(packed=False, momentum=False, T=T_CO, label=\"control, staggered, no mom.\")\nctl_co = column(packed=False, momentum=False, T=T_CO, cls=flow.SolverColocated,\n                label=\"control, collocated, no mom.\")\nprint(f\"{'free rise, ratio 100, momentum consistency OFF':>46} {'z_c(T)':>9} {'dz_c/dt':>10} \"\n      f\"{'/U_g':>7} {'V/V0-1':>10} {'iters':>9}\")\nfor r in (ctl_nc, ctl_co):\n    print(f\"{r['label']:>46} {r['zc'][-1]:9.2f} {mean_rise(r):10.5f} \"\n          f\"{mean_rise(r)/r['Ug']:7.3f} {r['vol'][-1]-1:10.1e} {r['iters']:6d}/{r['cap']}\")\nDCO = 100 * (mean_rise(ctl_co) / mean_rise(ctl_nc) - 1)\nprint(f\"\\ncollocated vs staggered rise speed: {DCO:+.2f} %\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\npeclet::flow SolverColocated: AUTO scheme fell back to gauge-exact (configuration unsupported by the ghost projection v1). Select explicitly with set_collocated_scheme to silence this notice.\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nfree rise, ratio 100, momentum consistency OFF    z_c(T)    dz_c/dt    /U_g     V/V0-1     iters\n                   control, staggered, no mom.     78.82    0.04057   0.641    4.0e-12     23/600\n                  control, collocated, no mom.     79.04    0.04078   0.645    4.0e-12     22/600\n\ncollocated vs staggered rise speed: +0.53 %\n```\n:::\n:::\n\n\nThe two grids agree on the free rise to\n0\\.5 %. That is the useful statement here: the collocated path\nreproduces the *fluid* half of this page, and everything the packing adds \u2014 the cut-cell\ntransport, the wetting fill, the momentum consistency \u2014 is staggered-only today. The\n[rising bubble](../rising-bubble/index.qmd) page states the other half of the rating:\ncollocated two-phase flow is honest to density ratio $\\lesssim 100$ for cases with\nmotion.\n\n## What this page does *not* establish\n\n- **There is no reference solution.** No published benchmark exists for this geometry,\n  and none is claimed. The control is the yardstick, and it is a weak one: it fixes the\n  fluid pair and the column, not the answer.\n- **The contact angle is static.** $\\theta$ does not depend on the contact-line\n  velocity \u2014 no dynamic angle, no hysteresis \u2014 and a bubble squeezing through a throat\n  is exactly the situation where an advancing and a receding line differ. At\n  $\\theta = 60\u00b0$ the liquid wets, so the gas mostly keeps a film between itself and the\n  grains and the contact line is short; that is why this scene was chosen, and it is\n  also why the number to distrust would be one that depended on $\\theta$.\n  See [droplet wetting](../droplet-wetting/index.qmd) for the accuracy the static model\n  has (\u2248 1\u00b0 up to 90\u00b0, and a contact radius of ten cells or more).\n- **One realisation, one resolution.** A packing is a random object; this is one seed.\n  The throat the bubble happens to meet first is a property of that seed.\n- **The bottleneck is 11 cells across.** That is enough for\n  the geometric transport, but an interface that fills such a throat gives the\n  height-function curvature cascade only a few columns to fit, so the curvature there is\n  its least accurate branch. A resolution study at fixed $\\mathrm{Eo}$ and fixed\n  geometry is the missing measurement, and it is the one that would say how much of the\n  arrest time above is physics.\n- **The packing is not bit-reproducible.** `dem`'s contact solve accumulates forces with\n  float atomics on the GPU, so the settled centres differ slightly between runs and a\n  re-execution of this page gets a *statistically equivalent* bed, not the same one \u2014\n  with a different bottleneck and a different arrest. Everything quoted here is inline\n  from the frozen execution; the qualitative statements are the ones that carry over.\n\n## Adapt this yourself\n\n- **Trap the bubble.** Raise `F_SDF` towards 1 (grains nearer to contact) or lower\n  `Eo`, and @eq-entry stops being satisfiable: the bubble parks under a throat and\n  stays. That is capillary trapping, and it is the whole subject of residual gas\n  saturation in porous media.\n- **Non-wetting gas.** `set_contact_angle(120)` makes the gas cling to the grains\n  instead of avoiding them, which changes both the entry pressure and the path.\n  `set_contact_angle_field(theta_array)` gives mixed wettability \u2014 a per-cell angle, so\n  a patchily wetted bed is one array away.\n- **A train of bubbles.** Add a second sphere to `bubble_colour`, or replace the closed\n  floor by a two-phase inflow (`set_vof_inflow`) and inject continuously.\n- **A real bed.** Swap `settle_bed` for the Lubachevsky\u2013Stillinger packing of the\n  [random packed bed](../random-packed-bed/index.qmd) page, or for the\n  [Pall rings](../pall-ring-packing/index.qmd) \u2014 the fluid side does not change, only\n  the SDF.\n- **Go multi-rank.** The identical script runs under `mpirun -np N python \u2026`; the\n  cut-cell VoF transport and the solid-band fill are built on the inner region and\n  exchanged, so the filled colour is decomposition-independent.\n\n## Reproduce this\n\nThe compiled solver runs this, so its outputs are **frozen** into the site. To\nregenerate:\n\n```bash\npip install peclet            # CPU wheels; for CUDA: pip install peclet-flow-cu13\nPECLET_FLOW_EXACT_RESIDUAL=1 quarto render examples/bubble-through-packing/index.qmd --execute\n# ...or against local source builds of the suite (GPU):\nPECLET_LOCAL_BUILD=/path/to/suite/flow/build_cuda:/path/to/suite/dem/build_cuda \\\nPECLET_FLOW_EXACT_RESIDUAL=1 OMP_NUM_THREADS=8 OMP_PROC_BIND=false \\\n  quarto render examples/bubble-through-packing/index.qmd --execute\n```\n\nThe solver-side gates for the pieces this page composes are, in the `flow` repo, the\n`vof_cutcell`, `vof_wetting` and `vof_collocated` ctests with their MPI twins at\nnp = 1/2/4, and the study scripts `tests/study/vof_wetting.py` and\n`tests/study/vof_surface_tension.py`.\n\n", "supporting": ["index_files"], "filters": [], "includes": {}}}