{
  "hash": "c86ae7d926a1cffd20d801f22450b869",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"peclet.dem vs the DEM8 bulk-process benchmark\"\nsubtitle: \"The three Dosta et al. (2024) community benchmark cases — silo emptying, drum mixing, particle impact — run one-on-one against the two best-performing open-source DEM codes on identical hardware and identical initial states.\"\nauthor: \"Peclet\"\ndate: \"2026-07-18\"\ncategories: [dem, accuracy, performance, benchmark, validation]\njupyter: python3\nresources:\n  - data/\n  - scripts/\n---\n\n\n## What this measures\n\nDosta et al., *\"Comparing open-source DEM frameworks for simulations of common bulk\nprocesses\"* ([CPC **296** (2024) 109066](https://doi.org/10.1016/j.cpc.2023.109066)),\nbenchmarked **eight** open-source DEM codes (LIGGGHTS, Yade, MUSEN, MercuryDPM, Kratos,\nMFiX, GranOO, Blaze-DEM) on three mid-size bulk processes with shared initial states\n([Zenodo dataset](https://doi.org/10.5281/zenodo.8252892)):\n\n1. **Silo emptying** — 100 000 particles (d = 4 mm) discharging from a cylindrical\n   steel silo through a 0.06 m (\"large\") or 0.04 m (\"small\") orifice, 5 s;\n2. **Drum mixing** — a bimodal bed (30k × 1 mm + 8k × 2 mm) in a Ø 0.2 m drum at\n   2 rad/s, 5 s;\n3. **Particle impact** — a steel ball (d = 20 mm) striking a settled granular bed of\n   25k / 50k / 100k particles at 5 m/s.\n\nThis page runs the same three cases with **`peclet.dem`** — from the *same* initial\nparticle positions — and, for a like-for-like comparison on *this* machine, re-runs\nthe two best performers from the paper: **MUSEN** (the fastest GPU code together with\nBlaze-DEM) on the same GPU, and **LIGGGHTS** (among the fastest CPU codes) on 24 MPI\nranks. Yade is Debian-packaged but not installable here without root; Blaze-DEM\n(2015-era CUDA) no longer compiles on CUDA 13; MFiX's download is registration-walled.\nThe paper's own multi-code figures serve as the ensemble reference throughout.\n\n::: {.callout-important}\n## An impulse-based method benchmarked against force-based codes\n\nAll eight paper codes integrate the **Hertz–Mindlin viscoelastic force model** with\ntime steps of 0.5–1.5 µs set by the contact stiffness. `peclet.dem` is an\n**impulse-based (XPBD-style) solver**: contacts are rigid at the velocity level,\ndissipation enters through the restitution coefficient *e* and Coulomb friction *µ*,\nand **Young's modulus does not appear at all**. Time steps are set by kinematics, not\nstiffness — here 50 µs (impact) to 200 µs (silo), i.e. **40–130× larger** than the\nreference codes. The benchmark's bulk observables (discharge rate, mixing curves,\npenetration depth) are exactly the quantities such a method claims to capture; this\npage measures how far that claim holds, and reports where it doesn't.\n:::\n\n**Material mapping.** Densities, restitution and friction pairs are taken verbatim\nfrom the paper (M1–M1 e = 0.5, µ = 0.3; M2–M2 0.4/0.4; grain–steel 0.4/0.2;\nsteel–steel 0.6/0.5). `peclet.dem` started this benchmark with one global\ngrain–grain material; the first runs approximated the drum's M1–M2 pair and the\nimpact ball's steel pairs with it, and the measured rebound deficit that produced\n(see Case 3) motivated adding a proper **per-pair material table**\n(`set_material_ids` / `set_pair_material`, with walls resolvable through the same\ntable) during the benchmark. The final peclet curves below use the paper's pair\nvalues exactly; the approximated runs are kept in `data/` as a sensitivity record.\n\n::: {#398b1b42 .cell execution_count=1}\n``` {.python .cell-code code-summary=\"Data loading + shared figure style\"}\nimport json, os\nimport numpy as np\nimport matplotlib.pyplot as plt\n\nDATA = \"data\"\nplt.rcParams.update({\"figure.dpi\": 130, \"font.size\": 10, \"axes.grid\": True,\n                     \"grid.alpha\": 0.3, \"axes.axisbelow\": True,\n                     \"figure.facecolor\": \"white\", \"savefig.bbox\": \"tight\"})\n\n# fixed code -> colour assignment, used identically in every figure\nC_PECLET  = \"#2a78d6\"   # peclet.dem, shipped solver (grounded statics)\nC_SYMPGS  = \"#1baf7a\"   # peclet.dem, symmetric warm-started PGS (experimental config)\nC_JACOBI  = \"#eda100\"   # peclet.dem, legacy Jacobi velocity solve\nC_MUSEN   = \"#4a3aa7\"   # MUSEN v1.75, GPU, this machine\nC_LIG     = \"#e34948\"   # LIGGGHTS-public, 24 MPI ranks, this machine\n\ndef ld(name):\n    p = os.path.join(DATA, name + \".npz\")\n    return np.load(p) if os.path.exists(p) else None\n\nTIM = json.load(open(os.path.join(DATA, \"timings.json\")))\n```\n:::\n\n\n## Case 3 — particle impact: the sharpest discriminator\n\nA steel ball (d = 20 mm, ρ = 7200 kg/m³) enters a settled bed of 2 mm particles at\n5 m/s; the measured result is the ball's vertical displacement over 0.1 s. The three\nbed sizes probe different physics: at **25k/50k** the bed is shallow and the ball's\narrest is **floor-limited** (it reaches the box bottom through the bed); at **100k**\nthe bed is deep and arrest is **bed-strength-limited** — the granular skeleton itself\nmust stop the ball.\n\n::: {#cell-fig-impact .cell execution_count=2}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 3, figsize=(10.5, 3.4), sharey=True)\nfor ax, n in zip(axes, (25, 50, 100)):\n    for tag, color, ls, label in (\n            (\"liggghts\",        C_LIG,    \"-\",  \"LIGGGHTS\"),\n            (\"musen\",           C_MUSEN,  \"-\",  \"MUSEN\"),\n            (\"peclet_onesided\", C_PECLET, \"-\",  \"peclet.dem (shipped)\"),\n            (\"peclet_sympgs\",   C_SYMPGS, \"--\", \"peclet.dem (sym. PGS)\"),\n            (\"peclet_jacobi\",   C_JACOBI, \":\",  \"peclet.dem (Jacobi)\")):\n        d = ld(f\"case3_{n}k_{tag}\")\n        if d is None:\n            continue\n        ax.plot(d[\"t\"], d[\"z\"] - 0.06, color=color, ls=ls, lw=1.6, label=label)\n    ax.set_title(f\"{n}k bed\")\n    ax.set_xlabel(\"t [s]\")\n    ax.set_xlim(0, 0.1)\naxes[0].set_ylabel(\"vertical displacement [m]\")\naxes[0].legend(fontsize=7.5, loc=\"lower right\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Impactor vertical displacement, three bed sizes. peclet.dem is shown in its shipped configuration and in the symmetric warm-started PGS configuration (see the solver note below); MUSEN and LIGGGHTS are re-runs on this machine from the same initial states. Paper Fig. 10 shows the eight-code ensemble spanning the same envelope as MUSEN/LIGGGHTS here.](index_files/figure-html/fig-impact-output-1.png){#fig-impact}\n:::\n:::\n\n\n**Shallow beds (25k, 50k): quantitative agreement.** In its momentum-conserving\nconfigurations `peclet.dem` lands on the references: minimum displacement −0.140 m\n(LIGGGHTS −0.139, MUSEN −0.138) at the same instant t ≈ 0.030 s for 25k, and the same\n−0.139 at t ≈ 0.044 s for 50k. The penetration phase — the part of the trajectory the\npaper found consistent across all eight codes — is reproduced **exactly**, at a 100×\nlarger time step. The rebound (which the paper itself reports as chaotic, spanning\n−0.013 to −0.07 across codes and requiring 10-seed ensembles) initially came out at\n−0.083, below the envelope — and that gap was **traced to the material mapping, not\nthe solver**: with a per-pair material table added to `peclet.dem` (so the ball–bed\npair gets its 0.4/0.2 and the ball–floor pair its steel–steel 0.6/0.5, exactly as in\nthe reference codes), the 25k rebound lands at **−0.040, mid-envelope**, with the\npenetration unchanged. A worked example of why benchmark fidelity needs pairwise\nmaterials rather than a single global pair.\n\n**Deep bed (100k): the two peclet configurations bracket the truth.** MUSEN and\nLIGGGHTS agree to the millimetre here (plateau −0.0905/−0.0909, no rebound). The\nshipped `peclet.dem` solver arrests the ball at −0.016 (too rigid), the symmetric-PGS\nconfiguration lets it sink to −0.136 (too soft). The reference plateau sits between\nthe two. The root causes are known solver-level items, quantified for the first time\nby this case — see [the solver note](#the-solver-note) below.\n\n## Case 1 — silo emptying\n\n::: {#cell-fig-silo .cell execution_count=3}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 2, figsize=(9, 3.6), sharey=True)\nfor ax, o in zip(axes, (\"large\", \"small\")):\n    for tag, color, ls, label in (\n            (\"liggghts\",        C_LIG,    \"-\",  \"LIGGGHTS\"),\n            (\"musen\",           C_MUSEN,  \"-\",  \"MUSEN\"),\n            (\"peclet_onesided\", C_PECLET, \"-\",  \"peclet.dem (shipped)\"),\n            (\"peclet_sympgs\",   C_SYMPGS, \"--\", \"peclet.dem (sym. PGS)\")):\n        d = ld(f\"case1_{o}_M1_{tag}\")\n        if d is None:\n            continue\n        ax.plot(d[\"t\"], np.asarray(d[\"count\"]) / 1000, color=color, ls=ls, lw=1.6,\n                label=label)\n    if o == \"large\":\n        tt = np.linspace(0.15, 4.35, 10)\n        ax.plot(tt, 100 - 23.2 * (tt - 0.15), color=\"0.55\", ls=\":\", lw=1.2,\n                label=\"paper mean rate\")\n    ax.set_title(f\"{o} orifice, M1\")\n    ax.set_xlabel(\"t [s]\")\n    ax.set_xlim(0, 5)\naxes[0].set_ylabel(\"particles above orifice [k]\")\naxes[0].legend(fontsize=7.5, loc=\"upper right\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Particles remaining above the orifice vs time, large-orifice (left) and small-orifice (right) silos with M1 particles. The dotted grey guide is the paper's mean large-orifice discharge rate (23.2k/s, all codes within ±5%).](index_files/figure-html/fig-silo-output-1.png){#fig-silo}\n:::\n:::\n\n\n::: {#e5d506a6 .cell execution_count=4}\n``` {.python .cell-code code-summary=\"Discharge-rate table\"}\ndef rate(d, t0=0.5, t1=3.5):\n    if d is None:\n        return None\n    t, N = np.asarray(d[\"t\"]), np.asarray(d[\"count\"])\n    m = (t >= t0) & (t <= t1) & (N > 2000)\n    return -np.polyfit(t[m], N[m], 1)[0] / 1000 if m.sum() > 3 else None\n\nrows = []\nfor o in (\"large\", \"small\"):\n    for tag, name in ((\"musen\", \"MUSEN\"), (\"liggghts\", \"LIGGGHTS\"),\n                      (\"peclet_onesided\", \"peclet.dem (shipped)\"),\n                      (\"peclet_sympgs\", \"peclet.dem (sym. PGS)\")):\n        r = rate(ld(f\"case1_{o}_M1_{tag}\"))\n        if r:\n            rows.append((f\"{o} / {name}\", r))\nfrom IPython.display import Markdown\nlines = [\"| silo / code | discharge rate [10³/s] |\", \"|---|---|\"]\nlines += [f\"| {a} | {b:.1f} |\" for a, b in rows]\nbig = {n.split(\" / \")[1]: r for n, r in rows if n.startswith(\"large\")}\nsmall = {n.split(\" / \")[1]: r for n, r in rows if n.startswith(\"small\")}\nfor k in big:\n    if k in small:\n        lines.append(f\"| large/small ratio, {k} | {big[k]/small[k]:.2f} |\")\nMarkdown(\"\\n\".join(lines))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=4}\n| silo / code | discharge rate [10³/s] |\n|---|---|\n| large / MUSEN | 24.2 |\n| large / LIGGGHTS | 24.5 |\n| large / peclet.dem (shipped) | 19.4 |\n| large / peclet.dem (sym. PGS) | 32.6 |\n| small / MUSEN | 7.7 |\n| small / peclet.dem (shipped) | 7.2 |\n| small / peclet.dem (sym. PGS) | 15.1 |\n| large/small ratio, MUSEN | 3.13 |\n| large/small ratio, peclet.dem (shipped) | 2.71 |\n| large/small ratio, peclet.dem (sym. PGS) | 2.16 |\n:::\n:::\n\n\nThree observations (all numbers for the final build, i.e. with the per-pair\nmaterials and the friction-bound fix of [the solver note](#the-solver-note)):\n\n- **The shipped solver has the right flow character** — a strictly linear N(t),\n  i.e. the head-*independent* mass flow that granular physics (and the paper's\n  Beverloo analysis) demands — but discharges **~20% slow**: 19.4 k/s (large) and\n  7.2 k/s (small) against 24.2/24.5 k/s and 7.7 k/s for MUSEN/LIGGGHTS on this\n  machine (paper mean 23.2 k/s ± 5%). Its large/small ratio 2.71 sits below the\n  Beverloo-consistent 3.10 ± 0.06 (MUSEN here: 3.13).\n- **The symmetric-PGS configuration is fast *and* has the wrong character**: its\n  rate decays with the remaining head (41 → 31 k/s for the large orifice, +95% for\n  the small one) — liquid-like, Torricelli-style discharge. That is the signature\n  of an under-supported bed: without load-bearing chains strong enough to form an\n  arch at the orifice, the outflow feels the full hydrostatic head.\n- Together the two configurations **bracket the references**, and the *qualitative*\n  split (right character/slow vs wrong character/fast) points at the same two open\n  solver items as the impact and drum cases.\n\n## Case 2 — drum mixing\n\nThe drum discriminates *segregation and convection* rather than statics: 30k small\nparticles start layered on top of 8k large ones, and the counter-clockwise rotation\n(2 rad/s) mixes and then partially re-segregates the species. The measured quantities\nare the species counts in two diagonal quadrant zones over time.\n\n::: {.callout-note}\nThe bimodal pair materials (M1–M2 e = 0.45, µ = 0.2) cannot yet be expressed in\n`peclet.dem`'s single global pair material; the runs below use e = 0.45, µ = 0.25\nfor all grain–grain contacts. A per-pair material table is the top item this\nbenchmark adds to the roadmap.\n:::\n\n::: {#cell-fig-drum .cell execution_count=5}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(7.5, 3.4))\nfor tag, color, ls, label in (\n        (\"liggghts\", C_LIG, \"-\", \"LIGGGHTS\"),\n        (\"musen\",    C_MUSEN, \"-\", \"MUSEN\"),\n        (\"peclet_onesided\", C_PECLET, \"-\", \"peclet.dem (shipped)\"),\n        (\"peclet_sympgs\",   C_SYMPGS, \"--\", \"peclet.dem (sym. PGS)\")):\n    d = ld(f\"case2_{tag}\")\n    if d is None:\n        continue\n    ax.plot(d[\"t\"], np.asarray(d[\"z2_m1\"]) / 1000, color=color, ls=ls, lw=1.6,\n            label=label)\nax.set_xlabel(\"t [s]\")\nax.set_ylabel(\"M1 particles in Zone 2 [k]\")\nax.set_xlim(0, 5)\nax.legend(fontsize=8)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Small-particle (M1) count in Zone 2 (lower-left quadrant) over 5 s of drum rotation — the paper's Fig. 8 observable, oscillating at the bed-circulation period with decaying amplitude as the species mix.](index_files/figure-html/fig-drum-output-1.png){#fig-drum}\n:::\n:::\n\n\nThe references agree with each other and the paper: a large oscillation (≈ 0 ↔ 23k)\nat the bed-circulation period ≈ 2 s, decaying as the species mix. `peclet.dem` is at\nits weakest here. Before the friction-bound fix of [the solver note](#the-solver-note)\nthe bed did not circulate *at all* (a dead-flat count — the drum is driven purely\nthrough wall friction, which the warm-started solver had silently disabled); with\nthe fix it circulates, but 2–4× slower than the references and with far weaker\namplitude. A control run with the legacy Jacobi solver — whose friction bound is\naccidentally *inflated* (it re-counts the same approach every iteration) — matches\nthe references' circulation pace, which localises the deficit precisely: with an\nhonest per-substep Coulomb bound, velocity-level friction cannot transmit enough\nstatic shear, and the missing piece is sequential-impulse tangential stick. The drum\nis therefore the cleanest quantitative target for that (long-known, now measured)\nsolver item.\n\n## Performance\n\n::: {.callout-warning}\n## Read the timings with care\n\nThe paper's Table 6 was measured on a Ryzen 3900X (12c) + TITAN RTX. This machine is\na Threadripper PRO 5965WX (24c) + RTX 5080 — both roughly a factor ~2 newer/larger,\nand the GPU numbers below were taken while the GPU was **shared with unrelated\ncompute jobs** (marked ◐). MUSEN (like Blaze-DEM) computes in **double precision**,\nwhich consumer GPUs execute at 1/32–1/64 rate; `peclet.dem` is single-precision by\ndesign. And the deepest structural difference stands: the reference codes take\n200 000–3 300 000 steps per case where `peclet.dem` takes 2 000–25 000. Same-machine,\nsame-initial-state wall-clock is reported because it is what a user experiences; it\nis *not* a controlled algorithmic comparison.\n:::\n\n| case | peclet.dem (GPU) | MUSEN (GPU) | LIGGGHTS (24 MPI ranks) |\n|---|---|---|---|\n| impact 25k (0.1 s) | **16 s** | 61 s | 1 839 s |\n| impact 100k (0.1 s) | **67 s** | 504 s ◐ | 913 s |\n| silo large M1 (5 s) | **171 s** | ≈ 1 360 s † | 5 892 s |\n| drum (5 s) | **399 s** | 5 587 s ◐ | 15 855 s |\n\nUnmarked numbers were measured with the GPU otherwise idle; ◐ marks runs that\nshared the GPU with unrelated compute (they overstate the true time — MUSEN's clean\n25k impact, 61 s, ran 22× faster than its contended attempt). † MUSEN's clean silo\nrerun reached 88% in 1 196 s before a CUDA driver hiccup killed it; the quoted time\nextrapolates that pace and is consistent with the paper's 28 min on a TITAN RTX.\nFull per-run values (and the contended history) are in `data/timings.json`.\n\nMeasured clean-to-clean, `peclet.dem` runs **4–8× faster than MUSEN** — the fastest\nGPU code of the study together with Blaze-DEM — and **14–115× faster than LIGGGHTS\non 24 ranks**, the direct dividend of the impulse formulation's stiffness-free time\nstep (2 000–25 000 steps per case against 200 000–3 300 000). Two structural notes\ntemper the comparison: MUSEN computes in double precision, which consumer GPUs\nexecute at 1/32–1/64 rate, while `peclet.dem` is single-precision by design; and at\nthese particle counts `peclet.dem` is launch-latency-bound (the 25k impact costs\n8 ms/step against ~26 ms/step for a *one-million*-particle bed in the fluidized-bed\nexample), so its advantage grows with problem size.\n\n## The solver note {#the-solver-note}\n\nThis benchmark was run against `peclet.dem`'s new warm-started PGS contact solver,\nand it surfaced three solver-level findings. Two were **fixed during the benchmark\nand are part of the featured curves**; one is an open design item with, now,\nquantified targets.\n\n**1 — Per-pair materials (fixed).** The single global grain–grain material\nunder-represented the impact ball's steel pairs; adding the pair table moved the 25k\nrebound from below the published envelope to mid-envelope with penetration unchanged\n(§ Case 3).\n\n**2 — The warm start silently disabled friction (fixed).** A friction sweep showed\nsilo discharge *entirely independent of µ* (0 → 0.9, identical curves). Mechanism:\nthe Coulomb bound was accumulated from contact *approach velocities* each velocity\niteration — and the PGS warm start pre-applies the converged impulses, so approaches\nare already ≈ 0 and the bound collapses. Re-bounding friction by the PGS impulse\naccumulator itself (which *is* the converged normal load) restored qualitative drum\ncirculation (a dead-flat Zone-2 count became the reference-like oscillation) and\nmoved the shipped silo rate from 18.1 to 19.4 k/s. Two residuals remain measurable:\nthe drum under-drives (weaker oscillation amplitude than MUSEN/LIGGGHTS) and the\nsymmetric-configuration silo still discharges head-dependently — both signatures of\nthe velocity-level friction lacking *tangential stick* (sequential-impulse\naccumulation of the tangential impulse), a known deferred item that this benchmark\nturns into two concrete targets: reference drum amplitude, and Beverloo-constant\ndischarge without the one-sided branch.\n\n**3 — The grounded one-sided shock branch is too strong for ballistic loads\n(open).** Added to hold deep static beds under gravity (a real failure mode: without\nit a silo bed free-falls collectively, and the warm-started symmetric solve alone\ndoes not restore the arch), the one-sided treatment makes a ballistic impactor meet\nan effectively infinite-mass bed: at 2880:1 ball/grain mass ratio the 25k ball stops\nwithin 2 mm of the surface with zero rebound (blue curve, 25k panel), the deep-bed\n100k impact arrests at −0.023 vs the references' −0.090, and silo discharge runs\n~20% slow. Disabling it (the *symmetric PGS* configuration) restores exact\nshallow-bed impact but over-penetrates the deep bed (−0.137) — **the references sit\nbetween the two configurations in every statics-sensitive observable**. Quantified\ntargets for the gate design: 100k plateau −0.090, silo 23–25 k/s at Beverloo ratio\n3.1.\n\nAll three, with the numbers above, are logged in [`ISSUES.md`](../../ISSUES.md).\n\n## Reproduce this\n\nThe runner scripts (one per case), the reference-code build recipes, and the\ncollection script live in [`scripts/`](scripts/) beside this page. The shared\ninitial states download from the paper's\n[Zenodo record](https://doi.org/10.5281/zenodo.8252892). The peclet runs need only\n`pip install peclet[dem]` and a GPU; MUSEN builds CLI-only with\n`cmake -DMUSEN_BUILD_GUI=OFF`; LIGGGHTS builds with `make auto` (VTK optional —\nthe benchmark inputs here have the VTK dumps removed).\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}