{
  "hash": "ff4b89b98f82dd2b0c20639ba96d1f77",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Non-spherical Stokes drag: exact spheroids, then cubes\"\nsubtitle: \"Measure a shape's drag against a sphere of the same volume in the same periodic box, so the box cancels — validated against the exact Oberbeck spheroid solution before it is used to predict anything.\"\nauthor: \"Peclet\"\ndate: \"2026-08-30\"\ncategories: [flow, IBM, csg, verification, analytic, drag, GPU]\njupyter: python3\n---\n\n\n\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/computational-chemical-engineering/peclet-examples/blob/main/examples/nonsphere-drag/index.ipynb){target=\"_blank\"}\n&nbsp;GPU example — the frozen page reads correctly without a solver.\n\n## What you'll learn\n\nEngineering correlations for non-spherical drag are built on *sphericity*: one number standing in\nfor a shape. It is worth knowing how well that works, and the only way to find out is to measure\nshapes whose drag you can also compute exactly.\n\nThis page does that in three moves:\n\n1. **Establish the method.** Drag in a periodic box is not drag in an unbounded fluid — at solid\n   fraction $\\phi$ the difference is tens of percent. Measuring a shape *and* an equal-volume sphere\n   in the **same** box and reporting the ratio makes the leading blockage cancel. That is an\n   assumption, so it gets a ladder.\n2. **Validate it against an exact solution.** A prolate spheroid's Stokes drag is known in closed\n   form (Oberbeck 1876; Happel & Brenner §4-26), both along and across its axis. If the ratio method\n   reproduces those, the method is sound.\n3. **Then predict.** With the method validated, the cube and the spherocylinder become measurements\n   worth quoting, and the sphericity correlations become the thing under test rather than the\n   reference.\n\nAlong the way: `peclet.core.geom`'s leaves differ in whether they are **distance-exact** (sphere,\nbox, capsule) or only a **bound** (ellipsoid, superquadric). Whether that matters for a cut-cell\nsolver is an empirical question, and this page answers it.\n\n::: {#bootstrap .cell execution_count=1}\n``` {.python .cell-code code-summary=\"Environment bootstrap (installs peclet from PyPI on Colab/Binder)\"}\nimport importlib.util, os, subprocess, sys\n_local = os.environ.get(\"PECLET_LOCAL_BUILD\")\nif _local:\n    for p in _local.split(os.pathsep):\n        sys.path.insert(0, p)\nelif importlib.util.find_spec(\"peclet\") is None:\n    subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"-q\", \"peclet\"], check=True)\n```\n:::\n\n\n::: {.callout-note}\n## Requires a recent `peclet`\n`peclet.core.geom`, the analytic-scene API and `hydro_force_torque_reaction` are newer than the\ncurrent PyPI release. The page is frozen and renders regardless.\n:::\n\n::: {#80875084 .cell execution_count=2}\n``` {.python .cell-code}\nimport time\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom scipy.special import gamma as gamma_fn\nfrom peclet import flow as sdflow\nfrom peclet.core import geom\n\nplt.rcParams.update({\"figure.dpi\": 130, \"font.size\": 9, \"axes.axisbelow\": True,\n                     \"figure.facecolor\": \"white\", \"savefig.bbox\": \"tight\"})\n\nRHO, MU, FBODY = 1.0, 0.1, 1e-4        # cell units: h = 1\nRV = 8.0                                # volume-equivalent RADIUS, in cells — fixed across boxes\nVOL = 4.0 / 3.0 * np.pi * RV ** 3\nKI_I, KI_R = 2, 17\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nKokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set\n  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads\n  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true\n  For unit testing set OMP_PROC_BIND=false\n\n```\n:::\n:::\n\n\n## The method\n\nHold the body fixed, drive the fluid with a uniform body force $f$, and read the force on the body\nfrom the **discrete reaction** — the momentum the fluid actually lost to it. Define\n\n$$\n\\lambda \\;=\\; \\frac{F_{\\text{body}}}{6\\pi\\mu R_v \\langle u\\rangle},\n$$ {#eq-lambda}\n\nwith $R_v$ the volume-equivalent radius and $\\langle u\\rangle$ the superficial (whole-box) mean\nvelocity. For a sphere this is exactly the simple-cubic array drag ratio Hasimoto (1959) gives in\nclosed form, so the sphere run is a calibration of the whole chain. For any other shape at the same\nvolume, $K = \\lambda_{\\text{shape}} / \\lambda_{\\text{sphere}}$ is the drag correction factor with\nthe box divided out.\n\n::: {#driver .cell execution_count=3}\n``` {.python .cell-code}\n_RCACHE = {}\nVSOL = {}      # (label, N) -> the solver's own count of SOLID staggered cells\n\ndef run(build, n, label, tol=1e-7, dt=1000.0, maxit=3000):\n    key = (label, n, tol, dt, maxit)\n    if key not in _RCACHE:\n        _RCACHE[key] = _run(build, n, label, tol, dt, maxit)\n    return _RCACHE[key]\n\ndef _run(build, n, label, tol, dt, maxit):\n    \"\"\"Steady Stokes drag on one analytic body in a periodic box, iterated to a steady mean.\n\n    The time step only sets how fast the transient is walked off -- the implicit viscous solve is\n    unconditionally stable and the fixed point is dt-independent. That is checked below rather\n    than asserted.\n    \"\"\"\n    b = geom.SceneBuilder()\n    root = build(b)\n    ni, nr, _, _ = b.encode()\n    inst_ints = np.zeros((1, KI_I), dtype=np.int32); inst_ints[0] = (root, -1)\n    inst_reals = np.zeros((1, KI_R))\n    inst_reals[0, 0:3] = (0.5 * n,) * 3\n    inst_reals[0, 6] = 1.0; inst_reals[0, 7] = 1.0\n\n    s = sdflow.Solver(n, n, n)\n    s.set_rho(RHO); s.set_mu(MU); s.set_dt(dt); s.set_advection(False)\n    s.set_velocity_solver_params(100); s.set_pressure_solver_params(25)\n    s.set_pressure_multigrid(True, levels=4)\n    s.set_scene(np.asarray(ni, dtype=np.int32), np.asarray(nr, dtype=float),\n                inst_ints.ravel(), inst_reals.ravel(), periodic=True)\n    s.set_solid_from_scene(True)\n    s.set_body_force(FBODY, 0.0, 0.0)\n    nc = s.fluid_momentum_cells()[0]\n    prev, it, t0 = 0.0, 0, time.time()\n    while it < maxit:\n        s.step(); it += 1\n        um = float(np.asarray(s.get_u()).sum()) / nc\n        if it > 5 and abs(um - prev) < tol * abs(um):\n            break\n        prev = um\n    force = float(np.asarray(s.hydro_force_torque_reaction())[0][0][0])\n    lam = force / (6 * np.pi * MU * RV * um)\n    VSOL[(label, n)] = n ** 3 - nc\n    print(\"   %-30s N=%3d  lambda=%8.5f   V_solid(discrete)=%7d  (analytic %7.0f)  %4d steps %3.0fs\"\n          % (label, n, lam, n ** 3 - nc, VOL, it, time.time() - t0))\n    return lam\n\ndef hasimoto(c):\n    \"\"\"Simple-cubic array drag ratio: Hasimoto (1959) extended by Sangani & Acrivos (1982).\n\n    The two extra terms matter: at c = 0.125 the four-term series gives 4.533 while this one\n    gives 4.289, against Zick & Homsy's tabulated 4.292.\n    \"\"\"\n    return 1.0 / (1 - 1.7601 * c ** (1 / 3) + c - 1.5593 * c ** 2\n                  + 3.9799 * c ** (8 / 3) - 3.0734 * c ** (10 / 3))\n```\n:::\n\n\n## The shapes — all at the same volume\n\n::: {#shapes .cell execution_count=4}\n``` {.python .cell-code}\nAR = 2.0                                   # spheroid aspect ratio\nB = RV / AR ** (1 / 3.0); A = AR * B       # prolate semi-axes, equal volume\nHC = (VOL / 8.0) ** (1 / 3.0)              # cube half-side, equal volume\n# spherocylinder (capsule): radius RC, cylinder half-length LC, volume = pi RC^2 (2 LC) + 4/3 pi RC^3\nRC = 0.75 * RV\nLC = (VOL - 4 / 3 * np.pi * RC ** 3) / (2 * np.pi * RC ** 2)\n\ndef quat_align(a, b):\n    \"\"\"Unit quaternion (x,y,z,w) whose rotation carries the BODY direction a onto the WORLD b.\"\"\"\n    a = np.asarray(a, float); a /= np.linalg.norm(a)\n    b = np.asarray(b, float); b /= np.linalg.norm(b)\n    axis = np.cross(a, b); c = float(np.dot(a, b))\n    if np.linalg.norm(axis) < 1e-12:\n        return [0.0, 0.0, 0.0, 1.0] if c > 0 else [1.0, 0.0, 0.0, 0.0]\n    axis /= np.linalg.norm(axis); ang = np.arccos(np.clip(c, -1, 1)); h = np.sin(ang / 2)\n    return [float(axis[0] * h), float(axis[1] * h), float(axis[2] * h), float(np.cos(ang / 2))]\n\n# a cube BODY DIAGONAL onto the flow direction (+x)\nDIAG_Q = quat_align([1.0, 1.0, 1.0], [1.0, 0.0, 0.0])\n\n# Rounded cubes as SUPERQUADRICS. core's leaf is [rx, ry, rz, n] with the implicit\n#   |x/rx|^n + |y/ry|^n + |z/rz|^n = 1,\n# so n IS the exponent: n = 2 is an ellipsoid and large n approaches a box. The literature\n# reference below uses the reciprocal \"blockiness\" convention e = 2/n (e = 1 sphere, e -> 0\n# box), so the two are related by n = 2/e -- a trap worth stating, since both conventions are\n# written \"e\". The superellipsoid volume is\n#   V = 8 rx ry rz Gamma(1+1/n)^3 / Gamma(1+3/n),\n# which fixes the semi-axis at a given equal-volume radius R_v.\ndef sq_radius(n, r_v):\n    return r_v * ((np.pi / 6) * gamma_fn(1 + 3 / n) / gamma_fn(1 + 1 / n) ** 3) ** (1 / 3.0)\n\nBLOCKINESS = (0.2, 0.4)                      # the reference's e\nSQ = {e: (2.0 / e, sq_radius(2.0 / e, RV)) for e in BLOCKINESS}\nfor e, (n_, r_) in SQ.items():\n    print(\"superquadric  reference e=%.1f  ->  core exponent n=%.2f   equal-volume semi-axis \"\n          \"R=%.4f   (R/d_v = %.5f)\" % (e, n_, r_, r_ / (2 * RV)))\nprint(\"   convention check: n=2 must give exactly the sphere radius -> %.5f (R_v = %.1f)\"\n      % (sq_radius(2.0, RV), RV))\n\nSHAPES = {\n    \"sphere (exact leaf)\":        lambda b: b.add_leaf(\"sphere\", [RV]),\n    \"sphere via ellipsoid leaf\":  lambda b: b.add_leaf(\"ellipsoid\", [RV, RV, RV]),\n    \"prolate AR=2, axial\":        lambda b: b.add_leaf(\"ellipsoid\", [A, B, B]),\n    \"prolate AR=2, broadside\":    lambda b: b.add_leaf(\"ellipsoid\", [B, A, B]),\n    \"cube, face-on\":              lambda b: b.add_leaf(\"box\", [HC, HC, HC]),\n    # Same cube turned so a body DIAGONAL points along the flow. A cube has cubic symmetry, so\n    # its translational resistance tensor must be isotropic and the two must agree -- a symmetry\n    # check the solver has no way to satisfy by accident.\n    \"cube, diagonal-on\":          lambda b: b.add_leaf(\n        \"box\", [HC, HC, HC], rotation=DIAG_Q),\n    \"capsule, axial\":             lambda b: b.add_leaf(\n        \"capsule\", [RC, LC], rotation=[0.0, 0.0, float(np.sin(np.pi / 4)),\n                                       float(np.cos(np.pi / 4))]),\n    \"rounded cube e=0.2\":         lambda b: b.add_leaf(\n        \"superquadric\", [SQ[0.2][1]] * 3 + [SQ[0.2][0]]),\n    \"rounded cube e=0.4\":         lambda b: b.add_leaf(\n        \"superquadric\", [SQ[0.4][1]] * 3 + [SQ[0.4][0]]),\n}\nprint(\"R_v = %.2f cells   cube side %.3f   spheroid a=%.3f b=%.3f   capsule r=%.3f L=%.3f\"\n      % (RV, 2 * HC, A, B, RC, 2 * LC))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsuperquadric  reference e=0.2  ->  core exponent n=10.00   equal-volume semi-axis R=6.5377   (R/d_v = 0.40860)\nsuperquadric  reference e=0.4  ->  core exponent n=5.00   equal-volume semi-axis R=6.7640   (R/d_v = 0.42275)\n   convention check: n=2 must give exactly the sphere radius -> 8.00000 (R_v = 8.0)\nR_v = 8.00 cells   cube side 12.896   spheroid a=12.699 b=6.350   capsule r=6.000 L=10.963\n```\n:::\n:::\n\n\n`capsule` is a **y**-axis primitive, so the axial case rotates it onto **x**, the flow direction.\n\n::: {#measure .cell execution_count=5}\n``` {.python .cell-code}\nN_MAIN = 96                      # the measurement box: phi = 0.0024, dilute enough that\nprint(\"N=%d, phi=%.5f\" % (N_MAIN, VOL / N_MAIN ** 3))   # the ratio's box terms are small\nlam = {k: run(v, N_MAIN, k) for k, v in SHAPES.items()}\nphi = VOL / N_MAIN ** 3\n# the fixed point must not depend on how we walked to it\nlam_slow = run(SHAPES[\"sphere (exact leaf)\"], N_MAIN, \"sphere @ dt=200\", dt=200.0, maxit=8000)\nprint(\"\\n   dt-independence of the fixed point: lambda(dt=1000) = %.6f   lambda(dt=200) = %.6f\"\n      \"   -> %.2e relative\" % (lam[\"sphere (exact leaf)\"], lam_slow,\n                               abs(lam_slow / lam[\"sphere (exact leaf)\"] - 1)))\nprint(\"\\n   sphere: lambda=%.5f   Hasimoto/Sangani-Acrivos SC = %.5f   (%+.2f%%)\"\n      % (lam[\"sphere (exact leaf)\"], hasimoto(phi),\n         100 * (lam[\"sphere (exact leaf)\"] / hasimoto(phi) - 1)))\nprint(\"   sphere authored as an ELLIPSOID leaf (a BOUND, not a distance): %+.3f%% from the \"\n      \"exact-distance sphere leaf\" %\n      (100 * (lam[\"sphere via ellipsoid leaf\"] / lam[\"sphere (exact leaf)\"] - 1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nN=96, phi=0.00242\n   sphere (exact leaf)            N= 96  lambda= 1.29739   V_solid(discrete)=   2104  (analytic    2145)  1786 steps 143s\n   sphere via ellipsoid leaf      N= 96  lambda= 1.29739   V_solid(discrete)=   2104  (analytic    2145)  1786 steps 110s\n   prolate AR=2, axial            N= 96  lambda= 1.22030   V_solid(discrete)=   2154  (analytic    2145)  1886 steps 117s\n   prolate AR=2, broadside        N= 96  lambda= 1.46106   V_solid(discrete)=   2124  (analytic    2145)  1606 steps  99s\n   cube, face-on                  N= 96  lambda= 1.41313   V_solid(discrete)=   2028  (analytic    2145)  1656 steps 111s\n   cube, diagonal-on              N= 96  lambda= 1.41120   V_solid(discrete)=   2122  (analytic    2145)  1658 steps 166s\n   capsule, axial                 N= 96  lambda= 1.23793   V_solid(discrete)=   2098  (analytic    2145)  1863 steps 208s\n   rounded cube e=0.2             N= 96  lambda= 1.40589   V_solid(discrete)=   2262  (analytic    2145)  1664 steps 156s\n   rounded cube e=0.4             N= 96  lambda= 1.35114   V_solid(discrete)=   2126  (analytic    2145)  1709 steps 151s\n   sphere @ dt=200                N= 96  lambda= 1.29787   V_solid(discrete)=   2104  (analytic    2145)  2969 steps 216s\n\n   dt-independence of the fixed point: lambda(dt=1000) = 1.297392   lambda(dt=200) = 1.297867   -> 3.66e-04 relative\n\n   sphere: lambda=1.29739   Hasimoto/Sangani-Acrivos SC = 1.30552   (-0.62%)\n   sphere authored as an ELLIPSOID leaf (a BOUND, not a distance): +0.000% from the exact-distance sphere leaf\n```\n:::\n:::\n\n\n## The exact reference: a prolate spheroid\n\nFor a prolate spheroid of semi-axes $a > b = c$ with eccentricity $e = \\sqrt{1 - b^2/a^2}$ and\n$L = \\ln\\frac{1+e}{1-e}$, the Stokes drag is (Oberbeck 1876; Happel & Brenner, *Low Reynolds Number\nHydrodynamics*, §4-26)\n\n$$\nF_\\parallel = \\frac{16\\pi\\mu a U e^3}{(1+e^2)L - 2e},\n\\qquad\nF_\\perp = \\frac{32\\pi\\mu a U e^3}{(3e^2-1)L + 2e},\n$$ {#eq-oberbeck}\n\nfor motion along and across the symmetry axis. Both reduce to $6\\pi\\mu a U$ as $e\\to 0$, which is\nworth checking in code rather than trusting in print.\n\n::: {#oberbeck .cell execution_count=6}\n``` {.python .cell-code}\ndef oberbeck(a, b):\n    e = np.sqrt(1 - (b / a) ** 2); L = np.log((1 + e) / (1 - e))\n    par = 16 * np.pi * MU * a * e ** 3 / ((1 + e ** 2) * L - 2 * e)\n    perp = 32 * np.pi * MU * a * e ** 3 / ((3 * e ** 2 - 1) * L + 2 * e)\n    return par, perp, e\n\n# sanity: the sphere limit\np_, q_, _ = oberbeck(1.0, 1.0 - 1e-6)\nprint(\"sphere limit of @eq-oberbeck / 6 pi mu a :  axial %.8f   transverse %.8f\"\n      % (p_ / (6 * np.pi * MU), q_ / (6 * np.pi * MU)))\n\nF_par, F_perp, ecc = oberbeck(A, B)\nK_par_exact = F_par / (6 * np.pi * MU * RV)\nK_perp_exact = F_perp / (6 * np.pi * MU * RV)\nK_par = lam[\"prolate AR=2, axial\"] / lam[\"sphere (exact leaf)\"]\nK_perp = lam[\"prolate AR=2, broadside\"] / lam[\"sphere (exact leaf)\"]\nprint(\"\\nprolate AR=2 (e=%.5f), drag relative to the equal-volume sphere:\" % ecc)\nprint(\"   axial      measured %.5f   exact %.5f   %+.2f%%\" %\n      (K_par, K_par_exact, 100 * (K_par / K_par_exact - 1)))\nprint(\"   broadside  measured %.5f   exact %.5f   %+.2f%%\" %\n      (K_perp, K_perp_exact, 100 * (K_perp / K_perp_exact - 1)))\nprint(\"   anisotropy F_perp/F_par: measured %.5f   exact %.5f   %+.2f%%\" %\n      (K_perp / K_par, K_perp_exact / K_par_exact,\n       100 * ((K_perp / K_par) / (K_perp_exact / K_par_exact) - 1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsphere limit of @eq-oberbeck / 6 pi mu a :  axial 0.99999921   transverse 0.99999940\n\nprolate AR=2 (e=0.86603), drag relative to the equal-volume sphere:\n   axial      measured 0.94058   exact 0.95557   -1.57%\n   broadside  measured 1.12615   exact 1.09443   +2.90%\n   anisotropy F_perp/F_par: measured 1.19730   exact 1.14532   +4.54%\n```\n:::\n:::\n\n\n## Does the box really cancel?\n\nThe ratio method assumes the blockage correction is the same for both shapes at equal volume. It is\nnot exactly — a long body blocks differently from a compact one. Repeat in a larger box at the same\n$R_v$ in cells (so the grid resolution of each shape is unchanged) and watch the ratios move.\n\n::: {#boxladder .cell execution_count=7}\n``` {.python .cell-code}\nN_BIG = 64                       # a 3.4x DENSER box: the shift is the ratio method's error bar\nprint(\"N=%d, phi=%.5f\" % (N_BIG, VOL / N_BIG ** 3))\nlam_big = {k: run(v, N_BIG, k) for k, v in SHAPES.items()}\nprint(\"\\n   %-28s  K(N=%d)   K(N=%d)     shift\" % (\"shape\", N_MAIN, N_BIG))\nrows = []\nfor k in SHAPES:\n    if k.startswith(\"sphere (\"):\n        continue\n    k64 = lam[k] / lam[\"sphere (exact leaf)\"]\n    k96 = lam_big[k] / lam_big[\"sphere (exact leaf)\"]\n    rows.append((k, k64, k96))\n    print(\"   %-28s  %7.5f   %7.5f   %+7.3f%%\" % (k, k64, k96, 100 * (k96 / k64 - 1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nN=64, phi=0.00818\n   sphere (exact leaf)            N= 64  lambda= 1.50312   V_solid(discrete)=   2104  (analytic    2145)   513 steps  14s\n   sphere via ellipsoid leaf      N= 64  lambda= 1.50312   V_solid(discrete)=   2104  (analytic    2145)   513 steps  14s\n   prolate AR=2, axial            N= 64  lambda= 1.38811   V_solid(discrete)=   2154  (analytic    2145)   556 steps  15s\n   prolate AR=2, broadside        N= 64  lambda= 1.73054   V_solid(discrete)=   2124  (analytic    2145)   451 steps  13s\n   cube, face-on                  N= 64  lambda= 1.65638   V_solid(discrete)=   2028  (analytic    2145)   474 steps  14s\n   cube, diagonal-on              N= 64  lambda= 1.65964   V_solid(discrete)=   2122  (analytic    2145)   475 steps  14s\n   capsule, axial                 N= 64  lambda= 1.41096   V_solid(discrete)=   2098  (analytic    2145)   549 steps  15s\n   rounded cube e=0.2             N= 64  lambda= 1.64556   V_solid(discrete)=   2262  (analytic    2145)   480 steps  14s\n   rounded cube e=0.4             N= 64  lambda= 1.57305   V_solid(discrete)=   2126  (analytic    2145)   470 steps  13s\n\n   shape                         K(N=96)   K(N=64)     shift\n   sphere via ellipsoid leaf     1.00000   1.00000    -0.000%\n   prolate AR=2, axial           0.94058   0.92349    -1.817%\n   prolate AR=2, broadside       1.12615   1.15130    +2.233%\n   cube, face-on                 1.08920   1.10196    +1.171%\n   cube, diagonal-on             1.08772   1.10413    +1.509%\n   capsule, axial                0.95417   0.93869    -1.622%\n   rounded cube e=0.2            1.08363   1.09476    +1.027%\n   rounded cube e=0.4            1.04143   1.04653    +0.489%\n```\n:::\n:::\n\n\n::: {#cell-fig-ratios .cell execution_count=8}\n``` {.python .cell-code code-fold=\"true\"}\nlabels = [r[0] for r in rows]\nk64 = np.array([r[1] for r in rows]); k96 = np.array([r[2] for r in rows])\nx = np.arange(len(labels))\nfig, ax = plt.subplots(figsize=(6.6, 3.2))\nax.bar(x - 0.18, k64, 0.34, color=\"#4c72b0\",\n       label=\"$N=%d$ ($\\\\phi=%.4f$)\" % (N_MAIN, VOL / N_MAIN ** 3))\nax.bar(x + 0.18, k96, 0.34, color=\"#8fa9c8\",\n       label=\"$N=%d$ ($\\\\phi=%.4f$)\" % (N_BIG, VOL / N_BIG ** 3))\nfor i, lab in enumerate(labels):\n    if \"axial\" in lab and \"prolate\" in lab:\n        ax.plot(x[i], K_par_exact, \"k*\", ms=11, zorder=5)\n    if \"broadside\" in lab:\n        ax.plot(x[i], K_perp_exact, \"k*\", ms=11, zorder=5, label=\"exact (Oberbeck)\")\nax.axhline(1.0, color=\"0.6\", lw=0.8, ls=\":\")\nax.set_xticks(x); ax.set_xticklabels([l.replace(\", \", \",\\n\") for l in labels], fontsize=7.5)\nax.set_ylabel(\"$K = F_{\\\\rm shape}/F_{\\\\rm sphere}$ at equal volume\")\nax.legend(fontsize=8, frameon=False); ax.grid(axis=\"y\", alpha=0.3)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Equal-volume drag ratios in two box sizes. Filled markers are the exact Oberbeck values for the spheroid; the box shift is the honest uncertainty on every bar.](index_files/figure-html/fig-ratios-output-1.png){#fig-ratios}\n:::\n:::\n\n\n## The cube, and what the correlations say about it\n\nA cube has cubic symmetry, so its translational resistance tensor — a second-rank tensor invariant\nunder that symmetry group — must be **isotropic**. Its Stokes drag is therefore independent of\norientation, which is why we measure it twice, face-on and with a body diagonal along the flow.\nAny difference between those two is our discretisation error, measured directly.\n\nSphericity $\\psi = A_{\\text{sphere of equal volume}} / A_{\\text{particle}}$ compresses a shape to one\nnumber. Leith [-@leith1987] instead keeps two length scales — the projected-area-equivalent diameter\n$d_n$ and the surface-equivalent diameter $d_s$ — and predicts, in the Stokes regime,\n\n$$\nK_{\\text{Leith}} = \\tfrac{1}{3}\\frac{d_n}{d_v} + \\tfrac{2}{3}\\frac{d_s}{d_v} .\n$$ {#eq-leith}\n\nBecause $d_n$ depends on orientation, @eq-leith does too: for a cube it runs **1.0457** face-on,\n**1.1031** edge-on and **1.1416** corner-on — a 9% spread across orientations where the true spread\nis exactly zero. (By Cauchy's theorem the orientation-averaged projected diameter of a convex body\nequals its surface-equivalent diameter, so Leith's random-orientation value is exactly\n$\\psi^{-1/2} = 1.1139$.) Any $d_n$-based correlation is therefore wrong for a cube in all but one\norientation. The established orientation-averaged value is $\\chi = 1.08$ [@fuchs1964mechanics;\n@pettyjohn1948] — a **two-digit** tabulation from free-settling experiments, so ±0.01 at best, and\nnot something to validate against to three digits.\n\nOne more consequence of the symmetry: a cube also has a centre of symmetry, so its\ntranslation–rotation coupling tensor vanishes and it settles **without rotating**. And all of this\nis a Stokes-flow statement: orientation dependence returns at finite Reynolds number.\n\n::: {.callout-warning}\n## Haider & Levenspiel is not a Stokes-regime reference\nThe most-cited non-spherical drag correlation [@haider1989levenspiel] writes\n$C_D = (24/\\mathrm{Re})[1 + A\\,\\mathrm{Re}^{B}] + C/(1 + D/\\mathrm{Re})$. Since $B(\\psi) = 0.0964 +\n0.5565\\psi > 0$ for every sphericity, $A\\,\\mathrm{Re}^{B} \\to 0$ and $C\\mathrm{Re}/D \\to 0$ as\n$\\mathrm{Re}\\to 0$: the correlation degenerates to $C_D = 24/\\mathrm{Re}$, the *sphere*, with no\nshape dependence at all. It cannot be compared against here, and that is a property of the\ncorrelation rather than a limitation of the measurement.\n:::\n\n::: {#correlations .cell execution_count=9}\n``` {.python .cell-code}\ndef geom_diameters(area_surface, area_projected):\n    d_v = 2 * RV\n    return d_v, np.sqrt(area_surface / np.pi), 2 * np.sqrt(area_projected / np.pi)\n\nside = 2 * HC\ncube_S, cube_A = 6 * side ** 2, side ** 2                       # face-on projection\nd_v, d_s, d_n = geom_diameters(cube_S, cube_A)\nK_leith_face = (1 / 3) * (d_n / d_v) + (2 / 3) * (d_s / d_v)\nK_leith_rand = d_s / d_v                                        # Cauchy: <d_n> = d_s\npsi_cube = (np.pi ** (1 / 3) * (6 * VOL) ** (2 / 3)) / cube_S\nK_cube_face = lam[\"cube, face-on\"] / lam[\"sphere (exact leaf)\"]\nK_cube_diag = lam[\"cube, diagonal-on\"] / lam[\"sphere (exact leaf)\"]\nprint(\"cube: side %.4f   S=%.2f   A_proj(face)=%.2f   d_s/d_v=%.4f  d_n/d_v=%.4f   sphericity %.4f\"\n      % (side, cube_S, cube_A, d_s / d_v, d_n / d_v, psi_cube))\nprint(\"   ISOTROPY CHECK (cubic symmetry says these are the same number):\")\nprint(\"      face-on      K = %.5f\" % K_cube_face)\nprint(\"      diagonal-on  K = %.5f      difference %+.3f%%\"\n      % (K_cube_diag, 100 * (K_cube_diag / K_cube_face - 1)))\nprint(\"   references:  orientation-averaged chi = 1.08 (Fuchs 1964 / Pettyjohn & Christiansen 1948,\"\n      \" 2 digits)\")\nprint(\"                Leith (1987) face-on %.4f    random-orientation %.4f\"\n      % (K_leith_face, K_leith_rand))\nprint(\"   measured (mean of the two orientations) = %.5f   -> %+.2f%% of the 1.08 datum\"\n      % (0.5 * (K_cube_face + K_cube_diag), 100 * (0.5 * (K_cube_face + K_cube_diag) / 1.08 - 1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncube: side 12.8959   S=997.83   A_proj(face)=166.31   d_s/d_v=1.1139  d_n/d_v=0.9095   sphericity 0.8060\n   ISOTROPY CHECK (cubic symmetry says these are the same number):\n      face-on      K = 1.08920\n      diagonal-on  K = 1.08772      difference -0.136%\n   references:  orientation-averaged chi = 1.08 (Fuchs 1964 / Pettyjohn & Christiansen 1948, 2 digits)\n                Leith (1987) face-on 1.0457    random-orientation 1.1139\n   measured (mean of the two orientations) = 1.08846   -> +0.78% of the 1.08 datum\n```\n:::\n:::\n\n\n## Rounded cubes against a boundary-element model\n\nŠtrakl et al. [-@strakl2022superquadric] published resistance tensors for superellipsoids in Stokes\nflow together with their code. Their shape family is the same as core's, but written in the\nreciprocal convention: their **blockiness** $e$ (with $e=1$ a sphere and $e\\to 0$ a box) is\n$n = 2/e$ in core's exponent. Both are called \"$e$\" in their respective docs, which is exactly the\nkind of thing that silently produces a wrong comparison, so the code above states the mapping and\nchecks it against the $n=2$ sphere limit. Their model's own error floor is about 0.05% (a sphere\ncontrol returns $\\chi = 1.0005$), and $e = 0.2$ ($n = 10$) sits at the edge of their fitted range,\nso it is an extrapolation toward the sharp cube rather than a converged value.\n\n::: {#superquadric .cell execution_count=10}\n``` {.python .cell-code}\nSTRAKL = {0.2: 1.0563, 0.4: 1.0255}      # chi = F_shape / F_equal-volume-sphere\nprint(\"   e     measured K (N=%d)    Strakl et al. (2022)    difference\" % N_MAIN)\nfor e in (0.2, 0.4):\n    k = lam[\"rounded cube e=%.1f\" % e] / lam[\"sphere (exact leaf)\"]\n    print(\"   %.1f      %.5f              %.4f                 %+.2f%%\"\n          % (e, k, STRAKL[e], 100 * (k / STRAKL[e] - 1)))\nprint(\"   for scale: the sharp cube is %.5f (measured) against 1.08 (tabulated)\"\n      % (0.5 * (K_cube_face + K_cube_diag)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   e     measured K (N=96)    Strakl et al. (2022)    difference\n   0.2      1.08363              1.0563                 +2.59%\n   0.4      1.04143              1.0255                 +1.55%\n   for scale: the sharp cube is 1.08846 (measured) against 1.08 (tabulated)\n```\n:::\n:::\n\n\n## The error budget\n\nTwo systematics survive the ratio, and both are measurable rather than estimated.\n\n**The box does not cancel exactly.** The ratio method assumes an equal-volume shape and sphere\nblock a periodic box equally. They do not: an elongated body blocks differently from a compact one,\nand the two boxes above disagree by 0.5–2.2% on exactly the shapes that are least sphere-like. That\nshift *is* the error bar.\n\n**The discrete body is not the analytic one — but by less than the obvious estimate.** The solver's\nown count of masked staggered points is a *point sample* of the shape, and a body with flat faces\naligned to the grid samples badly at $R_v = 8$ cells. The naive correction is that a volume mismatch\n$\\eta$ biases an equal-volume drag ratio by about $\\eta/3$. Both columns are below; read them\ntogether, because the naive correction turns out to be wrong.\n\n::: {#budget .cell execution_count=11}\n``` {.python .cell-code}\nprint(\"   shape                          V_disc/V_an   implied drag bias   box shift (96->64)\")\nfor k, k96, k64 in rows:\n    eta = VSOL[(k, N_MAIN)] / VOL\n    ref = VSOL[(\"sphere (exact leaf)\", N_MAIN)] / VOL\n    print(\"   %-28s   %+6.2f%%        %+6.2f%%             %+6.2f%%\"\n          % (k, 100 * (eta - 1), 100 * ((eta / ref) ** (1 / 3.0) - 1), 100 * (k64 / k96 - 1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   shape                          V_disc/V_an   implied drag bias   box shift (96->64)\n   sphere via ellipsoid leaf       -1.90%         +0.00%              -0.00%\n   prolate AR=2, axial             +0.44%         +0.79%              -1.82%\n   prolate AR=2, broadside         -0.96%         +0.32%              +2.23%\n   cube, face-on                   -5.44%         -1.22%              +1.17%\n   cube, diagonal-on               -1.06%         +0.28%              +1.51%\n   capsule, axial                  -2.18%         -0.10%              -1.62%\n   rounded cube e=0.2              +5.47%         +2.44%              +1.03%\n   rounded cube e=0.4              -0.87%         +0.35%              +0.49%\n```\n:::\n:::\n\n\n**The point count is not the effective volume.** The same cube, face-on and corner-on, samples\n**4.4 percentage points** differently (−5.44% against −1.06%) — and its drag changes by **0.14%**.\nThe cut-cell geometry is built from surface crossings and apertures, not from counting masked\npoints, and is correspondingly insensitive to that count; the $\\eta/3$ estimate is an upper bound\nthat the solver comfortably beats. The one row where the two do track is the sharpest shape, the\n$e = 0.2$ rounded cube: +5.5% in count and +2.6% above Štrakl's value. That is the least trustworthy\nnumber on the page, and it is flagged rather than explained away.\n\n**So the residuals are the box.** The spheroid's exact gate misses by −1.6% and +2.9%, against a box\nshift of −1.8% and +2.2% *in the same directions* — an elongated body simply does not block a\nperiodic cell the way an equal-volume sphere does, and the ratio does not cancel it. The method is\nsound and the numbers are box-limited rather than model-limited, which says what to do about it (a\nlarger box, or a genuinely unbounded formulation) instead of declaring 3% a success.\n\n## Results\n\n| claim | measured | reference |\n|---|---|---|\n| sphere in the box (the calibration) | 1\\.29739 | Hasimoto/Sangani–Acrivos 1\\.30552 (**\\-0\\.62%**) |\n| bound-leaf ellipsoid vs exact-distance sphere leaf, same shape | **\\+0\\.000%** | 0 |\n| **prolate AR=2, axial** | 0\\.94058 | exact 0\\.95557 (**\\-1\\.57%**) |\n| **prolate AR=2, broadside** | 1\\.12615 | exact 1\\.09443 (**\\+2\\.90%**) |\n| spheroid anisotropy $F_\\perp/F_\\parallel$ | 1\\.19730 | exact 1\\.14532 |\n| **cube** (face-on / diagonal-on) | 1\\.08920 / 1\\.08772 (spread **0\\.136%**, cubic symmetry says 0) | orientation-averaged $\\chi = 1.08$ (**\\+0\\.78%**); Leith face-on 1\\.0457 |\n| rounded cube $e=0.2$ | 1\\.08363 | Štrakl et al. 1\\.0563 (**\\+2\\.59%**) |\n| rounded cube $e=0.4$ | 1\\.04143 | Štrakl et al. 1\\.0255 (**\\+1\\.55%**) |\n| capsule, axial | 0\\.95417 | — (prediction) |\n\nThe headline: **a cube's Stokes drag comes out orientation-independent to\n0\\.14%**, which cubic symmetry demands and no\ncorrelation built on projected area can reproduce — Leith's own prediction for the same cube swings\n9% between face-on and corner-on — and its value,\n1\\.08846 against the tabulated $\\chi = 1.08 \\pm 0.01$,\nsits inside the reference's own uncertainty. The method that produced it was validated first against\nthe exact Oberbeck spheroid, where it lands within the box error bar, and the sphere calibration\nreproduces the Hasimoto–Sangani–Acrivos periodic series to\n0\\.62% with a fixed\npoint independent of the time step to\n3\\.7e\\-04.\n\nOne incidental result worth keeping: a sphere authored through the **bound-only** `ellipsoid` leaf\nand through the distance-exact `sphere` leaf give drag coefficients identical to six digits. The\ncut-cell geometry is derived from the zero level set and the crossings along grid lines, both of\nwhich a bound gets exactly right; the distance away from the surface, which is what the bound\nsacrifices, never enters. That is why the superquadric and ellipsoid measurements above are\ntrustworthy at all.\n\n## Adapt this yourself\n\n- **Any shape.** Anything you can build in `peclet.core.geom` — a CSG difference, an instanced\n  cluster — drops straight into `SHAPES`. Keep the volume fixed (`body_properties` will tell you\n  what it is) and the ratio stays meaningful.\n- **Orientation sweeps.** Rotate the instance quaternion rather than re-authoring the leaf, and the\n  drag becomes a function of angle: the anisotropy the correlations cannot express.\n- **Finite Reynolds number.** `set_advection(True)` — the reaction budget carries explicit\n  advection, so the same force call remains valid, and the correlations start earning their keep.\n- **Feed it to DEM.** The same tree is a `peclet.dem` particle via `scene_particle.build`; the\n  measured $K$ is the drag closure a point-particle CFD-DEM run would need.\n\n## Reproduce this\n\n```bash\nPECLET_LOCAL_BUILD=/path/to/suite/flow/build_l3_cuda \\\n  quarto render examples/nonsphere-drag/index.qmd --execute\n```\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}