{
  "hash": "2a503a69447e13af434bf2db8775a40e",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"A droplet on a wall: static contact angles on immersed solids\"\nsubtitle: \"Set the angle, get the angle — to about a degree up to 90°, and to 2 % of the cap radius on a curved solid. Plus the one wall placement that silently freezes the contact line.\"\nauthor: \"Peclet\"\ndate: \"2026-09-02\"\ncategories: [flow, vof, two-phase, wetting, IBM, verification]\njupyter: python3\n---\n\n\n\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/computational-chemical-engineering/peclet-examples/blob/main/examples/droplet-wetting/index.ipynb){target=\"_blank\"}\n&nbsp;Wants a GPU build: this page runs eleven $64^3$-class two-phase simulations.\n\n## What you'll learn\n\nA wetting condition is the one piece of two-phase physics that lives *inside* the\nsolid. Everything else — the interface, the curvature, the surface-tension force —\nis a statement about the fluid; a contact angle is a statement about what the\nfluid's stencils should see where there is no fluid at all. Get it wrong and the\nsymptom is not a crash: it is a droplet that quietly settles at the wrong shape.\n\nThis page puts peclet's static contact angle on an SDF solid through the two\nchecks that have closed-form answers:\n\n1. **A drop on a flat wall.** Prescribe $\\theta$, run to rest, and read the\n   apparent angle back off the equilibrium spherical cap. Measured\n   **30.7° / 60.0° / 88.8° / 116.9°** for $\\theta_{\\text{set}} =$ 30 / 60 / 90 / 120\n   at 24 cells per drop diameter — within **1.2°** up to 90°, and −3.1° at 120°,\n   where the contact line itself is resolved by fewer than ten cells.\n2. **A drop on a solid sphere.** The equilibrium is a spherical cap whose sphere\n   meets the solid sphere at $\\theta$ — a one-dimensional root solve from the\n   conserved volume. The measured cap radius lands within **2.3 %** at\n   $\\theta = 60°/90°/120°$, and the *curved* wall costs nothing over the flat one.\n\nAlong the way: liquid volume conserved to $10^{-14}$, near-wall spurious currents\nabout an order of magnitude above the free-droplet floor, and — the finding worth\nthe price of the page — **where you place a flat SDF wall inside its cell decides\nwhether the contact line can move at all.** Put it at a half-integer coordinate\nand the wall cell's tangential faces close, the contact line pins, and the\nunrelieved Young force shows up as a velocity of order 1.\n\n**The conclusion to carry away:** the angle is imposed entirely through the\n*colour field inside the solid* — no force is added at the wall — and it is an\nexact fixed point of the discrete scheme. What limits the accuracy is how many\ncells the contact line has, not the wetting model.\n\n## The problem\n\nA sessile drop at rest is a two-line problem. Surface tension makes the free\nsurface a constant-curvature cap; Young's condition makes it meet the solid at\nthe equilibrium angle set by the three interfacial tensions,\n\n$$\n\\cos\\theta = \\frac{\\sigma_{sg} - \\sigma_{sl}}{\\sigma_{lg}} .\n$$ {#eq-young}\n\nWith no gravity the equilibrium of a drop of volume $V$ on a flat wall is\ntherefore a **spherical cap**: contact radius $a$, apex height $h$, with\n\n$$\nV = \\frac{\\pi h}{6}\\left(3a^2 + h^2\\right), \\qquad\n\\tan\\frac{\\theta}{2} = \\frac{h}{a} .\n$$ {#eq-cap}\n\nTwo measurements ($V$ and $h$) give the third quantity and the angle, and this is\nhow the angle is read back below. It matters *which* two: $V$ is conserved to\nround-off by the geometric transport and $h$ is a column sum of the colour field,\nso @eq-cap is well conditioned on a flat wall — while reading the contact radius\noff the first open fluid plane is biased, because that plane's colour is an\naverage over $z \\in [z_w, z_w + 1]$ and not the section *at* the wall. Both are\nprinted below so you can see the size of the bias.\n\n### How the angle enters the discretization\n\npeclet represents the solid by a signed distance field ($\\varphi > 0$ is fluid)\nand the liquid by a colour field $C$ — the liquid fraction of each cell's *fluid*\nvolume. The geometric Weymouth–Yue transport [@weymouth2010] moves $C$ through\ncut cells with openness-weighted fluxes, and a balanced-force continuum surface\nforce [@brackbill1992; @francois2006; @popinet2009] turns the curvature into\nmomentum. None of that machinery knows about wetting.\n\nThe wetting condition is imposed by **filling the colour field inside the solid**.\nWrite $\\mathbf{n}_w = \\nabla\\varphi/|\\nabla\\varphi|$ for the wall normal (solid →\nfluid) and $\\mathbf{m}$ for the PLIC interface normal (liquid → gas). Measuring\n$\\theta$ through the liquid, the contact-line condition is simply\n\n$$\n\\mathbf{m}\\cdot\\mathbf{n}_w = \\cos\\theta ,\n$$ {#eq-contact}\n\nso $\\theta = 0$ (complete wetting) puts the interface parallel to the wall with\nthe liquid film between it and the solid, and $\\theta = 180°$ empties the band.\nFor each band cell inside the solid the solver walks along $\\mathbf{n}_w$ to the\nfirst fluid cell, takes the **azimuth** of that cell's interface normal, builds\nthe target normal $\\mathbf{m}_\\theta = \\cos\\theta\\,\\mathbf{n}_w + \\sin\\theta\\,\n\\hat{\\mathbf{t}}$, and writes the volume fraction of that plane into the band\ncell. The height-function/MYC curvature cascade — unchanged — then reads a\nconsistent interface across the wall and returns the curvature of a surface\nmeeting the solid at $\\theta$; the balanced force does the rest.\n\nThis is the volume-fraction form of the Afkhami–Bussmann height-function\nboundary condition [@afkhami2008; @afkhami2009], and it is the same family as\nBasilisk's embedded-boundary contact angle [@tavares2024; @basiliskcontactembed].\nTwo design points are worth stating because they are what makes it work:\n\n- **The fill is exactly idempotent.** The plane is anchored by matching the\n  anchor cell's *own* liquid volume, not by a geometric pivot point. An interface\n  that already meets the wall at $\\theta$ is reproduced to $10^{-15}$, so\n  $\\theta$ is a genuine fixed point of the discrete scheme rather than an\n  attractor with an offset.\n- **No force is added at the wall.** The entire wetting model is @eq-contact\n  expressed as cell fractions. There is nothing to balance against the CSF, and\n  nothing that can put energy into the near-wall velocity by construction.\n\n::: {.callout-important}\n## A run whose pressure solve hit its iteration cap is not a result\nEvery run on this page records `last_pressure_iterations()` against its cap and\n`max_open_divergence()`, and reports both. A capped solve means the projection did\nnot converge, the velocity field is not discretely divergence-free, and the\ngeometric transport's conservation guarantee — which is *conditional* on that —\nno longer holds. Such runs are discarded, not quoted. (None of the runs below\ncapped: 9–12 iterations against a cap of 300. The numbers are printed.)\n:::\n\n::: {#bootstrap .cell execution_count=1}\n``` {.python .cell-code code-summary=\"Environment bootstrap (installs peclet from PyPI on Colab/Binder)\"}\n# Makes this notebook run out-of-the-box on Colab/Binder. A real user just needs the\n# published package; this installs it on first run. Authors can instead point at a\n# local source build of the suite with the PECLET_LOCAL_BUILD env var.\nimport importlib.util, os, subprocess, sys\n_local = os.environ.get(\"PECLET_LOCAL_BUILD\")\nif _local:\n    sys.path.insert(0, _local)                                  # local source build\nelif importlib.util.find_spec(\"peclet\") is None:\n    subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"-q\", \"peclet\"], check=True)\n```\n:::\n\n\n::: {#e1f23069 .cell execution_count=2}\n``` {.python .cell-code}\nimport math\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom peclet import flow\n\nplt.rcParams.update({\"figure.dpi\": 130, \"font.size\": 10, \"axes.grid\": True,\n                     \"grid.alpha\": 0.3, \"axes.axisbelow\": True,\n                     \"figure.facecolor\": \"white\", \"savefig.bbox\": \"tight\"})\nBLUE, RED, GREY, GREEN, ORANGE = \"#1f77b4\", \"#d62728\", \"0.80\", \"#2ca02c\", \"#ff7f0e\"\nDEG = math.pi / 180.0\nPRESS_CAP = 300\n```\n:::\n\n\n## The scene: a cap on a slab\n\nThe wall is an SDF **slab**, not a single ramp. The box is periodic, so a lone\nwall would put a spurious fluid/solid seam at the wrap plane three cells from the\nband; a slab bounded at both ends keeps the wrap deep inside the solid where the\ndistance field is continuous.\n\nThe initial condition is the *exact* spherical cap of the prescribed angle,\nsampled as volume fractions by $4^3$ subsampling of the **fluid** part of each\ncell — because $C$ is a fraction of the fluid volume, not of the cell. Starting\nat the prescribed angle makes this the **fixed-point** protocol: the question is\nwhether the discrete equilibrium *is* the angle you asked for. (Starting from a\nhemisphere instead — the attraction protocol — is what the wall-placement study\nat the end of the page does.)\n\n::: {#geometry .cell execution_count=3}\n``` {.python .cell-code}\ndef cap_sphere(volume, theta_deg):\n    \"\"\"Radius and centre offset of the sphere whose cap of contact angle theta,\n    resting on z = 0, has the given volume: V = pi Rc^3 (1-cos t)^2 (2+cos t)/3.\"\"\"\n    ct = math.cos(theta_deg * DEG)\n    Rc = (3.0 * volume / (math.pi * (1.0 - ct) ** 2 * (2.0 + ct))) ** (1.0 / 3.0)\n    return Rc, -Rc * ct\n\n\ndef cap_colour(nx, ny, nz, cx, cy, zw, R, theta_deg):\n    \"\"\"Liquid volume fractions of a spherical cap of contact angle theta on the wall\n    z = zw, with the volume of a hemisphere of radius R. 4^3 subsampling of the FLUID\n    part of each cell.\"\"\"\n    Rc, zc = cap_sphere(2.0 / 3.0 * math.pi * R ** 3, theta_deg)\n    sub = (np.arange(4) + 0.5) / 4.0\n    px = np.arange(nx)[:, None, None, None, None, None] + sub[None, None, None, :, None, None]\n    py = np.arange(ny)[None, :, None, None, None, None] + sub[None, None, None, None, :, None]\n    pz = np.arange(nz)[None, None, :, None, None, None] + sub[None, None, None, None, None, :]\n    inside = ((px - cx) ** 2 + (py - cy) ** 2 + (pz - zw - zc) ** 2) < Rc * Rc\n    fluid = np.broadcast_to(pz >= zw, inside.shape)\n    tot = fluid.sum(axis=(3, 4, 5))\n    return np.asfortranarray(np.where(tot > 0, (fluid & inside).sum(axis=(3, 4, 5))\n                                      / np.maximum(tot, 1), 0.0).astype(float))\n\n\ndef slab_sdf(nx, ny, nz, zw):\n    \"\"\"A solid slab occupying z < zw and z > nz - zw (positive = fluid).\"\"\"\n    z = (np.arange(nz) + 0.5)[None, None, :]\n    return np.asfortranarray(\n        np.broadcast_to(np.minimum(z - zw, (nz - zw) - z), (nx, ny, nz)).astype(float))\n```\n:::\n\n\n## Driving the solver\n\nSix calls. `set_solid(..., cutcell_pressure=True)` is **required** — the colour\ntransport weights every flux by the face openness, and the staircase pressure\noperator has none, so the solver raises if you ask for VoF through a staircase\nsolid. `set_contact_angle(theta)` is the whole wetting model.\n\nSurface tension is explicit, so the time step is capped by the Brackbill capillary\nlimit `capillary_dt()`; on top of that the geometric transport wants an\n*interface-local* Courant number below about 0.2, and in cut cells that limiter is\ntighter than the plain one by up to $1/\\varepsilon$. The driver below tracks both.\n\nWe use $\\mathrm{Oh} = \\mu/\\sqrt{\\rho\\sigma D} = 0.1$, which is the fastest\nrelaxation the capillary time step allows without ringing.\n\n::: {#driver .cell execution_count=4}\n``` {.python .cell-code}\ndef maxvel(s, zlo=None):\n    m = 0.0\n    for f in (s.get_u, s.get_v, s.get_w):\n        v = np.abs(f())\n        m = max(m, float(v.max()) if zlo is None else float(v[:, :, zlo:].max()))\n    return m\n\n\ndef relax(s, steps, cfl=0.15, probe=25):\n    \"\"\"Run to rest with dt under both the capillary and the interface-CFL limits.\"\"\"\n    dt_cap = 0.5 * s.capillary_dt()\n    dt = dt_cap\n    s.set_dt(dt)\n    iters, capped, div, trace = 0, 0, 0.0, []\n    for i in range(steps):\n        c = s.vof_max_courant()\n        if c > cfl:\n            dt = min(dt_cap, dt * cfl / c); s.set_dt(dt)\n        elif dt < dt_cap and c < 0.5 * cfl:\n            dt = min(dt_cap, 1.2 * dt); s.set_dt(dt)\n        s.step()\n        it = s.last_pressure_iterations()\n        iters = max(iters, it)\n        capped += it >= PRESS_CAP                 # rule: a capped solve invalidates the run\n        div = max(div, s.max_open_divergence())   # the conservation floor\n        if (i + 1) % probe == 0:\n            trace.append((i + 1, maxvel(s)))\n    return dict(dt=dt, iters=iters, capped=capped, div=div, trace=np.array(trace))\n\n\ndef drop_on_wall(theta, ratio=1.0, steps=500, R=12.0, nx=64, nz=40, zw=4.25,\n                 sigma=1.0, oh=0.1, theta_init=None):\n    \"\"\"A liquid cap on a flat SDF wall at z = zw, relaxed at contact angle `theta`.\"\"\"\n    mu = oh * math.sqrt(1.0 * sigma * 2.0 * R)\n    s = flow.Solver(nx, nx, nz)\n    s.set_rho(1.0)\n    s.set_mu(mu)\n    s.set_solid(slab_sdf(nx, nx, nz, zw), cutcell_pressure=True)\n    s.enable_vof()\n    if ratio != 1.0:                                   # two-phase closures of the colour\n        s.set_property_model(\"rho\", \"linear\", \"C\", [1.0 / ratio, 1.0 - 1.0 / ratio])\n        s.set_property_model(\"mu\", \"linear\", \"C\", [mu / ratio, mu - mu / ratio])\n    s.set_vof(cap_colour(nx, nx, nz, nx / 2, nx / 2, zw, R,\n                         theta if theta_init is None else theta_init))\n    s.set_surface_tension(sigma)\n    s.set_contact_angle(theta)                         # <- the entire wetting model\n\n    V0 = s.vof_diagnostics()[\"volume\"]\n    r = relax(s, steps)\n\n    d, cd = s.vof_diagnostics(), s.contact_angle_diagnostics()\n    C, eps = s.get_vof(), s.vof_geometry(0)            # colour and cell fluid fraction\n    ix = nx // 2\n    h = float((C[ix, ix, :] * eps[ix, ix, :]).sum())   # apex height: the colour column\n    V = d[\"volume\"]\n    a = math.sqrt(max((6.0 * V / (math.pi * h) - h * h) / 3.0, 1e-12))     # @eq-cap\n    z0 = int(math.ceil(zw))\n    a_contour = math.sqrt(float(C[:, :, z0].sum()) / math.pi)              # the biased read\n    kw = int(math.floor(zw))                           # the wall-adjacent cut cell\n    r.update(theta_set=theta, theta=2 * math.degrees(math.atan2(h, a)), h=h, a=a,\n             theta_contour=2 * math.degrees(math.atan2(h, a_contour)), a_contour=a_contour,\n             dV=abs(V - V0) / V0, volume=V, mu=mu, sigma=sigma, ratio=ratio,\n             Ca_open=mu * maxvel(s, z0 + 1) / sigma, umax=maxvel(s),\n             apparent=cd[\"mean_apparent_angle\"], solid_sum=d[\"solid_sum\"],\n             band=(cd[\"contact_cells\"], cd[\"neighbour_cells\"], cd[\"pure_cells\"]),\n             C=C, eps=eps, zw=zw, nx=nx, nz=nz, R=R,\n             eps_wall=float(eps[ix, ix, kw]), ox_wall=float(s.get_ox()[ix, ix, kw]))\n    return r\n```\n:::\n\n\n## 1. A drop on a flat wall\n\nFour angles, 500 capillary-limited steps each, $D/\\Delta = 24$ in a\n$64\\times64\\times40$ box, matched fluids. The wall sits at $z = 4.25$ — a\n**quarter**-integer, for a reason the last section of this page measures.\n\n::: {#sweep .cell execution_count=5}\n``` {.python .cell-code}\nTHETAS = [30.0, 60.0, 90.0, 120.0]\nflat = {th: drop_on_wall(th) for th in THETAS}\n\nprint(f\"{'theta_set':>9} {'theta':>8} {'err':>7} {'h':>7} {'a':>7} {'contour th':>11} \"\n      f\"{'dV/V':>9} {'Ca(open)':>10} {'max|u|':>9} {'iters':>8} {'max|div|':>9}\")\nfor th, r in flat.items():\n    print(f\"{th:9.0f} {r['theta']:8.3f} {r['theta']-th:+7.3f} {r['h']:7.3f} {r['a']:7.3f} \"\n          f\"{r['theta_contour']:11.3f} {r['dV']:9.1e} {r['Ca_open']:10.2e} {r['umax']:9.2e} \"\n          f\"{r['iters']:5d}/{PRESS_CAP} {r['div']:9.1e}\")\nWORST = max(abs(r[\"theta\"] - th) for th, r in flat.items())\nprint(f\"\\nworst |theta - theta_set| over the sweep: {WORST:.2f} deg\")\nprint(f\"worst below 90 deg:                       \"\n      f\"{max(abs(flat[t]['theta'] - t) for t in (30.0, 60.0, 90.0)):.2f} deg\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntheta_set    theta     err       h       a  contour th      dV/V   Ca(open)    max|u|    iters  max|div|\n       30   30.688  +0.688   5.532  20.161      34.474   1.7e-14   2.96e-04  1.45e-03     9/300   1.8e-12\n       60   59.980  -0.020   8.839  15.316      62.765   3.3e-15   3.68e-04  2.09e-03    10/300   3.0e-12\n       90   88.841  -1.159  11.880  12.123      89.399   5.0e-16   2.20e-04  4.50e-04    11/300   3.6e-13\n      120  116.858  -3.142  14.798   9.094     114.079   2.6e-15   7.99e-04  1.82e-03    10/300   1.5e-12\n\nworst |theta - theta_set| over the sweep: 3.14 deg\nworst below 90 deg:                       1.16 deg\n```\n:::\n:::\n\n\nThe measured equilibria are\n**30\\.7° / 60\\.0° / 88\\.8° / 116\\.9°** against the\nprescribed 30° / 60° / 90° / 120°. Three of the four\nrows are inside 1\\.2°;\nthe 120° row is \\-3\\.1° low, which the\n\"resolution and limits\" section below traces to the contact radius rather than to\nthe wetting model.\n\nNote the two independent readings of the angle in the table. The\nvolume-consistent one (@eq-cap) and the first-fluid-plane contour agree to under\na degree at 90° and part company by\n3\\.8° at 30° —\nthe flatter the cap, the more the near-wall averaging biases a contour read. That\ngap is a *measurement* artefact, and it is worth knowing before comparing any\ncode's contact angle with any other's.\n\n::: {#cell-fig-shapes .cell execution_count=6}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 4, figsize=(9.6, 2.9), sharey=True)\nfor ax, th in zip(axes, THETAS):\n    r = flat[th]\n    nx, nz, zw = r[\"nx\"], r[\"nz\"], r[\"zw\"]\n    x = np.arange(nx) + 0.5\n    z = np.arange(nz) + 0.5\n    ax.contour(x, z, r[\"C\"][:, nx // 2, :].T, levels=[0.5], colors=[BLUE], linewidths=1.8)\n    Rc, zc = cap_sphere(r[\"volume\"], th)                 # the reference cap\n    t = np.linspace(0, 2 * np.pi, 400)\n    cx, cz = nx / 2 + Rc * np.cos(t), zw + zc + Rc * np.sin(t)\n    keep = cz >= zw\n    ax.plot(cx[keep], cz[keep], \"--\", color=RED, lw=1.3)\n    ax.axhspan(0, zw, color=\"0.75\", zorder=0)\n    ax.axhline(zw, color=\"0.35\", lw=1.0)\n    ax.set(xlim=(nx / 2 - 24, nx / 2 + 24), ylim=(0, 34), aspect=\"equal\",\n           title=f\"$\\\\theta_{{set}} = {th:.0f}°$\\nmeasured {r['theta']:.1f}°\")\n    ax.set_xlabel(\"x  [cells]\")\n    ax.grid(alpha=0.2)\naxes[0].set_ylabel(\"z  [cells]\")\naxes[0].plot([], [], color=BLUE, lw=1.8, label=r\"$C=\\frac{1}{2}$ (measured)\")\naxes[0].plot([], [], \"--\", color=RED, lw=1.3, label=\"exact cap\")\naxes[0].legend(fontsize=7, loc=\"upper left\", framealpha=0.9)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Equilibrium drop shapes after 500 steps: the C = ½ contour in the mid-plane (solid) against the exact spherical cap of the *prescribed* angle at the *conserved* volume (dashed). The dashed curve is also the initial condition, so the overlap is the fixed-point statement: an interface that already meets the wall at θ is left there. The grey band is the solid; the wall sits at z = 4.25, a quarter of a cell inside the cell below.](index_files/figure-html/fig-shapes-output-1.png){#fig-shapes}\n:::\n:::\n\n\n## 2. The same sweep at density ratio 100\n\nMatched fluids isolate the wetting model; a real drop does not have them. The\ndensity and viscosity become linear closures of the colour, which is what switches\nthe solver onto its variable-density projection, and everything else is identical.\n\n::: {#ratio100 .cell execution_count=7}\n``` {.python .cell-code}\nflat100 = {th: drop_on_wall(th, ratio=100.0) for th in THETAS}\n\nprint(f\"{'theta_set':>9} {'ratio 1':>9} {'ratio 100':>11} {'difference':>12} \"\n      f\"{'dV/V':>9} {'Ca(open)':>10} {'iters':>9} {'max|div|':>9}\")\nfor th in THETAS:\n    a, b = flat[th][\"theta\"], flat100[th][\"theta\"]\n    print(f\"{th:9.0f} {a:9.3f} {b:11.3f} {b-a:+12.3f} {flat100[th]['dV']:9.1e} \"\n          f\"{flat100[th]['Ca_open']:10.2e} {flat100[th]['iters']:6d}/{PRESS_CAP} \"\n          f\"{flat100[th]['div']:9.1e}\")\nDRIFT100 = max(abs(flat100[t][\"theta\"] - flat[t][\"theta\"]) for t in THETAS)\nprint(f\"\\nlargest ratio-1 vs ratio-100 difference: {DRIFT100:.2f} deg\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntheta_set   ratio 1   ratio 100   difference      dV/V   Ca(open)     iters  max|div|\n       30    30.688      29.920       -0.768   3.2e-12   1.72e-03     11/300   8.5e-09\n       60    59.980      58.360       -1.620   1.9e-11   2.57e-03     11/300   1.4e-08\n       90    88.841      88.439       -0.402   2.5e-11   3.02e-03     11/300   2.0e-08\n      120   116.858     116.415       -0.443   1.5e-12   4.48e-03     12/300   2.3e-08\n\nlargest ratio-1 vs ratio-100 difference: 1.62 deg\n```\n:::\n:::\n\n\n::: {#cell-fig-angle .cell execution_count=8}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(4.8, 4.2))\ntt = np.array([20, 132])\nax.fill_between(tt, tt - 3, tt + 3, color=BLUE, alpha=0.13, lw=0, label=\"±3° gate band\")\nax.plot(tt, tt, color=\"0.4\", lw=1.0, label=\"ideal\")\nax.plot(THETAS, [flat[t][\"theta\"] for t in THETAS], \"o-\", color=BLUE, ms=7, lw=1.6,\n        label=\"density ratio 1\")\nax.plot(THETAS, [flat100[t][\"theta\"] for t in THETAS], \"s--\", color=ORANGE, ms=6, lw=1.4,\n        label=\"density ratio 100\")\nax.set(xlabel=r\"prescribed $\\theta$  [deg]\", ylabel=r\"measured apparent $\\theta$  [deg]\",\n       xlim=(20, 132), ylim=(20, 132), title=\"The angle you set is the angle you get\")\nax.set_aspect(\"equal\")\nax.legend(fontsize=8, loc=\"upper left\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Measured apparent contact angle against the prescribed one at density ratios 1 and 100. The shaded band is ±3°, the tolerance the solver's own gate uses. The two curves track each other to within 1.7° at every angle and share the same −3.6° residual at 120°, so the discrete equilibrium is a property of the colour-field fill and not of the density contrast.](index_files/figure-html/fig-angle-output-1.png){#fig-angle}\n:::\n:::\n\n\nAt a hundredfold density contrast the equilibrium angles move by at most\n**1\\.6°** and the residual at 120° is the same −3.6°.\nThat is the check that matters for the model: the fill is a purely geometric\nstatement about the colour field, and the measurement confirms it does not\ninherit anything from the momentum equation it feeds.\n\n## 3. The approach to rest\n\nThe fixed-point protocol starts *at* equilibrium, so what the velocity trace shows\nis the relaxation of the discrete transient — the initial condition is an exact\ncap, but the discrete curvature of an exact cap is not exactly constant, and the\nband fill has to settle into the shape it is idempotent on.\n\n::: {#cell-fig-rest .cell execution_count=9}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(5.2, 3.6))\ncols = {30.0: BLUE, 60.0: GREEN, 90.0: ORANGE, 120.0: RED}\nfor th in THETAS:\n    tr = flat[th][\"trace\"]\n    ax.semilogy(tr[:, 0], tr[:, 1], color=cols[th], lw=1.6, label=f\"$\\\\theta = {th:.0f}°$\")\nax.set(xlabel=\"step\", ylabel=r\"$\\max|\\mathbf{u}|$\",\n       title=\"Relaxation to the equilibrium cap ($D/\\\\Delta = 24$, Oh $= 0.1$)\")\nax.legend(fontsize=8, ncol=2)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Maximum velocity anywhere in the domain against step number, for the four prescribed angles at density ratio 1. All four fall by one to two decades and flatten: the drop is at rest, and what remains is the near-wall parasitic floor quantified in the next section — not an unfinished transient. Curves are sampled every 25 steps.](index_files/figure-html/fig-rest-output-1.png){#fig-rest}\n:::\n:::\n\n\n## 4. A drop on a solid sphere\n\nA flat wall lets the fill get away with a lot: $\\mathbf{n}_w$ is constant, the\nband is three flat rows, and every column sees the same geometry. A **curved**\nsolid is the real test, and it also has a closed-form answer.\n\nPut a drop of volume $V$ on a solid sphere of radius $R_s$. At rest the free\nsurface is a sphere of radius $R_c$ whose centre sits a distance $d$ from the\nsolid's, and the two spheres must meet at $\\theta$ — which by the law of cosines is\n\n$$\nd^2 = R_s^2 + R_c^2 - 2 R_s R_c \\cos\\theta ,\n$$ {#eq-lawcos}\n\nwhile the liquid volume is the drop sphere minus the lens the two spheres share.\nGiven $(V, \\theta)$ that is a one-dimensional root solve for $R_c$ — the\nreference shape, with no fitting and no free parameters.\n\n::: {#sphere-ref .cell execution_count=10}\n``` {.python .cell-code}\ndef lens_volume(Rs, Rc, d):\n    \"\"\"Volume of the intersection of spheres (centre 0, radius Rs) and (centre d, Rc).\"\"\"\n    if d >= Rs + Rc:\n        return 0.0\n    if d <= abs(Rs - Rc):\n        return 4.0 / 3.0 * math.pi * min(Rs, Rc) ** 3\n    return (math.pi * (Rs + Rc - d) ** 2\n            * (d * d + 2 * d * Rc - 3 * Rc ** 2 + 2 * d * Rs + 6 * Rc * Rs - 3 * Rs ** 2)\n            / (12.0 * d))\n\n\ndef drop_volume(Rs, Rc, d):\n    return 4.0 / 3.0 * math.pi * Rc ** 3 - lens_volume(Rs, Rc, d)\n\n\ndef cap_from_volume(Rs, V, theta_deg):\n    \"\"\"(V, theta) -> the reference cap sphere (Rc, d) via @eq-lawcos. Bisection.\"\"\"\n    ct = math.cos(theta_deg * DEG)\n    lo, hi = 1e-3, 50.0 * Rs\n    for _ in range(200):\n        mid = 0.5 * (lo + hi)\n        d = math.sqrt(max(Rs ** 2 + mid ** 2 - 2 * Rs * mid * ct, 0.0))\n        (lo, hi) = (mid, hi) if drop_volume(Rs, mid, d) < V else (lo, mid)\n    Rc = 0.5 * (lo + hi)\n    return Rc, math.sqrt(max(Rs ** 2 + Rc ** 2 - 2 * Rs * Rc * ct, 0.0))\n\n\ndef theta_from_volume_apex(Rs, V, H):\n    \"\"\"The inverse reading: (V, apex height H = d + Rc) -> (Rc, d, theta).\"\"\"\n    lo, hi = 1e-3, H\n    for _ in range(200):\n        Rc = 0.5 * (lo + hi)\n        (lo, hi) = (Rc, hi) if drop_volume(Rs, Rc, max(H - Rc, 0.0)) < V else (lo, Rc)\n    Rc = 0.5 * (lo + hi)\n    d = H - Rc\n    ct = (Rs ** 2 - d ** 2 + Rc ** 2) / (2.0 * Rs * Rc)\n    return Rc, d, math.degrees(math.acos(max(-1.0, min(1.0, ct))))\n```\n:::\n\n\n::: {#sphere-run .cell execution_count=11}\n``` {.python .cell-code}\ndef drop_on_sphere(theta, steps=500, Rs=12.0, Rd=8.0, n=64, sigma=1.0, oh=0.1):\n    \"\"\"A drop with the volume of a sphere of radius Rd, resting on a solid sphere Rs.\"\"\"\n    mu = oh * math.sqrt(1.0 * sigma * 2.0 * Rd)\n    c = n * 0.5\n    ax_ = (np.arange(n) + 0.5)\n    sdf = np.asfortranarray(np.sqrt((ax_[:, None, None] - c) ** 2\n                                    + (ax_[None, :, None] - c) ** 2\n                                    + (ax_[None, None, :] - c) ** 2) - Rs)\n    V = 4.0 / 3.0 * math.pi * Rd ** 3\n    Rc0, d0 = cap_from_volume(Rs, V, theta)\n\n    sub = (np.arange(4) + 0.5) / 4.0                       # exact-ish initial fractions\n    px = np.arange(n)[:, None, None, None, None, None] + sub[None, None, None, :, None, None]\n    py = np.arange(n)[None, :, None, None, None, None] + sub[None, None, None, None, :, None]\n    pz = np.arange(n)[None, None, :, None, None, None] + sub[None, None, None, None, None, :]\n    fluid = ((px - c) ** 2 + (py - c) ** 2 + (pz - c) ** 2) > Rs ** 2\n    liq = fluid & (((px - c) ** 2 + (py - c) ** 2 + (pz - c - d0) ** 2) < Rc0 ** 2)\n    tot = fluid.sum(axis=(3, 4, 5))\n    C0 = np.asfortranarray(np.where(tot > 0, liq.sum(axis=(3, 4, 5)) / np.maximum(tot, 1),\n                                    0.0).astype(float))\n\n    s = flow.Solver(n, n, n)\n    s.set_rho(1.0)\n    s.set_mu(mu)\n    s.set_solid(sdf, cutcell_pressure=True)\n    s.enable_vof()\n    s.set_vof(C0)\n    s.set_surface_tension(sigma)\n    s.set_contact_angle(theta)\n    V0 = s.vof_diagnostics()[\"volume\"]\n    r = relax(s, steps)\n\n    d, cd = s.vof_diagnostics(), s.contact_angle_diagnostics()\n    C, eps = s.get_vof(), s.vof_geometry(0)\n    i = int(c)\n    H = float((C[i, i, :] * eps[i, i, :])[int(c):].sum()) + Rs     # apex above the centre\n    Vm = d[\"volume\"]\n    Rc, dd, th = theta_from_volume_apex(Rs, Vm, H)\n    r.update(theta_set=theta, theta=th, Rc=Rc, Rc_ref=Rc0, d=dd, d_ref=d0, H=H,\n             H_ref=d0 + Rc0, dV=abs(Vm - V0) / V0, Ca=mu * maxvel(s) / sigma,\n             apparent=cd[\"mean_apparent_angle\"], solid_sum=d[\"solid_sum\"],\n             C=C, n=n, Rs=Rs, c=c, mu=mu)\n    return r\n\n\nSPH_THETAS = [60.0, 90.0, 120.0]\nsph = {th: drop_on_sphere(th) for th in SPH_THETAS}\n\nprint(f\"{'theta_set':>9} {'Rc':>7} {'Rc ref':>8} {'Rc err':>9} {'H':>7} {'H ref':>7} \"\n      f\"{'theta(V,H)':>11} {'local th':>9} {'dV/V':>9} {'iters':>9}\")\nfor th, r in sph.items():\n    print(f\"{th:9.0f} {r['Rc']:7.3f} {r['Rc_ref']:8.3f} \"\n          f\"{100*(r['Rc']-r['Rc_ref'])/r['Rc_ref']:+8.2f}% {r['H']:7.3f} {r['H_ref']:7.3f} \"\n          f\"{r['theta']:11.2f} {r['apparent']:9.2f} {r['dV']:9.1e} \"\n          f\"{r['iters']:6d}/{PRESS_CAP}\")\nRC_WORST = max(abs(r[\"Rc\"] - r[\"Rc_ref\"]) / r[\"Rc_ref\"] for r in sph.values())\nprint(f\"\\nworst cap-radius error: {100*RC_WORST:.2f} %\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntheta_set      Rc   Rc ref    Rc err       H   H ref  theta(V,H)  local th      dV/V     iters\n       60   9.368    9.585    -2.27%  21.041  20.578       64.86     74.38   4.4e-11      9/300\n       90   8.612    8.549    +0.74%  23.067  23.283       87.44     89.43   2.2e-11      9/300\n      120   8.174    8.119    +0.68%  25.178  25.649      113.53    113.92   1.1e-11      9/300\n\nworst cap-radius error: 2.27 %\n```\n:::\n:::\n\n\n::: {#cell-fig-sphere .cell execution_count=12}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 3, figsize=(8.4, 3.2), sharey=True)\nt = np.linspace(0, 2 * np.pi, 500)\nfor ax, th in zip(axes, SPH_THETAS):\n    r = sph[th]\n    n, c, Rs = r[\"n\"], r[\"c\"], r[\"Rs\"]\n    g = np.arange(n) + 0.5\n    ax.contour(g, g, r[\"C\"][:, int(c), :].T, levels=[0.5], colors=[BLUE], linewidths=1.8)\n    ax.plot(c + r[\"Rc_ref\"] * np.cos(t), c + r[\"d_ref\"] + r[\"Rc_ref\"] * np.sin(t),\n            \"--\", color=RED, lw=1.3)\n    ax.add_patch(plt.Circle((c, c), Rs, color=\"0.75\", zorder=0))\n    ax.plot(c + Rs * np.cos(t), c + Rs * np.sin(t), color=\"0.35\", lw=1.0)\n    ax.set(xlim=(c - 20, c + 20), ylim=(c - 16, c + 26), aspect=\"equal\",\n           title=f\"$\\\\theta_{{set}} = {th:.0f}°$\\n$R_c$ \"\n                 f\"{100*(r['Rc']-r['Rc_ref'])/r['Rc_ref']:+.2f} %\")\n    ax.set_xlabel(\"x  [cells]\")\n    ax.grid(alpha=0.2)\naxes[0].set_ylabel(\"z  [cells]\")\naxes[0].plot([], [], color=BLUE, lw=1.8, label=r\"$C=\\frac{1}{2}$\")\naxes[0].plot([], [], \"--\", color=RED, lw=1.3, label=\"analytic cap\")\naxes[0].legend(fontsize=7, loc=\"lower left\", framealpha=0.9)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![A drop resting on a solid sphere of radius 12 cells. Solid line: the measured C = ½ contour in the mid-plane. Dashed: the analytic cap sphere that intersects the solid at the prescribed angle with the same (conserved) liquid volume, from the root solve of @eq-lawcos. The two agree to better than 2.3 % in cap radius at every angle — on a curved wall, where the wall normal turns from column to column.](index_files/figure-html/fig-sphere-output-1.png){#fig-sphere}\n:::\n:::\n\n\nThe measured cap radii are within\n**2\\.3 %** of the analytic two-sphere solution at all\nthree angles — on a wall whose normal turns from column to column, which is the\ncase the flat wall cannot exercise.\n\n::: {.callout-note}\n## Why the table gates the cap *radius* and not the angle\nThe angle column of the sphere table is off by up to\n6\\.5° while the shape\nis right to under a percent, and that is a statement about the **measurement**.\nThe angle is inferred by inverting $(V, H) \\to (R_c, d) \\to \\theta$ from the\nconserved volume and the apex height, and that inversion is badly conditioned:\nhere $\\mathrm{d}\\theta/\\mathrm{d}H \\approx 10°$ per cell, so a half-cell error in\na colour column sum — exactly what an interface crossing a cell diagonally gives —\nis worth five degrees. The cap radius is the well-conditioned reading, and the\nsolver's *local* estimator (`contact_angle_diagnostics()['mean_apparent_angle']`,\nthe last column of the table) is the other one: it reads\n74° / 89° / 114° against\nthe prescribed 60 / 90 / 120. Global-shape inversions are a trap in wetting\nbenchmarks generally, not just here.\n:::\n\n## 5. Volume, and what a contact line costs in spurious currents\n\nTwo health numbers. The liquid volume must be conserved by the geometric\ntransport to the projection's own divergence residual — that is the whole point of\na Weymouth–Yue scheme, and the openness-weighted cut-cell form keeps it. And the\nspurious currents near a contact line are the honest price of the wetting model:\nthe [parasitic-currents page](../parasitic-currents/index.qmd) measures\n$\\mathrm{Ca} = 2.6\\times10^{-5}$ for a **free** droplet at the same $D/\\Delta$,\nwhich is the floor a wetting run can be compared against.\n\n::: {#conservation .cell execution_count=13}\n``` {.python .cell-code}\nCA_FREE = 2.6e-5      # free droplet at D/dx = 24, from the parasitic-currents page\nprint(f\"{'':<14}{'theta':>7} {'dV/V':>10} {'max|div|':>10} {'Ca(open fluid)':>16} \"\n      f\"{'x free droplet':>16} {'solid colour':>13}\")\nfor tag, tab in ((\"flat, ratio 1\", flat), (\"flat, ratio 100\", flat100)):\n    for th in THETAS:\n        r = tab[th]\n        print(f\"{tag if th == THETAS[0] else '':<14}{th:7.0f} {r['dV']:10.1e} \"\n              f\"{r['div']:10.1e} {r['Ca_open']:16.2e} \"\n              f\"{r['Ca_open']/CA_FREE:15.0f}x {r['solid_sum']:13.1e}\")\nfor th in SPH_THETAS:\n    r = sph[th]\n    print(f\"{'sphere' if th == SPH_THETAS[0] else '':<14}{th:7.0f} {r['dV']:10.1e} \"\n          f\"{r['div']:10.1e} {r['Ca']:16.2e} {r['Ca']/CA_FREE:15.0f}x \"\n          f\"{r['solid_sum']:13.1e}\")\n\nCA_RANGE = (min(flat[t][\"Ca_open\"] for t in THETAS), max(flat[t][\"Ca_open\"] for t in THETAS))\nDV_MAX = max(flat[t][\"dV\"] for t in THETAS)\nprint(f\"\\nflat wall, ratio 1: dV/V <= {DV_MAX:.1e};  Ca in \"\n      f\"[{CA_RANGE[0]:.1e}, {CA_RANGE[1]:.1e}] = \"\n      f\"{CA_RANGE[0]/CA_FREE:.0f}x .. {CA_RANGE[1]/CA_FREE:.0f}x the free droplet\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                theta       dV/V   max|div|   Ca(open fluid)   x free droplet  solid colour\nflat, ratio 1      30    1.7e-14    1.8e-12         2.96e-04              11x       0.0e+00\n                   60    3.3e-15    3.0e-12         3.68e-04              14x       0.0e+00\n                   90    5.0e-16    3.6e-13         2.20e-04               8x       0.0e+00\n                  120    2.6e-15    1.5e-12         7.99e-04              31x       0.0e+00\nflat, ratio 100     30    3.2e-12    8.5e-09         1.72e-03              66x       0.0e+00\n                   60    1.9e-11    1.4e-08         2.57e-03              99x       0.0e+00\n                   90    2.5e-11    2.0e-08         3.02e-03             116x       0.0e+00\n                  120    1.5e-12    2.3e-08         4.48e-03             172x       0.0e+00\nsphere             60    4.4e-11    1.1e-08         1.25e-03              48x       0.0e+00\n                   90    2.2e-11    9.8e-09         3.33e-03             128x       0.0e+00\n                  120    1.1e-11    6.5e-09         1.15e-03              44x       0.0e+00\n\nflat wall, ratio 1: dV/V <= 1.7e-14;  Ca in [2.2e-04, 8.0e-04] = 8x .. 31x the free droplet\n```\n:::\n:::\n\n\nThree things to read off that table.\n\n**Volume is exact.** On the flat wall the drift is at most\n1\\.7e\\-14 relative over 500 steps, and the colour inside the\nsolid is **exactly zero** in every run — the transport never leaks liquid into\nthe wall, and the band fill the stencils read is a separate working field.\n\n**The conservation floor is the pressure solve, not the advection.** The\nmatched-fluid flat-wall runs carry `max|div(open·u)|` around $10^{-12}$ and drift\nat $10^{-14}$; the harder projections — the variable-density rows and the curved\nsolid — carry $10^{-8}$ and drift at $10^{-11}$. The *ratio* of the two is the\nsame everywhere, which is the signature of a transport whose conservation is\nexact and inherits the projection's residual. If you need tighter volume\nconservation, tighten the projection; refining the transport will not help.\n\n**A contact line costs about an order of magnitude in spurious currents.** With\nmatched fluids the near-wall $\\mathrm{Ca}$ over the open fluid runs\n2\\.2e\\-04–8\\.0e\\-04, i.e.\n8–31× the\nfree-droplet floor; at density ratio 100 the same measurement is five to\nfourteen times larger again. This is measured over the **open fluid only** ($z$ above the first fully open plane).\nVelocities on the immersed DOFs inside and on the wall are constrained by the IBM\nand multiplied by zero openness everywhere they could act; quoting them would\nmeasure the immersed boundary rather than the surface-tension balance — and, as\nthe next section shows, at one particular wall placement they are enormous while\nthe physics is unchanged.\n\n## 6. Resolution and limits — read this before using it\n\nThis rung is honest about four things.\n\n### The contact line needs about ten cells\n\nThe error over the sweep is monotone in $\\theta$:\n\\+0\\.7 / \\-0\\.0 / \\-1\\.2 / \\-3\\.1 degrees at\n30 / 60 / 90 / 120. So is the contact radius:\n20\\.2 / 15\\.3 / 12\\.1 / 9\\.1 cells. The row that\nmisses is the row whose contact line is resolved by fewer than ten radial cells,\nand at $\\theta = 150°$ on this grid the contact radius would be about 5 cells,\nwhere the solver's own study measures −3.8°.\n\n**The practical rule: size the grid on the contact radius $a$, not on the drop\ndiameter.** For an obtuse angle $a \\ll D$, so a $D/\\Delta$ that is generous for a\nfree droplet is not generous for a wetting one.\n\n### The residual above 90° is converged, and unexplained\n\nThe −3.6° at 120° is not an unfinished transient. Run to rest in the solver's own\nstudy (1500 steps, `max|u|` down to $1.8\\times10^{-4}$) the same scene settles at\n116.40°, and the velocity trace on this page is already flat at 500 steps. Two\ncandidate mechanisms have been ruled out by measurement: it is **not** the density\ncontrast (the ratio-100 column above reproduces it), and it is **not** the\ncut-cell reconstruction — with the wall on a cell face, where the anchor cell is\nuncut and that approximation is exactly absent, the same run reads *worse*\n(115.3° after 750 steps). It tracks the contact-line resolution, which is why the\nrecommendation above is a resolution rule rather than a correction factor. The\nrefinement that is *not* implemented is the solid-clipped flux polygon\n[@chen2025]: peclet reconstructs the PLIC plane on the whole unit cell and\nmultiplies its slab volume by the open face area, rather than clipping it against\nthe solid as well.\n\n### It is a *static* angle\n\n$\\theta$ is a per-cell field and the fill is evaluated every step, but the value\nit is given does not depend on the contact-line velocity. There is no dynamic\ncontact angle and no hysteresis: an advancing and a receding contact line are\ngiven the same $\\theta$. That is rung V6 of the VoF campaign; when it lands, only\nwhat fills the $\\theta$ field changes, not the machinery on this page.\n\nA consequence worth budgeting for: **the approach to a prescribed angle is slow.**\nThe driving force vanishes as the contact line arrives, so a relaxation that has\nto move the line through 30° takes $O(10^3)$ capillary-limited steps, not\n$O(10^2)$ — the wall-placement run below starts from a hemisphere and is still\ntravelling after 300.\n\n### The wall placement trap\n\n::: {.callout-warning}\n## Do not put a flat SDF wall at a half-integer coordinate\nIt is the natural choice — it makes the wall cells \"genuinely cut\" — and it\nsilently freezes the contact line. Use a quarter-integer, or put the wall exactly\non a cell face.\n:::\n\nAt exactly $z = k + \\tfrac12$ the *tangential* MAC faces of the wall-adjacent cell\nsit **on** the SDF zero level. The openness builder treats $\\varphi > 0$ as fluid,\nso $\\varphi = 0$ closes them: the cell reads a fluid fraction of 0.5 and a\ntangential face openness of 0.000 *at the same time*. It is a fluid cell that can\nexchange nothing along the wall — no colour, no momentum — so the contact line\ncannot move, and the unrelieved Young force appears as a velocity of order 1 on\nDOFs the projection never sees.\n\nOne angle, one initial condition (a hemisphere, so the contact line *has* to\ntravel), everything identical except where the wall sits inside its cell:\n\n::: {#wall-trap .cell execution_count=14}\n``` {.python .cell-code}\nplace = {zw: drop_on_wall(60.0, steps=300, zw=zw, theta_init=90.0) for zw in (4.25, 3.5)}\nprint(f\"{'wall z':>7} {'eps (wall cell)':>16} {'tangential ox':>15} \"\n      f\"{'theta @300':>11} {'max|u|':>10} {'verdict':>18}\")\nfor zw, r in place.items():\n    verdict = \"mobile, cut\" if r[\"ox_wall\"] > 0 else \"PINNED\"\n    print(f\"{zw:7.2f} {r['eps_wall']:16.3f} {r['ox_wall']:15.3f} {r['theta']:11.2f} \"\n          f\"{r['umax']:10.2e} {verdict:>18}\")\nUFAC = place[3.5][\"umax\"] / place[4.25][\"umax\"]\nprint(f\"\\nsame physics, same theta, same steps: max|u| differs by a factor {UFAC:.0f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n wall z  eps (wall cell)   tangential ox  theta @300     max|u|            verdict\n   4.25            0.750           0.750       73.85   2.90e-02        mobile, cut\n   3.50            0.500           0.000       81.42   1.05e+00             PINNED\n\nsame physics, same theta, same steps: max|u| differs by a factor 36\n```\n:::\n:::\n\n\n::: {#cell-fig-walltrap .cell execution_count=15}\n``` {.python .cell-code}\nfig, (ax, axb) = plt.subplots(1, 2, figsize=(8.4, 3.3),\n                              gridspec_kw=dict(width_ratios=[1.25, 1]))\nfor zw, col, lab in ((4.25, BLUE, \"wall at $z = 4.25$ (quarter cell)\"),\n                     (3.5, RED, \"wall at $z = 3.50$ (half cell)\")):\n    tr = place[zw][\"trace\"]\n    ax.semilogy(tr[:, 0], tr[:, 1], color=col, lw=1.8, label=lab)\nax.set(xlabel=\"step\", ylabel=r\"$\\max|\\mathbf{u}|$\",\n       title=\"Where the wall sits inside its cell\")\nax.legend(fontsize=8, loc=\"center right\")\n\nx = np.arange(place[4.25][\"nx\"]) + 0.5\nfor zw, col in ((4.25, BLUE), (3.5, RED)):\n    r = place[zw]\n    z = np.arange(r[\"nz\"]) + 0.5\n    axb.contour(x, z, r[\"C\"][:, r[\"nx\"] // 2, :].T, levels=[0.5], colors=[col],\n                linewidths=1.8)\n    axb.axhline(zw, color=col, lw=0.9, ls=\":\")\naxb.axhspan(0, 4.25, color=\"0.85\", zorder=0)\naxb.set(xlim=(32 - 22, 32 + 22), ylim=(0, 26), aspect=\"equal\", xlabel=\"x  [cells]\",\n        ylabel=\"z  [cells]\",\n        title=f\"shape after 300 steps\\n({place[4.25]['theta']:.0f}° travelling vs \"\n              f\"{place[3.5]['theta']:.0f}° stalled)\")\naxb.grid(alpha=0.2)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The same relaxation (θ = 60° from a hemisphere, 300 steps) with the SDF wall a quarter of a cell into the wall cell (blue) and exactly half a cell in (red). At the half-integer placement the wall cell's tangential face openness is exactly zero: the contact line cannot move and a velocity of order 1 builds up on those closed-face DOFs. Nothing about the physics differs between the two runs.](index_files/figure-html/fig-walltrap-output-1.png){#fig-walltrap}\n:::\n:::\n\n\nThe mobile run has travelled from 90° to\n74° and is still going; the pinned one sits\nat 81° with a `max|u|` of\n1\\.05, a factor 36 larger.\nNeither run touched the pressure cap, both conserve volume, and there is no error\nmessage: the only visible symptom is a drop that stops at the wrong shape.\n\n::: {.callout-note}\n## A domain-BC wall is not a wetting wall\n`set_domain_bc(face, 1)` gives a no-slip domain wall, and it does **not** receive\nthe contact-angle fill — the band fill runs on the SDF classification only, so a\ndomain wall keeps the zero-gradient (90°) colour extrapolation whatever\n`set_contact_angle` says. Model a wetting wall as an **SDF slab**, which is what\nevery run on this page does.\n:::\n\n## Collocated cross-check\n\npeclet also ships a cell-centred/collocated grid (`flow.SolverColocated`), and\nsince rung V8 (2026-09-02) it runs two-phase flow: variable density in the\napproximate (ABC) projection, surface tension as a face acceleration, and the\ncolour advected by the projected face field. The\n[parasitic currents](../parasitic-currents/index.qmd) and\n[capillary oscillations](../capillary-oscillations/index.qmd) pages carry that\ncolumn.\n\n**This page is not one of them, and the reason is the solid.** Rung V8 is\n*all-fluid*: the cut-cell colour transport of rung V5a — openness-weighted\ngeometric fluxes, the solid-band fill, and with it the contact-angle plane this\nwhole page is about — exists on the staggered grid only. The composition is\nrefused rather than silently approximated:\n\n::: {#colocated-scope .cell execution_count=16}\n``` {.python .cell-code}\ns = flow.SolverColocated(32, 32, 24)\ns.set_rho(1.0)\ns.set_mu(0.1)\ns.set_solid(slab_sdf(32, 32, 24, 4.25), cutcell_pressure=True)   # accepted: single-phase is fine\ntry:\n    s.enable_vof()\n    print(\"enable_vof() succeeded — this page's setup would run\")\nexcept RuntimeError as e:\n    print(f\"enable_vof() raised RuntimeError:\\n  {e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nenable_vof() raised RuntimeError:\n  enable_vof: geometric VoF on SolverColocated (rung V8) is ALL-FLUID only — an immersed solid needs the cut-cell face acceleration and the matching one-sided closures, which is a later rung. Use the staggered Solver (rung V5a supports cut cells).\n```\n:::\n:::\n\n\nThe reverse call order is guarded in the same place rather than in `set_solid`:\n`enable_vof()` first and `set_solid()` second is accepted, and the throw then\narrives from `set_vof`, `set_surface_tension` and `step()` with the same message.\n`set_contact_angle` itself never raises — it only records the angle — so the\nguard you will actually meet is the one above.\n\nThere is nothing to report here yet, and nothing to approximate: every number on\nthis page is a **staggered** number, and the contact-angle model has no collocated\ncolumn until the cut-cell face acceleration lands. The\n[rising bubble](../rising-bubble/index.qmd) page states the other half of the\ncurrent rating — collocated two-phase flow is honest to density ratio $\\lesssim\n100$ for cases with motion, because momentum-consistent transport is staggered-only\nas well.\n\n## Adapt this yourself\n\n- **Pattern the wettability.** `set_contact_angle_field(theta_deg_array)` takes a\n  per-cell angle, so a chemically striped or patchy surface is one array away.\n  The fill is evaluated per band cell, so nothing else changes.\n- **Put it on a packing.** The wall here is a slab and a sphere; the same three\n  calls work on any SDF, including a `dem`-generated sphere packing — that is the\n  trickle-flow example, and the only extra ingredients are two-phase inflow and\n  outflow boundaries.\n- **Check the fill you are getting.** `vof_filled_colour()` returns the working\n  colour field *including* the band inside the solid, and\n  `contact_angle_diagnostics()` returns the census of which rule filled each band\n  cell (`contact_cells` = the θ-plane rule, `neighbour_cells` = averaged from\n  mixed neighbours, `pure_cells` = pure-phase continuation) plus the mean locally\n  measured apparent angle. If `contact_cells` is zero, your contact line is not\n  where you think it is.\n- **Ablate the anchor.** `set_contact_angle_pivot(0..3)` switches the plane's\n  anchor between the shipped volume-matched one and three geometric alternatives,\n  one of which is the obvious \"project the interface centroid onto the wall\". It\n  is *not* idempotent — the prescribed angle stops being a fixed point — and the\n  ablation shows by how much.\n- **Go multi-rank.** The identical script runs under `mpirun -np N python …`. The\n  band fill is built on the inner region and exchanged rather than guessed at\n  depth, so the filled colour is **bitwise** decomposition-independent even when\n  the block cut goes through the contact line.\n\n## Reproduce this\n\nThe compiled solver runs this, so its outputs are **frozen** into the site. To\nregenerate:\n\n```bash\npip install peclet            # the solver, from PyPI\nquarto render examples/droplet-wetting/index.qmd --execute\n# ...or against a local source build of the suite (GPU):\nPECLET_LOCAL_BUILD=/path/to/suite/flow/build_cuda OMP_NUM_THREADS=8 OMP_PROC_BIND=false \\\n  quarto render examples/droplet-wetting/index.qmd --execute\n```\n\nThe same battery lives inside the solver repo as\n`tests/study/vof_wetting.py` (`g1` the flat-wall sweep, `g1w` the wall-placement\nstudy, `g2` the drop on a sphere, `g4` a capillary-rise case that does **not**\nyet pass and is documented as such), and the kernel-level gates — the flat-wall\nidempotence of the fill to $10^{-15}$, the rotation, the wetting limits at\n$\\theta = 0$ and $180°$ — run in the `vof_wetting` ctest, with its MPI twin at\nnp = 1/2/4.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}