{"hash": "45677b4193a48a69f96a5fced6f7922b", "result": {"engine": "jupyter", "markdown": "---\ntitle: \"Trickle flow over a sphere packing\"\nsubtitle: \"Liquid fed onto a wetting packing through a distributor, gas around it, an open outlet below \u2014 three VoF rungs composed into one gas\u2013liquid\u2013solid unit cell, with the colour budget closing at the projection floor.\"\nauthor: \"Peclet\"\ndate: \"2026-09-02\"\ncategories: [flow, dem, vof, two-phase, wetting, porous-media, multi-method, gpu]\njupyter: python3\n---\n\n\n\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/computational-chemical-engineering/peclet-examples/blob/main/examples/trickle-flow-packing/index.ipynb){target=\"_blank\"}\n&nbsp;Wants a GPU build: a DEM packing, one $48\\times48\\times96$ two-phase run and three on half\nthat grid, each several thousand steps.\n\n## What you'll learn\n\nThe other two-phase pages in this gallery each isolate **one** piece of physics against a\nclosed-form answer. This one composes three of them and lets the answer be a *balance*:\n\n- **cut-cell VoF** \u2014 the colour field transported through an immersed solid with openness-weighted\n  geometric fluxes;\n- **a static contact angle** on that solid \u2014 $\\theta = 60\u00b0$, imposed entirely through the colour\n  field *inside* the grains, with no force added at the wall;\n- **two-phase open boundaries** \u2014 a liquid distributor over part of the inlet face, and an outlet\n  that lets liquid *and* gas leave and lets gas back in wherever the flow reverses.\n\nThe case is a trickle-bed unit cell: liquid dripped onto a gravity-settled random packing of\nspheres, gas around it, gravity down, an open bottom. There is no analytical answer to check\nagainst \u2014 a rivulet network is not a spherical cap \u2014 so what the page gates instead is everything\nthat must hold *whatever* the physics does:\n\n1. **The liquid is conserved exactly.** Injected, minus what has left, minus what is held in the\n   box, is zero to about one part in $10^{13}$ of the injected volume \u2014 through a solid, through a\n   partially covered inlet and through an outlet, over thousands of fully coupled steps. That\n   identity is the reason to believe the holdup number at all.\n2. **The projection stays healthy.** Every run records `last_pressure_iterations()` against its cap\n   and the *non-mutating* `max_open_divergence_projected()`; a capped run would be discarded, not\n   quoted. No run below reaches its iteration cap \u2014 the count is printed with each one \u2014\n   and the divergence of the projected field at the outlet stays below $10^{-8}$, four to five\n   orders better than the same case gave before the variable-density outflow operator was fixed.\n3. **The functionals are followed from a dry bed**, in the three quantities a trickle bed is\n   designed around \u2014 liquid holdup, wetted-area fraction, pressure drop. They are still *rising*\n   when the run stops: the liquid load chosen here fills the bed faster than its films drain it, so\n   within the run length this page can afford on a shared GPU the unit cell never reaches the state\n   where the outlet returns what the distributor delivers. That is reported rather than hidden, and it is\n   what makes the run-to-run comparisons below same-time comparisons rather than steady-state ones.\n\nAnd the honest part, three times over: the Bond number here is the physical one but the **Capillary\nnumber is set by the grid** and is two to three orders too high \u2014 an inequality with a proof, in\n[resolution and limits](#sec-limits); the run is a **filling transient**, not a steady state; and at\ndensity ratio 1000 the run still conserves and still converges, but the solver's own gates say the\n*velocities* in thin liquid structures are not yet trustworthy there. All three are stated where\nthe numbers are.\n\n## The problem: a trickle-bed unit cell\n\nA trickle-bed reactor is a packed column with liquid running down over the grains as films and\nrivulets while gas occupies the rest of the pore space. The quantities it is designed around are\nthe **liquid holdup** (how much liquid the bed retains), the **wetted fraction** (how much of the\ncatalyst surface the liquid actually touches \u2014 the rest of it is doing nothing) and the **pressure\ndrop**. All three are emergent: they come out of a competition between gravity, viscosity and\ncapillarity on a geometry nobody controls in detail.\n\nThree dimensionless groups fix that competition. With $d_p$ the sphere diameter, $\\delta$ a film\nthickness, $\\Delta\\rho$ the density difference and $u$ the film surface speed,\n\n$$\n\\mathrm{Bo} = \\frac{\\Delta\\rho\\, g\\, d_p^2}{\\sigma}, \\qquad\n\\mathrm{Ca} = \\frac{\\mu_\\ell u}{\\sigma}, \\qquad\n\\mathrm{Re}_f = \\frac{\\rho_\\ell u \\delta}{\\mu_\\ell} .\n$$ {#eq-groups}\n\n$\\mathrm{Bo}$ says whether liquid hanging off a grain falls or stays; $\\mathrm{Ca}$ says whether\nthe film shape is set by capillarity or by shear; $\\mathrm{Re}_f$ says the film is laminar. Water\nand air on 3 mm packing give $\\mathrm{Bo}\\approx 1.2$, which is the number this page matches. It\ncannot match $\\mathrm{Ca}$, and the reason is a *grid* statement rather than a modelling one \u2014 see\n[resolution and limits](#sec-limits).\n\nThe film scale itself is a Nusselt balance: a film of thickness $\\delta$ draining down a vertical\nwall under a body force $\\Delta\\rho g$ has\n\n$$\nu(\\xi) = \\frac{\\Delta\\rho\\, g}{\\mu_\\ell}\\left(\\delta \\xi - \\tfrac12 \\xi^2\\right), \\qquad\nu_{\\max} = \\frac{\\Delta\\rho\\, g\\, \\delta^2}{2\\mu_\\ell},\n$$ {#eq-nusselt}\n\nand $u_{\\max}$ is the speed the distributor is fed at, so that liquid arrives at about the rate a\nfilm can carry it away. (peclet reproduces @eq-nusselt to **+0.21 %** in flow rate at density\nratios 100 *and* 1000 on a flat wall with an open inlet and an open outlet; that gate is what made\nthis page possible, and it exercises exactly the machinery below.)\n\n### What the boundaries have to do\n\nThe inlet and outlet are where a two-phase open-boundary problem is won or lost, so they get\nstated explicitly rather than left to a default.\n\n- **Inlet (top).** The velocity profile (`set_domain_bc_profile`) says how fast fluid enters at\n  each position on the face; the *colour* profile (`set_vof_inflow_profile`) says whether what\n  enters there is liquid or gas. A distributor is exactly that pair: a central disc carries $C=1$\n  at the Nusselt speed, the rest of the face carries $C=0$. The flux through a face whose donor\n  cell lies outside the domain is the **algebraic** $C_{\\text{ghost}}\\,a$, never a reconstructed\n  PLIC slab \u2014 a prescribed uniform ghost band has no interface in it to reconstruct, and a\n  fractional inflow colour is a statement about the incoming *flux*, not about a sub-cell interface\n  position.\n- **Outlet (bottom, `set_vof_backflow(4, 0.0)`).** Zero-gradient where the flow leaves; where the\n  boundary face velocity points back *into* the domain, the ghost band carries the prescribed\n  backflow colour \u2014 here $0$, gas. That is OpenFOAM's `inletOutlet` switch [@rusche2002], and it\n  is the volume-of-fluid half of the energy-stable two-phase open boundary of Dong\n  [@dong2014; @dong2016], whose backflow term is likewise active only where\n  $\\mathbf{n}\\cdot\\mathbf{u} < 0$. Without it, a bed that momentarily pushes fluid back through the\n  outlet would draw *liquid* in and quietly invent volume.\n- **Sides: periodic.** This is a unit cell of the interior of a bed, not a laboratory column. A\n  column wall would add its own wetting film and the wall channelling that trickle-bed\n  experimentalists spend their lives avoiding; both are real, neither is what this page measures.\n  (If you *do* want column walls, model them as an SDF slab and put them at a **quarter**-integer\n  coordinate \u2014 a flat SDF wall at $k+\\tfrac12$ closes the wall cell's tangential faces and freezes\n  the contact line, as the [droplet wetting](../droplet-wetting/index.qmd) page measures. The\n  spheres here are curved, so none of their faces sits on the zero level by construction.)\n\nThe direct precedent for the configuration is the TU/e coupled immersed-boundary + volume-of-fluid\nline [@patel2017] \u2014 a static contact angle on resolved particles inside a VoF solver \u2014 and, for the\nphysics the page shows, the packed-bed liquid-spreading study of Ambekar, R\u00fcde and Buwa\n[@ambekar2022].\n\n::: {#bootstrap .cell execution_count=1}\n``` {.python .cell-code code-summary=\"Environment bootstrap (installs peclet from PyPI on Colab/Binder)\"}\nimport importlib.util, os, subprocess, sys\n_local = os.environ.get(\"PECLET_LOCAL_BUILD\")\nif _local:\n    for p in _local.split(os.pathsep):\n        sys.path.insert(0, p)\nelif importlib.util.find_spec(\"peclet\") is None:\n    subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"-q\", \"peclet\"], check=True)\n```\n:::\n\n\n::: {#5f0a8a75 .cell execution_count=2}\n``` {.python .cell-code}\nimport math, time\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom peclet import dem, flow\n\nplt.rcParams.update({\"figure.dpi\": 130, \"font.size\": 10, \"axes.grid\": True,\n                     \"grid.alpha\": 0.3, \"axes.axisbelow\": True,\n                     \"figure.facecolor\": \"white\", \"savefig.bbox\": \"tight\"})\nBLUE, RED, GREY, GREEN, ORANGE = \"#1f77b4\", \"#d62728\", \"0.80\", \"#2ca02c\", \"#ff7f0e\"\nPRESS_CAP = 600\n```\n:::\n\n\n## 1. The packing: `peclet.dem` \u2192 an SDF\n\nSame idea as the [random packed bed](../random-packed-bed/index.qmd) page, with one change: the\nbox is periodic in $x$ and $y$ only and a flat SDF floor closes it below, so the grains **settle\nunder gravity into a real bed** instead of jamming in a triply periodic box. That gives the unit\ncell what it needs \u2014 a rough top surface for the liquid to land on, and a bottom it can drip off.\n\n::: {#packing .cell execution_count=3}\n``` {.python .cell-code}\ndef settle_bed(N=34, R=7.7, L=48.0, H=260.0, seed=5, dt=0.004, fall=9000, quench=4000):\n    \"\"\"A gravity-settled random packing of N spheres in a laterally periodic column.\"\"\"\n    from peclet.dem import build_wall_sdf\n    rng = np.random.default_rng(seed)\n    s = dem.Simulation(N)\n    s.initialize(shape_type=1, radius=R)\n    s.set_domain((0.0, 0.0, -R), (L, L, H))\n    s.enable_periodicity(True, True, False)          # periodic sides, a floor below\n    s.set_gravity(0.0, 0.0, -9.81)\n    s.set_material_params(0.1, 0.0, 0.35)            # restitution, cohesion, friction\n    s.set_solver_iterations(24, 8)\n    build_wall_sdf(lambda p: p[:, 2], ((0.0, 0.0, -R), (L, L, H)), resolution=32) \\\n        .add_to(s, restitution=0.1, friction=0.35)   # the floor: positive above z = 0\n    pos = np.zeros((N, 4), np.float32)\n    pos[:, 0] = rng.uniform(0, L, N); pos[:, 1] = rng.uniform(0, L, N)\n    pos[:, 2] = rng.permutation(np.linspace(R + 2, R + 2 + 4.0 * L, N)) + rng.normal(0, 2, N)\n    pos[:, 3] = 1.0                                  # inverse mass\n    s.set_positions(pos)\n    s.set_velocities(np.zeros((N, 3), np.float32))\n    for _ in range(fall):\n        s.step(dt)\n    # A zero-restitution quench alone does not come to rest: a grain that lands on top of the pile\n    # keeps rolling, and the packing is then reported with a residual velocity of order 1. Draining\n    # the kinetic energy directly -- zero the velocities, step, repeat -- turns the tail of the\n    # quench into pure position relaxation, and makes the settled POROSITY reproducible even though\n    # the GPU contact solve is not bit-reproducible (float atomics in the contact sum).\n    s.set_material_params(0.0, 0.0, 0.35)            # quench into the rigid contact network\n    zero = np.zeros((N, 3), np.float32)\n    for k in range(quench):\n        if k % 400 == 0 or k > quench - 200:\n            s.set_velocities(zero)\n        s.step(dt)\n    p = s.get_positions()[:, :3].astype(float)\n    p[:, 2] -= p[:, 2].min() - R                     # rest the lowest grain on z = 0\n    # the velocity ONE step regenerates from rest: a measure of the residual unbalanced force\n    return p, float(np.abs(s.get_velocities()).max())\n\nt0 = time.time()\nPOS, VREST = settle_bed()\nL48, R48 = 48.0, 7.7\nHBED = POS[:, 2].max() + R48\nPHI = len(POS) * (4 / 3) * math.pi * R48 ** 3 / (L48 * L48 * HBED)\nprint(f\"{len(POS)} spheres of radius {R48} cells; bed height {HBED:.2f} cells, \"\n      f\"solid fraction {PHI:.3f} (porosity {1 - PHI:.3f})\")\nprint(f\"velocity regenerated by one step from rest: {VREST:.1e}   ({time.time() - t0:.0f} s)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n34 spheres of radius 7.7 cells; bed height 51.07 cells, solid fraction 0.553 (porosity 0.447)\nvelocity regenerated by one step from rest: 4.6e-02   (27 s)\n```\n:::\n:::\n\n\nThirty-four equal spheres in a laterally periodic box three diameters wide is a *small* unit cell,\nand it shows: the settled bed is partly ordered rather than properly random (the 3-D still below\nmakes this obvious). That is a consequence of the cell size, not of the packing protocol, and it is\none of the limits at the end of the page.\n\nSampling the packing onto the flow grid gives the signed distance field \u2014 **positive in the\nfluid**, one `min` over the spheres and their lateral periodic images. Nothing else is solid: no\ncolumn wall, no floor.\n\n::: {#sdf .cell execution_count=4}\n``` {.python .cell-code}\nNX, NZ = 48, 96                 # the production grid; halve both for an 8x cheaper preview\nZBED0 = 22.0                    # bed base in cells: 22 below it to drain, ~21 above for the jet\n\ndef bed_sdf(nx, nz, pos, R):\n    ax = (np.arange(nx) + 0.5)[:, None, None]\n    ay = (np.arange(nx) + 0.5)[None, :, None]\n    az = (np.arange(nz) + 0.5)[None, None, :]\n    best = np.full((nx, nx, nz), 1e30)\n    for cx, cy, cz in pos:\n        for px in (-nx, 0, nx):                      # lateral periodic images\n            for py in (-nx, 0, nx):\n                best = np.minimum(best, np.sqrt((ax - (cx + px)) ** 2 + (ay - (cy + py)) ** 2\n                                                + (az - cz) ** 2) - R)\n    return np.asfortranarray(best)\n\ndef place(nx, nz):\n    \"\"\"Scale the DEM packing onto an nx x nx x nz grid and lift it onto the bed base.\"\"\"\n    sc = nx / L48\n    p = POS * sc\n    p[:, 2] += ZBED0 * (nz / 96.0)\n    return p, R48 * sc, ZBED0 * (nz / 96.0), ZBED0 * (nz / 96.0) + HBED * sc\n```\n:::\n\n\n## 2. The scene\n\n::: {#physics .cell execution_count=5}\n``` {.python .cell-code code-summary=\"The physical parameters, and where each number comes from\"}\n# Solver units: cell size 1, time in seconds. Only the dimensionless groups matter.\nRHO_L, MU_L = 100.0, 50.0        # the liquid\nMU_RATIO = 50.0                  # water/air is 55; this fixes the gas viscosity at both ratios\nBO = 1.2                         # water/air on 3 mm packing: 1.23\nTHETA = 60.0                     # a wetting solid\nDELTA_CELLS = 3.0                # the film thickness the inlet speed is sized on\nUMAX_CELLS = 0.3                 # the Nusselt surface speed of that film\nRD_CELLS = 8.0                   # distributor radius\n\ndef scene(nx, nz, ratio=100.0):\n    \"\"\"Every derived number of the case, at the grid resolution asked for.\"\"\"\n    sc = nx / L48\n    pos, R, z0, z1 = place(nx, nz)\n    dp = 2 * R                                        # sphere diameter, cells\n    rho_g, mu_g = RHO_L / ratio, MU_L / MU_RATIO\n    drho = RHO_L - rho_g\n    delta, umax = DELTA_CELLS * sc, UMAX_CELLS * sc\n    g = 2 * MU_L * umax / (drho * delta ** 2)         # invert eq-nusselt for the body force\n    sigma = drho * g * dp ** 2 / BO                   # then fix the Bond number\n    return dict(pos=pos, R=R, dp=dp, z0=z0, z1=z1, sc=sc, rho_g=rho_g, mu_g=mu_g, drho=drho,\n                delta=delta, umax=umax, g=g, sigma=sigma, rd=RD_CELLS * sc, ratio=ratio,\n                Ca=MU_L * umax / sigma, Re_f=RHO_L * umax * delta / MU_L)\n\nS0 = scene(NX, NZ)\nprint(f\"grid {NX}x{NX}x{NZ}   d_p = {S0['dp']:.2f} cells   bed z in \"\n      f\"[{S0['z0']:.1f}, {S0['z1']:.1f}]   distributor radius {S0['rd']:.1f} cells\")\nprint(f\"rho_l/rho_g = {RHO_L / S0['rho_g']:.0f}   mu_l/mu_g = {MU_RATIO:.0f}   \"\n      f\"sigma = {S0['sigma']:.4g}   g = {S0['g']:.5g}   u_max = {S0['umax']:.3g} cells/s\")\nprint(f\"Bo = {BO}   Ca = {S0['Ca']:.4g}   Re_film = {S0['Re_f']:.3g}   theta = {THETA:.0f} deg\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ngrid 48x48x96   d_p = 15.40 cells   bed z in [22.0, 73.1]   distributor radius 8.0 cells\nrho_l/rho_g = 100   mu_l/mu_g = 50   sigma = 658.8   g = 0.03367   u_max = 0.3 cells/s\nBo = 1.2   Ca = 0.02277   Re_film = 1.8   theta = 60 deg\n```\n:::\n:::\n\n\n::: {.callout-important}\n## Three settings that are not defaults \u2014 and two that now are\n`set_pressure_fcg` is selected **after** the density closure: `set_property_model(\"rho\", ...)`\nfires the solver's density-mode switch, which reselects the Chebyshev driver and silently discards\nan earlier choice. On a box with open boundaries at density ratio $\\ge 100$ Chebyshev *diverges*\nand MG-PCG burns any cap, while FCG converges \u2014 so the order of these two lines is load-bearing.\n`set_pressure_multigrid` gets an explicit depth and the velocity solve extra sweeps, as the\nvalidated open-boundary channel case does. **MG telescoping must stay off**: the telescope stage\ngathers inner cells only, so the outflow face plane does not survive the merge, and the solver\nrefuses the combination outright.\n\nWhat *is* a default since the variable-density outflow operator was fixed: the $1/\\rho_f$ outflow\ncorrection (`set_outflow_rho_correction`) and the exact pressure residual, which `enable_vof()`\nturns on. Together they are why the outlet divergence below reads $10^{-9}$ or smaller\nrather than $10^{-3}$.\n:::\n\n::: {#driver .cell execution_count=6}\n``` {.python .cell-code}\ndef trickle(nx=NX, nz=NZ, tend=420.0, ratio=100.0, ugas=0.0, probe=50, cap=PRESS_CAP,\n            max_steps=18000, snap_fracs=(0.10, 0.25, 0.45, 0.70, 1.00)):\n    \"\"\"One trickle-flow run, to physical time `tend`. `ugas` is the co-current gas inflow as a\n    fraction of u_max.\"\"\"\n    P = scene(nx, nz, ratio)\n    s = flow.Solver(nx, nx, nz)\n    s.set_rho(RHO_L); s.set_mu(MU_L)\n    for f in range(4):\n        s.set_domain_bc(f, 0, 0, 0, 0)               # periodic sides\n    s.set_domain_bc(4, 3, 0, 0, 0)                   # OUTFLOW at the bottom\n\n    xc = (np.arange(nx) + 0.5)[:, None]; yc = (np.arange(nx) + 0.5)[None, :]\n    disc = ((xc - nx / 2) ** 2 + (yc - nx / 2) ** 2) < P[\"rd\"] ** 2\n    prof = np.zeros((nx, nx, 3))\n    prof[:, :, 2] = np.where(disc, -P[\"umax\"], -ugas * P[\"umax\"])\n    s.set_domain_bc_profile(5, np.ascontiguousarray(prof))          # the distributor: velocity\n\n    s.set_velocity_solver_params(60)\n    s.set_pressure_multigrid(True, levels=6)\n    s.set_pressure_solver_params(80)\n    s.set_solid(bed_sdf(nx, nz, P[\"pos\"], P[\"R\"]), cutcell_pressure=True)   # the cut-cell IBM\n    s.enable_vof()\n    s.set_vof(np.zeros((nx, nx, nz), order=\"F\"))                    # the bed starts dry\n    s.set_surface_tension(P[\"sigma\"])\n    s.set_contact_angle(THETA)                                      # the whole wetting model\n    s.set_property_model(\"rho\", \"linear\", \"C\", [P[\"rho_g\"], RHO_L - P[\"rho_g\"]])\n    s.set_property_model(\"mu\", \"linear\", \"C\", [P[\"mu_g\"], MU_L - P[\"mu_g\"]])\n    # REDUCED gravity: the force acts on the liquid only, so the gas is exactly force-free and\n    # hydrostatic -- which is what a Dirichlet p = 0 outlet assumes. With gravity on the gas too,\n    # the outlet accelerates the whole gas column instead of supporting it: a different problem.\n    s.set_property_model(\"force_z\", \"linear\", \"C\", [0.0, -P[\"drho\"] * P[\"g\"]])\n    s.enable_vof_momentum(P[\"rho_g\"], RHO_L)\n    s.set_pressure_fcg(True, cap, 1e-11)                            # DRIVER LAST -- see above\n    s.set_vof_inflow_profile(5, np.ascontiguousarray(disc.astype(float)))   # ...and its colour\n    s.set_vof_backflow(4, 0.0)                                      # gas re-enters on backflow\n\n    eps = np.asarray(s.vof_geometry(0)).copy()          # cell fluid fraction\n    cut = (eps > 1e-9) & (eps < 1.0 - 1e-9)             # cells the grain surface passes through\n    zc = np.arange(nz) + 0.5\n    bed = (zc >= P[\"z0\"]) & (zc <= P[\"z1\"])\n    cutbed = cut & bed[None, None, :]\n    VB = float(eps[:, :, bed].sum())                    # void volume of the bed\n    za = min(nz - 1, int(round(P[\"z1\"] + 2)))                       # pressure probe planes:\n    zb = max(0, int(round(P[\"z0\"] - 2)))                            # open planes just off the bed\n\n    dt_cap = 0.5 * s.capillary_dt()\n    snap_t = [tend * f for f in snap_fracs]\n    hist, snaps = [], {}\n    t = 0.0; i = 0\n    it_max = capped = 0; div_max = drift = 0.0; b0 = None; cmin, cmax = 1.0, 0.0\n    t0 = time.time()\n    while t < tend and i < max_steps:\n        # dt is re-picked EVERY step from the solver's own two explicit limits. Every ten steps is\n        # not enough here: the jet impinging on the bed can double max|u_f| inside ten steps, and\n        # the Weymouth-Yue boundedness cap is a hard throw, not a warning.\n        lim = s.vof_step_limits()\n        dt = min(dt_cap, 0.4 * lim[\"cfl_dt\"]) if lim[\"cfl_dt\"] > 0 else dt_cap\n        s.set_dt(dt); s.step(); t += dt; i += 1\n        it = s.last_pressure_iterations()\n        it_max = max(it_max, it); capped += it >= cap\n        want_snap = bool(snap_t) and t >= snap_t[0]\n        if i % probe == 0 or want_snap or t >= tend:\n            d = s.vof_diagnostics()\n            tot = s.vof_bc_volumes_total()              # the ADVECTOR's own boundary fluxes\n            b = d[\"volume\"] - sum(tot)\n            if b0 is None:\n                b0 = b\n            drift = max(drift, abs(b - b0))\n            cmin, cmax = min(cmin, d[\"min\"]), max(cmax, d[\"max\"])\n            div = s.max_open_divergence_projected()     # NON-mutating -- see the note below\n            div_max = max(div_max, div)\n            C, p = s.get_vof(), np.asarray(s.get_p())\n            cd = s.contact_angle_diagnostics()\n            hist.append(dict(\n                step=i, t=t, dt=dt, iters=it, div=div, drift=drift, volume=d[\"volume\"],\n                beta=float((eps[:, :, bed] * C[:, :, bed]).sum()) / VB,     # liquid saturation\n                fw=float((C[cutbed] > 0.5).sum()) / max(int(cutbed.sum()), 1),\n                dp=float((eps[:, :, za] * p[:, :, za]).sum() / eps[:, :, za].sum()\n                         - (eps[:, :, zb] * p[:, :, zb]).sum() / eps[:, :, zb].sum()),\n                inflow=tot[5], outflow=-tot[4], solid=d[\"solid_sum\"],\n                clipped=d[\"clipped_volume\"], wisps=d[\"wisps\"],\n                contact_cells=cd[\"contact_cells\"], apparent=cd[\"mean_apparent_angle\"],\n                frame=C[:, nx // 2, :].astype(np.float32).copy()))          # for the movie\n            if want_snap:\n                snaps[round(snap_t.pop(0), 3)] = C.copy()\n    tot = s.vof_bc_volumes_total()\n    return dict(P=P, hist=hist, snaps=snaps, eps=eps, cut=cut, cutbed=cutbed, bed=bed, VB=VB,\n                C=s.get_vof(), nx=nx, nz=nz, steps=i, ugas=ugas, ratio=ratio, t=t,\n                drift=drift, it_max=it_max, capped=capped, div_max=div_max, cap=cap,\n                inflow=tot[5], outflow=-tot[4], cmin=cmin, cmax=cmax, wall=time.time() - t0,\n                eps_bed=float(eps[:, :, bed].mean()))\n```\n:::\n\n\n::: {.callout-note}\n## `max_open_divergence()` changes the run; `max_open_divergence_projected()` does not\nThe older diagnostic re-imposes the zero-gradient outflow face before measuring, which destroys\nthe projection's outflow correction \u2014 the mechanism by which mass leaves \u2014 and then reports the\ndivergence of a field the solver never used. Calling it inside a time loop therefore *changes the\nrun*, by three to four orders in the budget. On any domain with an outflow face, use the\nnon-mutating sibling, as the driver above does.\n:::\n\n## 3. The run\n\n::: {#run-base .cell execution_count=7}\n``` {.python .cell-code}\nTEND = 420.0     # physical seconds. The wetting front needs about 300 s to cross\n                 # the bed and reach the outlet; the rest is the plateau.\nbase = trickle(tend=TEND)\nprint(f\"ratio {base['ratio']:.0f}, gas at rest: {base['steps']} steps to t = {base['t']:.0f} s \"\n      f\"({base['wall'] / 60:.0f} min wall)\")\nprint(f\"  pressure {base['it_max']}/{base['cap']} iterations, capped steps {base['capped']};  \"\n      f\"max|div(open u)| (projected) {base['div_max']:.2e}\")\nprint(f\"  liquid injected {base['inflow']:.6g}, left {base['outflow']:.6g}, \"\n      f\"budget defect {base['drift']:.3e} = {base['drift'] / base['inflow']:.2e} relative\")\nprint(f\"  C in [{base['cmin']:.2e}, {base['cmax']:.10f}];  \"\n      f\"colour inside the grains {base['hist'][-1]['solid']:.1e}\")\n_cl = max(r[\"clipped\"] for r in base[\"hist\"])\nprint(f\"  cut-cell approximation tripwire: worst per-step clipped liquid volume {_cl:.2e} \"\n      f\"({_cl / base['hist'][-1]['volume']:.1e} of the liquid in the box); \"\n      f\"wisp cells {max(r['wisps'] for r in base['hist'])}\")\nprint(f\"  contact-angle band at the end: {base['hist'][-1]['contact_cells']} theta cells, \"\n      f\"mean locally measured apparent angle {base['hist'][-1]['apparent']:.1f} deg \"\n      f\"(prescribed {THETA:.0f})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nratio 100, gas at rest: 9151 steps to t = 420 s (11 min wall)\n  pressure 38/600 iterations, capped steps 0;  max|div(open u)| (projected) 2.05e-09\n  liquid injected 26208.8, left 6.2262e-24, budget defect 8.860e-10 = 3.38e-14 relative\n  C in [-4.24e-22, 1.0000000000];  colour inside the grains 0.0e+00\n  cut-cell approximation tripwire: worst per-step clipped liquid volume 0.00e+00 (0.0e+00 of the liquid in the box); wisp cells 212821\n  contact-angle band at the end: 5987 theta cells, mean locally measured apparent angle 134.7 deg (prescribed 60)\n```\n:::\n:::\n\n\nThe first thing to check is the one the run cannot fake. Nothing here depends on the physics being\nright: the budget, the pressure health and the boundedness of $C$ are properties of the\ndiscretisation, and if any of them failed the rest of the page would be void. They do not: the budget closes to\n3\\.4e\\-14 of the injected volume, the projection uses\n38 of its 600 allowed iterations, the outlet\ndivergence sits at 2\\.1e\\-09, the colour stays inside $[0, 1]$ (worst\nexcursion 4\\.2e\\-22), and the colour inside the\ngrains is **exactly** zero.\n\nTwo lines of that print deserve a note.\n\n**The cut-cell tripwire reads zero.** `clipped_volume` measures the one place the cut-cell transport\napproximates: where the interface crosses a grain wall inside a cell, the PLIC slab is reconstructed\non the whole cell and its swept volume multiplied by the face openness, rather than clipped against\nthe solid as well. Over 9151 steps, nothing had to be clipped back into\n$[0,1]$.\n\n**Almost every cell in the box is a wisp.** `wisps` counts cells whose colour is within $10^{-8}$ of\n0 or of 1 without being exactly there \u2014 here\n212 821 of the\n221 184 cells: the round-off wake\nof a geometric advection scheme, of order $10^{-20}$ per cell. It is harmless *because* the wisp\nguard is on \u2014 cells inside that band are treated as pure, so no PLIC normal is ever built from a\nstencil of $10^{-20}$ values, which is exactly the degeneracy that takes an emptying domain to\n`NaN`. The guard costs nothing in conservation: such a cell is fluxed algebraically at its actual\ncolour, and the budget above is the proof.\n\n::: {#cell-fig-panels .cell execution_count=8}\n``` {.python .cell-code}\nkeys = sorted(base[\"snaps\"])   # snapshot times\nP = base[\"P\"]\nsdf_mid = bed_sdf(base[\"nx\"], base[\"nz\"], P[\"pos\"], P[\"R\"])[:, base[\"nx\"] // 2, :]\nx = np.arange(base[\"nx\"]) + 0.5\nz = np.arange(base[\"nz\"]) + 0.5\nfig, axes = plt.subplots(1, len(keys), figsize=(2.05 * len(keys), 4.8), sharey=True)\nfor ax, k in zip(axes, keys):\n    C = base[\"snaps\"][k][:, base[\"nx\"] // 2, :]\n    ax.contourf(x, z, np.where((sdf_mid > 0) & (C > 0.02), C, np.nan).T,\n                levels=np.linspace(0, 1, 11), cmap=\"Blues\", vmin=0, vmax=1)\n    ax.contourf(x, z, (sdf_mid < 0).T.astype(float), levels=[0.5, 1.5], colors=[\"0.72\"])\n    for zz in (P[\"z0\"], P[\"z1\"]):\n        ax.axhline(zz, color=\"0.45\", lw=0.6, ls=\":\")\n    ax.plot([base[\"nx\"] / 2 - P[\"rd\"], base[\"nx\"] / 2 + P[\"rd\"]], [base[\"nz\"] - 0.4] * 2,\n            color=RED, lw=3.5, solid_capstyle=\"butt\")\n    h = min(base[\"hist\"], key=lambda r: abs(r[\"t\"] - k))\n    ax.set(xlim=(0, base[\"nx\"]), ylim=(0, base[\"nz\"]), aspect=\"equal\",\n           title=f\"$t = {h['t']:.0f}$ s\\n$\\\\beta = {h['beta']:.3f}$\", xlabel=\"x  [cells]\")\n    ax.grid(False)\naxes[0].set_ylabel(\"z  [cells]\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Mid-plane liquid fraction as the bed wets. Grey is solid, blue is liquid; the red bar at the top is the distributor and the dotted lines bound the bed. At this Bond number the liquid does not fall as a jet: it hangs from the distributor as a growing pendant body until it touches the packing, and then feeds the bed through that liquid bridge, spreading over the top layer and running down between the grains.](index_files/figure-html/fig-panels-output-1.png){#fig-panels}\n:::\n:::\n\n\n::: {#cell-fig-3d .cell execution_count=9}\n``` {.python .cell-code code-summary=\"3-D still (pyvista, off-screen)\"}\nimport pyvista as pv\npv.OFF_SCREEN = True\n\nnx, nz = base[\"nx\"], base[\"nz\"]\ngrid = pv.ImageData(dimensions=(nx, nx, nz), spacing=(1, 1, 1))\ngrid[\"sdf\"] = bed_sdf(nx, nz, P[\"pos\"], P[\"R\"]).flatten(order=\"F\")\ngrid[\"C\"] = base[\"C\"].flatten(order=\"F\")\ngrains = grid.contour([0.0], scalars=\"sdf\")\nliquid = grid.contour([0.5], scalars=\"C\")\n\npl = pv.Plotter(off_screen=True, window_size=(880, 980))\npl.background_color = \"white\"\npl.add_mesh(grains, color=\"#bfbfbf\", smooth_shading=True)\npl.add_mesh(liquid, color=\"#2b7bba\", opacity=0.95, smooth_shading=True)\npl.camera_position = [(nx * 3.2, -nx * 2.8, nz * 0.95), (nx / 2, nx / 2, nz * 0.48), (0, 0, 1)]\npl.camera.zoom(0.85)\npl.show()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n/tmp/ipykernel_1295856/4036978783.py:17: UserWarning: Using static image for notebook display.\nInstall trame for interactive backends: pip install \"pyvista[jupyter]\"\n  pl.show()\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![The packing at the end of the run: the grains (grey) with the liquid interface C = \u00bd on them (blue). The liquid does not coat the bed uniformly \u2014 it spreads over the top layer, picks a few paths down between the grains and leaves whole grains dry, which is exactly the wetting-efficiency problem a trickle bed is designed around. Note also how ordered the bed is: 34 equal spheres in a laterally periodic box three diameters wide partially crystallise, which is a small-unit-cell artefact rather than a property of packed beds.](index_files/figure-html/fig-3d-output-2.png){#fig-3d}\n:::\n:::\n\n\n<!-- MOVIE: an animation of the mid-plane colour field is written next to this page as\n     trickle-flow-packing.mp4 (git-ignored, see .gitignore). Upload it to YouTube and replace this\n     comment with the embed:\n     {{< video https://www.youtube.com/embed/XXXXXXXXXXX >}} -->\n\n::: {#movie .cell execution_count=10}\n``` {.python .cell-code code-summary=\"Write the mid-plane animation to an mp4 next to the page (not committed)\"}\nimport matplotlib.animation as animation\n\nframes = [r[\"frame\"] for r in base[\"hist\"]]\nfigm, axm = plt.subplots(figsize=(3.2, 6.0))\naxm.contourf(x, z, (sdf_mid < 0).T.astype(float), levels=[0.5, 1.5], colors=[\"0.72\"])\naxm.set(xlim=(0, base[\"nx\"]), ylim=(0, base[\"nz\"]), aspect=\"equal\", xlabel=\"x  [cells]\",\n        ylabel=\"z  [cells]\")\naxm.grid(False)\nart = {}\n\ndef draw(k):\n    for c in art.pop(\"c\", []):\n        c.remove()\n    cs = axm.contourf(x, z, np.where((sdf_mid > 0) & (frames[k] > 0.02), frames[k], np.nan).T,\n                      levels=np.linspace(0, 1, 11), cmap=\"Blues\", vmin=0, vmax=1)\n    axm.contourf(x, z, (sdf_mid < 0).T.astype(float), levels=[0.5, 1.5], colors=[\"0.72\"])\n    axm.set_title(f\"t = {base['hist'][k]['t']:.0f} s\")\n    art[\"c\"] = cs.collections if hasattr(cs, \"collections\") else [cs]\n    return art[\"c\"]\n\ntry:\n    anim = animation.FuncAnimation(figm, draw, frames=range(0, len(frames), 2), blit=False)\n    anim.save(\"trickle-flow-packing.mp4\", fps=20, dpi=110)\n    print(f\"wrote trickle-flow-packing.mp4 ({len(frames) // 2} frames)\")\nexcept Exception as e:                       # no ffmpeg on the machine rendering the site\n    print(f\"movie skipped: {e}\")\nplt.close(figm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nwrote trickle-flow-packing.mp4 (94 frames)\n```\n:::\n:::\n\n\n## 4. The colour budget\n\nThe geometric transport carries $\\varepsilon_i C_i$ and every flux is the openness-weighted\n$o_f F_f$, so the flux sum telescopes exactly and\n\n$$\n\\sum_i \\varepsilon_i C_i(t) \\;-\\; \\int_0^t \\! Q_{\\text{in}} \\,\\mathrm{d}t' \\;+\\;\n\\int_0^t \\! Q_{\\text{out}} \\,\\mathrm{d}t' \\;=\\; \\text{const}\n$$ {#eq-budget}\n\nmust hold to round-off, with $Q_{\\text{in}}$ and $Q_{\\text{out}}$ the **advector's own** boundary\nface fluxes (`vof_bc_volumes_total()`) rather than a re-integration of the velocity field. The\nfloor of the identity is the projection's divergence residual. This is the strongest statement the\npage makes, because it holds *through a solid*, *through a partially covered inlet* and *through an\noutlet that both loses liquid and takes gas back in* \u2014 three code paths that only meet in a case\nlike this one.\n\n::: {#cell-fig-budget .cell execution_count=11}\n``` {.python .cell-code}\nh = base[\"hist\"]\ntt = np.array([r[\"t\"] for r in h])\nfig, (a0, a1) = plt.subplots(1, 2, figsize=(9.4, 3.4))\na0.plot(tt, [r[\"inflow\"] for r in h], color=BLUE, lw=1.8, label=\"injected (distributor)\")\na0.plot(tt, [r[\"outflow\"] for r in h], color=RED, lw=1.8, label=\"left (outlet)\")\na0.plot(tt, [r[\"volume\"] for r in h], color=GREEN, lw=1.8, label=r\"held: $\\sum \\varepsilon C$\")\na0.plot(tt, [r[\"inflow\"] - r[\"outflow\"] for r in h], \"--\", color=\"0.35\", lw=1.2,\n        label=\"in $-$ out\")\na0.set(xlabel=\"t  [s]\", ylabel=\"liquid volume  [cells$^3$]\", title=\"the three terms of the budget\")\na0.legend(fontsize=8)\na1.semilogy(tt, np.maximum([r[\"drift\"] / max(r[\"inflow\"], 1e-30) for r in h], 1e-18), color=BLUE,\n            lw=1.8, label=\"budget defect / injected\")\na1.semilogy(tt, np.maximum([r[\"div\"] for r in h], 1e-18), color=ORANGE, lw=1.4,\n            label=r\"$\\max|\\nabla\\!\\cdot\\!(o\\,\\mathbf{u})|$, projected\")\na1.set(xlabel=\"t  [s]\", ylabel=\"magnitude\", title=\"both at the round-off floor\")\na1.legend(fontsize=8, loc=\"lower right\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The colour budget over the run. Left: liquid injected through the distributor, liquid that has left through the outlet, and the liquid held in the box; the three close on each other. Right: the running budget defect relative to the injected volume, against the outlet's own divergence residual \u2014 both at round-off.](index_files/figure-html/fig-budget-output-1.png){#fig-budget}\n:::\n:::\n\n\nThe three curves in the left panel are three independent accountings of the same liquid \u2014 the\ninlet's own flux ledger, the outlet's, and a sum over the field \u2014 and they close on each other for\nthe whole run. The outlet's ledger is the flat one: at the end of the run it stands at\n6\\.23e\\-24, i.e. **nothing has left the domain yet** \u2014 so what the budget\nis testing here is that a colour field pushed through a partially covered inlet and through a\npacking loses nothing on the way. The right panel is the statement in one number.\n\n## 5. Holdup, wetted area, pressure drop\n\nThree functionals, all measured on the bed region (the grains' bounding slab, dotted in the panels\nabove):\n\n- **Liquid saturation** $\\beta = \\sum_{\\text{bed}} \\varepsilon C \\big/ \\sum_{\\text{bed}}\n  \\varepsilon$ \u2014 the fraction of the *pore* volume the liquid occupies. Multiply by the bed\n  porosity $\\varepsilon_{\\text{bed}}$ for the holdup per unit *bed* volume, the other convention in\n  the literature.\n- **Wetted fraction** $f_w$ \u2014 of the cut cells in the bed (the cells the grain surface passes\n  through), the fraction whose colour is above $\\tfrac12$. It is a proxy for the wetted-area\n  fraction, biased by the cells' unequal share of surface, and it is quoted as a proxy.\n- **Pressure drop** across the bed: $\\langle p \\rangle$ on a plane two cells above the grains minus\n  the same two cells below, each averaged with the cell fluid fraction as the weight. Because the\n  body force acts on the liquid only, this $\\Delta p$ is the *frictional* drop plus the static head\n  of the liquid the bed is holding, $\\Delta\\rho\\, g \\int \\varepsilon C\\,\\mathrm{d}z$; both are\n  reported.\n\n::: {#cell-fig-functionals .cell execution_count=12}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 3, figsize=(10.8, 3.2))\nfor ax, key, lab, col in ((axes[0], \"beta\", r\"liquid saturation $\\beta$\", BLUE),\n                          (axes[1], \"fw\", r\"wetted cut-cell fraction $f_w$\", GREEN),\n                          (axes[2], \"dp\", r\"$\\Delta p$ across the bed\", RED)):\n    ax.plot(tt, [r[key] for r in h], color=col, lw=1.8)\n    ax.set(xlabel=\"t  [s]\", ylabel=lab)\naxes[2].axhline(0, color=\"0.5\", lw=0.8)\nplt.show()\n\ndef pct(a, b):\n    \"\"\"Relative change, in per cent, that survives a zero baseline.\"\"\"\n    return (b - a) / abs(a) * 100 if a else float(\"nan\")\n\n\ndef plateau(run, key, frac=0.25):\n    hh = run[\"hist\"]; n = max(2, int(len(hh) * frac))\n    v = np.array([r[key] for r in hh[-n:]])\n    return float(v.mean()), float(v.std())\n\nfor k, lab in ((\"beta\", \"liquid saturation beta\"), (\"fw\", \"wetted cut-cell fraction\"),\n               (\"dp\", \"pressure drop across the bed\")):\n    m, sd = plateau(base, k)\n    print(f\"  {lab:34s} {m:10.4f}  +- {sd:.4f}  (mean +- s.d. over the last quarter)\")\nBETA, _ = plateau(base, \"beta\")\nDPB, _ = plateau(base, \"dp\")\nHEAD = base[\"P\"][\"drho\"] * base[\"P\"][\"g\"] * BETA * base[\"eps_bed\"] * (base[\"P\"][\"z1\"] - base[\"P\"][\"z0\"])\nprint(f\"\\n  bed porosity {base['eps_bed']:.3f} -> holdup per bed volume \"\n      f\"{BETA * base['eps_bed']:.4f}\")\nprint(f\"  static head of that holdup: {HEAD:.3f};  measured Delta p {DPB:.3f};  \"\n      f\"frictional remainder {DPB - HEAD:.3f}\")\n```\n\n::: {.cell-output .cell-output-display}\n![The three trickle-bed functionals against time. Nothing happens for the first two minutes while the pendant body grows on the distributor; then it bridges to the packing and all three climb, and they are still climbing when the run stops. This is the filling transient of a bed fed faster than its films drain \u2014 not a steady operating point. The saw-tooth on the pressure drop reads as individual rivulets forming and detaching.](index_files/figure-html/fig-functionals-output-1.png){#fig-functionals}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n  liquid saturation beta                 0.2982  +- 0.0229  (mean +- s.d. over the last quarter)\n  wetted cut-cell fraction               0.1462  +- 0.0135  (mean +- s.d. over the last quarter)\n  pressure drop across the bed          34.6544  +- 22.6106  (mean +- s.d. over the last quarter)\n\n  bed porosity 0.443 -> holdup per bed volume 0.1322\n  static head of that holdup: 22.511;  measured Delta p 34.654;  frictional remainder 12.144\n```\n:::\n:::\n\n\nRead these as **filling curves, not plateaus.** For the first two minutes or so nothing happens in\nthe bed at all: the liquid hangs from the distributor as a growing pendant body \u2014 at this Bond number\nthe disc is *below* the detachment size, so it does not drip \u2014 until it reaches the packing and\nbridges to it. The front then enters the bed, and the saturation,\nthe wetted fraction and the pressure drop climb together \u2014 and they are still climbing when the run\nstops at $t =$ 420 s, with nothing returned at the outlet. Two things follow, and both are worth more than a plateau would have been:\n\n- **The liquid load is above what this bed drains.** The distributor delivers a fixed\n  $u_{\\max}\\,\\pi r_d^2$; a film of thickness $\\delta$ on a vertical wall carries\n  $\\Delta\\rho g \\delta^3/3\\mu_\\ell$ per unit width of wetted contour, and multiplying that by the\n  grain contour a horizontal cut of this packing offers gives a drainage capacity of the *same\n  order* as the feed. A bed fed at its drainage capacity does not reach a trickle steady state; it\n  accumulates, which is precisely what the curves show and what a trickle-bed operator calls\n  approaching flooding. Reaching a trickle steady state means either a smaller distributor or a much\n  longer run; the second is what the GPU budget for this page did not allow, and the first is the\n  first thing to change if you adapt it.\n- **The numbers quoted below are therefore levels at a common time**, not converged holdups. Since\n  every run on this page is stopped at the same physical time, from the same dry initial condition,\n  on the same packing, the comparisons between them are still controlled \u2014 which is what the next\n  three sections use them for.\n\nThe wetted fraction climbs with the saturation but stays well below it: the liquid does not spread\nover the whole grain surface, it selects paths \u2014 which is the wetting-efficiency problem the 3-D\nstill shows directly.\n\nOne diagnostic in the run print above says the same thing from the wall's side. The contact-angle\nband census reports a *mean locally measured apparent angle* far above the prescribed 60\u00b0 \u2014 the\nsolver imposes 60\u00b0 on the band, but the angle the interface actually presents while a front is\nadvancing over a dry grain is not the equilibrium angle, and a static model has no term that would\nmake it one. That gap is the honest signature of a moving contact line under a static angle, and\nclosing it is what the dynamic Cox\u2013Voinov rung is for (see the limits).\n\n### The same case at half resolution {#sec-half}\n\nThree more runs follow \u2014 a co-current gas stream, density ratio 1000, and this one \u2014 and three\n$48\\times48\\times96$ runs do not fit on a shared GPU. They are therefore run on a grid with every\nlength halved, and *this* run is the control that makes them readable: the same case as above, so\nthe difference between the two columns is discretisation and nothing else. The sphere diameter\ndrops from 15\\.4 cells to about 7\\.7 and the\nfilm from three cells to one and a half, while the Bond and Capillary numbers stay exactly where\nthey are \u2014 they are built from the scaled lengths. Do not read the two columns as a convergence\nstudy: two grids give a difference, not an order, and the difference is the honest error bar.\n\n::: {#run-half .cell execution_count=13}\n``` {.python .cell-code}\nhalf = trickle(nx=NX // 2, nz=NZ // 2, tend=TEND)\nprint(f\"half resolution: {half['steps']} steps, pressure {half['it_max']}/{half['cap']}, \"\n      f\"capped {half['capped']}, max|div| {half['div_max']:.2e}, \"\n      f\"budget {half['drift'] / half['inflow']:.2e} relative\")\nprint(f\"  {'':20s}{'48 x 48 x 96':>14s}{'24 x 24 x 48':>14s}{'change':>12s}\")\nfor lab, k in ((\"saturation beta\", \"beta\"), (\"wetted fraction\", \"fw\"), (\"pressure drop\", \"dp\")):\n    a, _ = plateau(base, k); b, _ = plateau(half, k)\n    print(f\"  {lab:20s}{a:14.4f}{b:14.4f}{pct(a, b):11.1f} %\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nhalf resolution: 5485 steps, pressure 48/600, capped 0, max|div| 8.09e-11, budget 6.49e-14 relative\n                        48 x 48 x 96  24 x 24 x 48      change\n  saturation beta             0.2982        0.3034        1.7 %\n  wetted fraction             0.1462        0.1526        4.4 %\n  pressure drop              34.6544       31.7604       -8.4 %\n```\n:::\n:::\n\n\n::: {#cell-fig-half .cell execution_count=14}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 2, figsize=(7.6, 3.2))\nfor ax, key, lab in ((axes[0], \"beta\", r\"liquid saturation $\\beta$\"),\n                     (axes[1], \"fw\", r\"wetted cut-cell fraction $f_w$\")):\n    for run, col, name in ((base, BLUE, f\"${NX}^2\\\\times{NZ}$\"),\n                           (half, GREEN, f\"${NX // 2}^2\\\\times{NZ // 2}$\")):\n        ax.plot([r[\"t\"] for r in run[\"hist\"]], [r[key] for r in run[\"hist\"]], color=col, lw=1.7,\n                label=name)\n    ax.set(xlabel=\"t  [s]\", ylabel=lab)\naxes[0].legend(fontsize=8)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Liquid saturation and wetted fraction at the production resolution and at half of it. Both grids see the same bed and the same dimensionless numbers; what separates the curves is discretisation, and its size is the error bar to attach to every functional on this page.](index_files/figure-html/fig-half-output-1.png){#fig-half}\n:::\n:::\n\n\nThe two grids see the same bed, the same distributor and the same dimensionless numbers, so\nwhatever separates the columns is discretisation. Two mechanisms pull in opposite directions and\nneither is small: the thinnest structure either grid can carry is about the same number of *cells*,\nso the coarse grid's minimum film is twice as thick in units of the fine grid and tends to hold and\nspread **more** liquid; while its throats are resolved by half as many cells, which changes what\nthey cost the flow \u2014 and the pressure drop, set by exactly those throats, is the least trustworthy\nof the three functionals for that reason. Which mechanism wins is not something to read off a\nsingle pair of runs. Take the spread as the error bar on every functional here \u2014 measured on this\nrun,\n2 % on the holdup,\n4 % on the wetted fraction\nand 8 % on the pressure\ndrop.\n\n## 6. Does a co-current gas stream change anything? {#sec-gas}\n\nSo far the gas has been at rest: the part of the inlet face outside the distributor prescribes zero\nvelocity, so gas moves only because the liquid drags it. A real trickle bed runs gas **down** the\ncolumn together with the liquid. The change is one line \u2014 the annulus of the inlet profile carries\na downward velocity at $C = 0$ \u2014 and everything else, the packing included, is identical. Both\ncolumns below are the half-resolution grid, against the control of the previous section.\n\n::: {#run-gas .cell execution_count=15}\n``` {.python .cell-code}\ngas = trickle(nx=NX // 2, nz=NZ // 2, tend=TEND, ugas=0.25)   # a quarter of the liquid speed\nprint(f\"co-current gas at {gas['ugas']:.2f} u_max: pressure {gas['it_max']}/{gas['cap']}, \"\n      f\"capped {gas['capped']}, max|div| {gas['div_max']:.2e}, \"\n      f\"budget {gas['drift'] / gas['inflow']:.2e} relative\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nco-current gas at 0.25 u_max: pressure 46/600, capped 0, max|div| 9.96e-11, budget 2.23e-14 relative\n```\n:::\n:::\n\n\n::: {#cell-fig-gas .cell execution_count=16}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 3, figsize=(10.8, 3.2))\nfor ax, key, lab in ((axes[0], \"beta\", r\"$\\beta$\"), (axes[1], \"fw\", r\"$f_w$\"),\n                     (axes[2], \"dp\", r\"$\\Delta p$\")):\n    for run, col, name in ((half, BLUE, \"gas at rest\"), (gas, ORANGE, \"co-current gas\")):\n        ax.plot([r[\"t\"] for r in run[\"hist\"]], [r[key] for r in run[\"hist\"]], color=col, lw=1.7,\n                label=name)\n    ax.set(xlabel=\"t  [s]\", ylabel=lab)\naxes[0].legend(fontsize=8)\nplt.show()\n\nprint(f\"  {'':20s}{'gas at rest':>14s}{'co-current':>14s}{'change':>12s}\")\nfor k, lab in ((\"beta\", \"saturation beta\"), (\"fw\", \"wetted fraction\"), (\"dp\", \"pressure drop\")):\n    a, _ = plateau(half, k); b, _ = plateau(gas, k)\n    print(f\"  {lab:20s}{a:14.4f}{b:14.4f}{pct(a, b):11.1f} %\")\n```\n\n::: {.cell-output .cell-output-display}\n![Gas at rest against a co-current gas stream at a quarter of the liquid inlet speed, both on the half-resolution grid: liquid saturation, wetted fraction and the pressure drop across the bed.](index_files/figure-html/fig-gas-output-1.png){#fig-gas}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n                         gas at rest    co-current      change\n  saturation beta             0.3034        0.3252        7.2 %\n  wetted fraction             0.1526        0.1765       15.7 %\n  pressure drop              31.7604       85.5826      169.5 %\n```\n:::\n:::\n\n\nBoth signs in that table are the ones trickle-bed correlations give: holdup and pressure drop\n**increase** with gas load in the trickle regime, because a co-current stream drags liquid down the\ncolumn and presses it into the pore space instead of blowing it out. Here the response is very\nunevenly distributed between the three \u2014 the holdup moves by\n\\+7 %, the wetted fraction by\n\\+16 %, and the pressure drop by\n\\+169 % \u2014 and the size of that last\nnumber is a reminder that at this Capillary number the interfaces are far stiffer than a real\nbed's, so the gas has to work much harder to get past them. The pressure solve works harder too\n(46 iterations against 48 with the gas at\nrest, both under the cap of 600), and the budget still closes to\n2\\.2e\\-14 of the injected volume.\n\n\n\n\n## 7. Density ratio 1000 {#sec-ratio1000}\n\nWater and air are a factor 1000 apart, not 100. Everything so far is at 100, because that is where\nthe solver's momentum-consistent transport is unambiguously validated. Ratio 1000 is where the\nhonest reporting starts, so it gets its own run \u2014 again on the half-resolution grid, against the\nsame control.\n\n::: {#run-1000 .cell execution_count=17}\n``` {.python .cell-code}\nr1000 = trickle(nx=NX // 2, nz=NZ // 2, tend=TEND, ratio=1000.0)\nprint(f\"ratio {r1000['ratio']:.0f}: pressure {r1000['it_max']}/{r1000['cap']}, \"\n      f\"capped {r1000['capped']}, max|div| {r1000['div_max']:.2e}\")\nprint(f\"  budget defect {r1000['drift'] / r1000['inflow']:.2e} relative, \"\n      f\"C in [{r1000['cmin']:.2e}, {r1000['cmax']:.10f}]\")\nprint(f\"  {'':20s}{'ratio 100':>14s}{'ratio 1000':>14s}{'change':>12s}   (both half res)\")\nfor k, lab in ((\"saturation beta\", \"beta\"), (\"wetted fraction\", \"fw\"), (\"pressure drop\", \"dp\")):\n    a, _ = plateau(half, lab); b, _ = plateau(r1000, lab)\n    print(f\"  {k:20s}{a:14.4f}{b:14.4f}{pct(a, b):11.1f} %\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nratio 1000: pressure 63/600, capped 0, max|div| 4.78e-11\n  budget defect 8.22e-14 relative, C in [-2.82e-22, 1.0000000000]\n                           ratio 100    ratio 1000      change   (both half res)\n  saturation beta             0.3034        0.3056        0.7 %\n  wetted fraction             0.1526        0.1539        0.8 %\n  pressure drop              31.7604       30.8907       -2.7 %\n```\n:::\n:::\n\n\nThe machinery does not care: the budget closes to\n8\\.2e\\-14, the colour stays inside $[0, 1]$, the\nprojection converges in 63 of its 600 allowed\niterations and the outlet divergence stays at 4\\.8e\\-11 \u2014 the same four\nstatements as at ratio 100, at ten times the density contrast, on a box\nwith an open inlet and an open outlet, which is the configuration that used to cap every pressure\ndriver whatever it was given.\n\nThe functionals themselves move, and by how much is in the table. Do not over-read it in either\ndirection. The bed is stochastic \u2014 the DEM packing is not bit-reproducible \u2014 and a rivulet network\nis chaotic, so the spread between two *nominally identical* configurations is of the same size as\nthe effect being looked for; the two-grid comparison of the previous section is the calibration for\nthat. What licenses or forbids reading physics out of the ratio-1000 column is not this table but\nthe box below.\n\n\n\n\n::: {.callout-warning}\n## What the solver's own gates say about ratio 1000 on an open boundary\nTwo measurements bound the trust to put in the ratio-1000 column. The good one: a Nusselt falling\nfilm with an open inlet and an open outlet reproduces the analytical flow rate to **+0.21 %** at\nratio 1000 just as at 100, in 64 pressure iterations, with the outlet divergence at\n$2\\times10^{-12}$ \u2014 so the *boundary machinery* is sound at that ratio. The bad one: a resting\nliquid pool with a gas stream blown over it, at the same ratio, loses $10^{-3}$ of its volume in\n500 steps and picks up **3 % of the gas inlet speed** where it should pick up nothing. That is a\nspurious-current / momentum-consistency defect, not an outflow-operator one, and it is the sharpest\nopen two-phase item in the solver. A trickle bed is closer to the second configuration than to the\nfirst: the *conservation* of the ratio-1000 column is exact, the *velocities* in the thin liquid\nstructures carry that defect, and no quantitative physical claim is made from them here.\n:::\n\n## 8. Resolution and limits {#sec-limits}\n\n**The Capillary number is set by the grid, not by a choice.** For a film of thickness $\\delta$ fed\nat the Nusselt speed on a grain of diameter $d_p$, @eq-groups and @eq-nusselt combine into\n\n$$\n\\mathrm{Ca} \\;=\\; \\frac{\\mu_\\ell u_{\\max}}{\\sigma}\n   \\;=\\; \\frac{\\mathrm{Bo}}{2}\\left(\\frac{\\delta}{d_p}\\right)^{\\!2} ,\n$$ {#eq-ca}\n\nwith $\\mu_\\ell$, $g$ and $\\sigma$ all cancelling. So once the Bond number is fixed at its physical\nvalue, the Capillary number is fixed by **one geometric ratio**: how thin the film is compared with\nthe grain. A geometric VoF cannot carry a film thinner than about three cells, and the grains here\nare 15\\.4 cells across, so the smallest $\\delta/d_p$ this grid can express is\nabout 0.2 \u2014 and the Capillary number that goes with it is the\n0\\.023 printed above. A water/air trickle bed runs at\n$\\delta/d_p \\sim 10^{-2}$, i.e. $\\mathrm{Ca}\\sim 10^{-4}$ \u2014 three orders lower. Recovering those\nthree orders means lowering $\\delta/d_p$ by a factor $\\sim\\!30$, i.e. resolving each grain with\n$\\sim\\!500$ cells instead of 15, which costs a factor\n$\\sim\\!3\\times10^{4}$ in cells for the same bed. That is the honest scope of this page: **the Bond number is physical, the\nCapillary number is a grid artefact, and no amount of parameter tuning changes that** \u2014 only\nresolution does. What the page therefore shows is the *structure* of trickle flow (films, rivulets,\npartial wetting, a holdup that saturates) at a Capillary number two to three orders too high, not a\npredicted holdup for a named system.\n\n**The other limits, briefly:**\n\n- **The contact angle is static.** A real rivulet on a grain pins on defects and advances and\n  recedes at different angles, which is what makes rivulets *stay* where they are. The solver has\n  the Cox\u2013Voinov dynamic angle and advancing/receding hysteresis\n  (`set_contact_angle_dynamic`, `set_contact_angle_hysteresis`), and switching them on is a\n  one-line change to the driver \u2014 but a dynamic-wetting result must state its slip length, and\n  calibrating that is a page of its own.\n- **The cut-cell flux is an approximation where the interface crosses a grain.** The PLIC\n  polyhedron is reconstructed on the whole cell and its swept volume multiplied by the face\n  openness, rather than clipped against the solid too. It is conservative either way and exact\n  where the interface and the wall are parallel or the cell is whole; where they cross, the\n  *distribution* of liquid inside that cell is O(1) wrong. `vof_diagnostics()[\"clipped_volume\"]`\n  is the tripwire and it is printed with the run above.\n- **The wetted fraction is a cut-cell count, not an area integral.** Cells carry unequal shares of\n  the grain surface, so $f_w$ is a proxy \u2014 good for a trend and for comparing two runs on the same\n  packing, not for an absolute wetting efficiency.\n- **No steady state.** Every functional is a level at the end of a fixed-length run on a bed that\n  is still filling (section 5). The comparisons are same-time comparisons on the same packing from the same dry\n  start, which is a controlled experiment; the absolute holdup is not a converged operating point\n  and should not be read against a correlation.\n- **The bed is partly ordered.** 34 equal spheres in a periodic box three diameters wide settle\n  into something closer to a lattice than to a random packing. A random bed's throat-size\n  distribution is much wider, and it is the narrow throats that decide where liquid goes \u2014 so the\n  *paths* here are cleaner than a real bed's. Widening the cell is the fix, and it costs cells.\n- **One packing, one seed.** 34 grains is a unit cell, not a statistical sample. Every number here\n  belongs to *this* bed; the spread over packings is not measured. The DEM packing is also not\n  bit-reproducible \u2014 the GPU contact solve sums float contributions atomically \u2014 so re-running the\n  first cell gives a slightly different bed.\n- **Resolution.** The half-resolution control in [section 5](#sec-half) is the size of the\n  discretisation error to attach to every functional here. It is a control, not a convergence\n  study: two grids give a difference, not an order.\n\n## Collocated cross-check\n\npeclet's cell-centred solver (`flow.SolverColocated`) runs two-phase flow since rung V8 \u2014\nvariable density in the approximate projection, surface tension as a face acceleration \u2014 and the\n[parasitic currents](../parasitic-currents/index.qmd) and\n[capillary oscillations](../capillary-oscillations/index.qmd) pages carry that column.\n\n**This page cannot have one, and the reason is the solid.** The collocated two-phase path is\n**all-fluid**: the openness-weighted cut-cell colour transport, the solid-band fill and the\ncontact-angle plane this page is built on exist on the staggered grid only. The composition is\nrefused rather than silently approximated:\n\n::: {#colocated-scope .cell execution_count=18}\n``` {.python .cell-code}\npos32, R32, _, _ = place(32, 32)\nsc32 = flow.SolverColocated(32, 32, 32)\nsc32.set_rho(1.0); sc32.set_mu(0.1)\nsc32.set_solid(bed_sdf(32, 32, pos32, R32), cutcell_pressure=True)   # single-phase: accepted\ntry:\n    sc32.enable_vof()\n    print(\"enable_vof() succeeded\")\nexcept RuntimeError as e:\n    print(f\"enable_vof() raised RuntimeError:\\n  {e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nenable_vof() raised RuntimeError:\n  enable_vof: geometric VoF on SolverColocated (rung V8) is ALL-FLUID only \u2014 an immersed solid needs the cut-cell face acceleration and the matching one-sided closures, which is a later rung. Use the staggered Solver (rung V5a supports cut cells).\n```\n:::\n:::\n\n\nEvery number on this page is a **staggered** number.\n\n## Adapt this yourself\n\n- **Change the wettability.** `set_contact_angle(120)` makes the grains non-wetting, and the\n  liquid should stop filming and start channelling; `set_contact_angle_field(theta)` takes a\n  per-cell angle, so a partially poisoned catalyst is one array away. This is the cheapest\n  interesting experiment on the page.\n- **Change the distributor.** The inlet is two arrays \u2014 a velocity profile and a colour profile.\n  Two point sources instead of one central disc, an annulus, a full-face rain: all of them are a\n  change to `disc` and nothing else. Maldistribution *is* the geometry of that array.\n- **Change the flow rate.** `UMAX_CELLS` sets the Nusselt inlet speed; the body force follows from\n  @eq-nusselt and $\\sigma$ from `BO`, so the Capillary number stays put and only the liquid load\n  moves. That sweep is the holdup-versus-flow-rate curve.\n- **Wet the bed first.** `set_vof(C0)` with a pre-filled pore space and no inflow gives the\n  *draining* problem \u2014 residual holdup \u2014 instead of the wetting one.\n- **Put a column wall on it.** An SDF slab pair `min`-ed into the packing SDF at a\n  **quarter**-integer coordinate. The sides then stop being periodic, and the wall film and wall\n  channelling appear: the laboratory-column problem rather than the unit cell.\n- **Go multi-rank.** The identical script runs under `mpirun -np N python \u2026`. The cut-cell colour\n  transport, the contact-angle band fill and the boundary ledger are all decomposition-independent\n  and gated at np = 1/2/4 with the block cut going through the inlet plane, the outlet plane and\n  the packing.\n\n## Reproduce this\n\nThe compiled solver runs this, so its outputs are **frozen** into the site. To regenerate:\n\n```bash\npip install peclet            # the solver, from PyPI\nquarto render examples/trickle-flow-packing/index.qmd --execute\n# ...or against a local source build of the suite (GPU):\nPECLET_LOCAL_BUILD=/path/to/suite/flow/build_cuda:/path/to/suite/dem/build_cuda \\\n  OMP_NUM_THREADS=8 OMP_PROC_BIND=false \\\n  quarto render examples/trickle-flow-packing/index.qmd --execute\n```\n\nThe machinery this page composes is gated inside the solver repo by `tests/kokkos/test_vof_bc.cpp`\n(the colour budget through an inlet and an outlet, and the composed packing-plus-boundary scene),\n`tests/kokkos/test_vof_cutcell.cpp` (conservation through a solid),\n`tests/kokkos/test_vof_wetting.cpp` (the contact-angle fill), their MPI twins at np = 1/2/4, and\nthe physics studies `tests/study/vof_open_boundaries.py` (the Nusselt film and the gas-over-pool\ncase quoted above) and `tests/study/vof_wetting.py`.\n\n", "supporting": ["index_files"], "filters": [], "includes": {}}}