{
  "hash": "7560d81b562fbb6d825c7ad94a21cac6",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Parasitic currents: a balanced-force VoF at machine zero\"\nsubtitle: \"A droplet that should not move. What makes it move, by how much, and which single line of the discretization decides.\"\nauthor: \"Peclet\"\ndate: \"2026-09-02\"\ncategories: [flow, vof, two-phase, surface-tension, verification]\njupyter: python3\n---\n\n\n\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/computational-chemical-engineering/peclet-examples/blob/main/examples/parasitic-currents/index.ipynb){target=\"_blank\"}\n&nbsp;Runs on a free Colab CPU runtime, slowly; the $64^3$ rungs want a GPU build.\n\n## What you'll learn\n\nEvery volume-of-fluid code with surface tension has a signature disease: a droplet\nsitting in a quiescent fluid, in perfect mechanical equilibrium, spins up a\nvortex ring and never stops. These **parasitic** (or *spurious*) **currents** are\nthe standard health check of a two-phase solver, and they are almost never a\nsurface-tension bug — they are a statement about which discrete operators were\npaired with which.\n\nThis page measures peclet's geometric VoF against that check three ways:\n\n1. With an **exact** curvature the spurious velocity is **machine zero** — not\n   small, *zero to round-off*, at every resolution. The balanced-force\n   construction [@francois2006; @popinet2009] is an algebraic identity, and we\n   show it holding to $2\\times10^{-17}$.\n2. Flip one operator (`set_csf_mode(1)` — the \"obvious\" cell-centred\n   $\\sigma\\kappa\\nabla C$, face-interpolated) and the same run reads\n   $5.8\\times10^{-2}$. That is a factor $3\\times10^{15}$, and it is the\n   literature's \"naive CSF gives $\\sim10^{-2}$\" reproduced as a switch.\n3. With the **computed** curvature what is left is the curvature error and\n   nothing else: the spurious capillary number falls at second order, from\n   $\\mathrm{Ca}=2.5\\times10^{-4}$ at 8 cells per diameter to\n   $1.4\\times10^{-5}$ at 32.\n\nPlus the one guard that makes the whole thing survive transport: a wisp\nthreshold on the interfacial predicate, without which the round-off colour\nresidue Weymouth–Yue leaves behind returns curvatures of $10^{11}$ and the\ncurrents stop decaying.\n\n**The conclusion to carry away:** in this solver the surface-tension force\ndiscretization is *exact*, and the **curvature estimator is the ceiling**.\n\n## The problem\n\nA spherical droplet of radius $R$ sits at rest. Surface tension pulls its\ninterface inward; the pressure inside rises by exactly the Young–Laplace jump\n\n$$\n\\Delta p = \\sigma\\,\\kappa, \\qquad \\kappa = \\frac{2}{R},\n$$ {#eq-yl}\n\nand the two effects cancel *pointwise*. The continuous problem therefore has the\nexact solution $\\mathbf{u}\\equiv 0$, $p = \\sigma\\kappa C + \\text{const}$, where\n$C\\in[0,1]$ is the liquid volume fraction. Nothing should ever move.\n\nThe discrete problem does not automatically inherit that. The continuum-surface-force\n(CSF) model [@brackbill1992] replaces the singular interfacial traction by a\nvolumetric body force\n\n$$\n\\mathbf{f}_\\sigma = \\sigma \\kappa \\nabla C ,\n$$ {#eq-csf}\n\nand the momentum equation is then integrated with a projection: predict\n$\\mathbf{u}^*$, solve a Poisson equation for the pressure, subtract its discrete\ngradient. Equilibrium survives **iff the discrete force in @eq-csf lies in the\nrange of the discrete gradient operator that the projection subtracts.** If it\ndoes, the projection annihilates the force completely and the velocity stays at\nzero to round-off. If it does not, the leftover is a solenoidal residue that no\namount of curvature accuracy removes — and it drives a steady vortex ring of\nmagnitude $\\sim\\sigma\\kappa/\\mu$ around the interface.\n\nThe balanced-force recipe is to form the force with *the projection's own face\ndifference*. At the staggered velocity unknown $u_c(i)$ peclet evaluates\n\n$$\nF_c(i) = \\sigma\\, \\kappa_f(i)\\, \\frac{C(i) - C(i - s_c)}{h},\n$$ {#eq-balanced}\n\nadded to the momentum right-hand side at exactly the point, in exactly the units\nand with exactly the cut-cell rescale of the incremental scheme's\n$-(P(i)-P(i-s_c))$. The face curvature $\\kappa_f$ is the mean of the two cells'\ncurvatures where both carry an estimate, the single available one where only one\ndoes. With a **constant** $\\kappa$, @eq-balanced is *literally* the discrete\ngradient of $\\sigma\\kappa C$ — hence in the range, hence annihilated, hence exact.\n\nThe health metric is the spurious capillary number\n\n$$\n\\mathrm{Ca} = \\frac{\\mu\\,\\max|\\mathbf{u}|}{\\sigma},\n$$ {#eq-ca}\n\nthe ratio of viscous to capillary stress carried by a flow that should not exist.\n\n::: {#bootstrap .cell execution_count=1}\n``` {.python .cell-code code-summary=\"Environment bootstrap (installs peclet from PyPI on Colab/Binder)\"}\n# Makes this notebook run out-of-the-box on Colab/Binder. A real user just needs the\n# published package; this installs it on first run. Authors can instead point at a\n# local source build of the suite with the PECLET_LOCAL_BUILD env var.\nimport importlib.util, os, subprocess, sys\n_local = os.environ.get(\"PECLET_LOCAL_BUILD\")\nif _local:\n    sys.path.insert(0, _local)                                  # local source build\nelif importlib.util.find_spec(\"peclet\") is None:\n    subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"-q\", \"peclet\"], check=True)\n```\n:::\n\n\n::: {#beebaa32 .cell execution_count=2}\n``` {.python .cell-code}\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom peclet import flow\n\nplt.rcParams.update({\"figure.dpi\": 130, \"font.size\": 10, \"axes.grid\": True,\n                     \"grid.alpha\": 0.3, \"axes.axisbelow\": True,\n                     \"figure.facecolor\": \"white\", \"savefig.bbox\": \"tight\"})\nBLUE, RED, GREY, GREEN = \"#1f77b4\", \"#d62728\", \"0.80\", \"#2ca02c\"\n```\n:::\n\n\n## The initial condition: exact volume fractions\n\nVoF wants the *volume fraction* of liquid in every cell, not a level set sampled\nat cell centres — a sampled indicator carries an $O(h)$ error on the interface\nand would pollute the curvature before the solver ever runs. For a sphere the\nfraction is available in closed form along one axis (the chord length of the\nsphere inside the cell's $z$-extent) and only needs subsampling in the other two.\n\nThe droplet centre is deliberately placed at a **non-symmetric** offset\n(`+0.13, +0.27, +0.11` cells). A droplet centred on a cell or a face inherits\ngrid symmetries that cancel the spurious currents for free; the number you would\nmeasure would be a property of the placement, not of the scheme.\n\n::: {#ac5bceba .cell execution_count=3}\n``` {.python .cell-code}\ndef sphere_fractions(shape, R, c, sub=24):\n    \"\"\"Liquid volume fraction of a sphere: exact in z, sub x sub subsampled in (x,y).\"\"\"\n    nx, ny, nz = shape\n    ax = (np.arange(nx)[:, None] + (np.arange(sub)[None, :] + 0.5) / sub).ravel()\n    ay = (np.arange(ny)[:, None] + (np.arange(sub)[None, :] + 0.5) / sub).ravel()\n    X, Y = ax[:, None], ay[None, :]\n    half = np.sqrt(np.maximum(R * R - (X - c[0]) ** 2 - (Y - c[1]) ** 2, 0.0))\n    z0, z1 = c[2] - half, c[2] + half\n    C = np.zeros((nx, ny, nz))\n    for k in range(nz):\n        seg = np.maximum(np.minimum(z1, k + 1) - np.maximum(z0, k), 0.0)\n        C[:, :, k] = seg.reshape(nx, sub, ny, sub).mean(axis=(1, 3))\n    return np.asfortranarray(C)\n\nOFFSET = (0.13, 0.27, 0.11)          # deliberately off-symmetry\nC0 = sphere_fractions((32, 32, 32), 8.0, (16 + .13, 16 + .27, 16 + .11))\nprint(\"liquid fraction along x through the droplet centre (D/dx = 16, R = 8 cells):\")\nprint(np.round(C0[6:27, 16, 16], 4))\nprint(f\"total liquid volume {C0.sum():.4f} cells^3 vs exact 4/3 pi R^3 = \"\n      f\"{4/3*np.pi*8.0**3:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nliquid fraction along x through the droplet centre (D/dx = 16, R = 8 cells):\n[0.     0.     0.8488 1.     1.     1.     1.     1.     1.     1.\n 1.     1.     1.     1.     1.     1.     1.     1.     0.1075 0.\n 0.    ]\ntotal liquid volume 2144.6468 cells^3 vs exact 4/3 pi R^3 = 2144.6606\n```\n:::\n:::\n\n\n## Driving the solver\n\nThe whole two-phase setup is five calls: `enable_vof()` registers the colour\nfield `\"C\"`, `set_vof()` loads the fractions, `set_property_model(\"rho\", …)`\nmakes the density a closure of `C` (which is what switches the solver onto its\nvariable-density path), and `set_surface_tension(sigma)` turns on the\nbalanced-force CSF — which also enables the curvature cascade, run once per step\nat the head of `step()` from the same colour field the density closure sees.\n\nSurface tension is **explicit**, so the time step is capped by the Brackbill\ncapillary limit $\\Delta t < \\sqrt{(\\rho_1+\\rho_2)h^3/(4\\pi\\sigma)}$\n[@brackbill1992] — `capillary_dt()` reports it, and `step()` *enforces* it.\nWe run at half of it.\n\nTwo instruments earn their keep here. `set_vof_kappa_constant(k)` writes an\n**exact** curvature everywhere and freezes it, which isolates the balanced-force\nidentity from the estimator. `set_csf_mode(1)` is the operator **ablation**: the\nsame physics with the force built as a cell-centred $\\sigma\\kappa\\nabla C$ and\nface-interpolated with an arithmetic mean, exactly the way the per-cell body-force\nmachinery carries $\\rho\\mathbf{g}$ — consistent, convergent, and not a discrete\ngradient of anything.\n\n::: {#driver .cell execution_count=4}\n``` {.python .cell-code}\nMU, SIGMA = 0.1, 1.0\n\ndef maxvel(s):\n    return max(np.abs(s.get_u()).max(), np.abs(s.get_v()).max(), np.abs(s.get_w()).max())\n\ndef droplet(n, R, steps=60, csf_mode=0, exact_kappa=False, interface_eps=None):\n    \"\"\"A stationary droplet of radius R cells in an n^3 periodic box. Returns a record.\"\"\"\n    s = flow.Solver(n, n, n)\n    s.set_rho(1.0)\n    s.set_mu(MU)\n    s.set_pressure_geometry(np.full((n, n, n), 10.0, order=\"F\"))   # all-fluid cut-cell operator\n    s.set_pressure_chebyshev(True, 500, 1e-14)\n    s.enable_vof()\n    s.set_vof(sphere_fractions((n, n, n), R,\n                               (n / 2 + OFFSET[0], n / 2 + OFFSET[1], n / 2 + OFFSET[2])))\n    s.set_property_model(\"rho\", \"linear\", \"C\", [1.0, 0.0])         # uniform rho: isolate the force\n    s.set_surface_tension(SIGMA)\n    s.set_csf_mode(csf_mode)\n    if exact_kappa:\n        s.set_vof_kappa_constant(2.0 / R)                          # the analytic sphere curvature\n        s.set_vof_kappa_frozen(True)\n    if interface_eps is not None:\n        s.set_vof_interface_eps(interface_eps)\n    s.set_dt(0.5 * s.capillary_dt())\n\n    hist, iters, div = [], 0, 0.0\n    for _ in range(steps):\n        s.step()\n        hist.append(maxvel(s))\n        iters = max(iters, s.last_pressure_iterations())           # rule 3b: a capped solve\n        div = max(div, s.max_open_divergence())                    # invalidates the run\n    return dict(n=n, R=R, umax=hist[-1], hist=np.array(hist), iters=iters, div=div,\n                kappa=s.vof_curvature(), branch=s.vof_curvature_branch(),\n                csf=s.csf_diagnostics(), cap=500)\n```\n:::\n\n\n::: {.callout-important}\n## A run whose pressure solve hit its iteration cap is not a result\nEvery run on this page records `last_pressure_iterations()` against the cap it was\ngiven and `max_open_divergence()`, and reports both. A capped solve means the\nprojection did not converge, so the velocity field is *not* discretely\ndivergence-free and \"the spurious current\" measured on it is an artefact of the\nlinear solver, not of the surface tension. We discard such runs rather than\nquoting them. (None of the runs below capped; the numbers are printed so you can\ncheck.)\n:::\n\n## 1. With an exact curvature, the currents are at machine zero\n\nGive the solver the analytic $\\kappa = 2/R$ and run the two force\ndiscretizations against each other. Everything else — grid, colour field, time\nstep, pressure driver, viscosity — is identical.\n\n::: {#switch .cell execution_count=5}\n``` {.python .cell-code}\nexact = {m: droplet(32, 8.0, steps=30, csf_mode=m, exact_kappa=True) for m in (0, 1)}\nfor m, r in exact.items():\n    name = \"balanced force (production)\" if m == 0 else \"cell-centred + interpolated\"\n    print(f\"csf_mode={m}  {name:<30s}  max|u| = {r['umax']:.3e}   \"\n          f\"Ca = {MU*r['umax']/SIGMA:.3e}   pressure {r['iters']}/{r['cap']}   \"\n          f\"max|div| {r['div']:.1e}\")\nRATIO = exact[1][\"umax\"] / exact[0][\"umax\"]\nprint(f\"\\nthe operator pairing is worth a factor {RATIO:.2e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncsf_mode=0  balanced force (production)     max|u| = 1.878e-17   Ca = 1.878e-18   pressure 13/500   max|div| 2.7e-16\ncsf_mode=1  cell-centred + interpolated     max|u| = 5.760e-02   Ca = 5.760e-03   pressure 13/500   max|div| 2.2e-16\n\nthe operator pairing is worth a factor 3.07e+15\n```\n:::\n:::\n\n\n::: {#cell-fig-switch .cell execution_count=6}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(5.0, 3.4))\nvals = [exact[0][\"umax\"], exact[1][\"umax\"]]\nbars = ax.bar([\"balanced force\\n(shipped)\", \"cell-centred σκ∇C\\nface-interpolated\"],\n              vals, color=[BLUE, RED], width=0.55)\nax.set_yscale(\"log\")\nax.set_ylim(1e-18, 1e0)\nax.set_ylabel(r\"spurious $\\max|\\mathbf{u}|$  (32³, exact $\\kappa$, 30 steps)\")\nax.axhline(2.2e-16, color=\"0.3\", ls=\"--\", lw=1)\nax.text(0.02, 3e-16, \"double-precision round-off\", transform=ax.get_yaxis_transform(),\n        fontsize=8, color=\"0.3\")\nfor b, v in zip(bars, vals):\n    ax.text(b.get_x() + b.get_width() / 2, v * 2.2, f\"{v:.2e}\", ha=\"center\", fontsize=9)\nax.grid(axis=\"x\", visible=False)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![One line of the discretization. Both bars are the same droplet, the same exact curvature, the same 30 steps: only the operator that turns σκ∇C into a face force differs. The balanced-force pairing (@eq-balanced) is a discrete gradient, so the projection removes it exactly; the arithmetic-mean interpolation of a cell-centred force is not, and what survives is the classical parasitic current. Note the log scale spans 15 decades.](index_files/figure-html/fig-switch-output-1.png){#fig-switch}\n:::\n:::\n\n\nThe balanced-force run sits at **1\\.88e\\-17** — below\ndouble-precision round-off on a field whose pressure is $O(0.25)$, i.e. the\nvelocity never left zero. The ablation sits at\n**5\\.76e\\-02**, a factor\n**3\\.1e\\+15** larger. Both runs converged their pressure solve\nin a handful of iterations and carry a divergence at round-off, so neither is a\nsolver artefact.\n\nThis is the whole content of \"balanced force\", and it is worth stating plainly:\n*the accuracy of the curvature has nothing to do with it.* @eq-balanced with a\nwrong-but-constant $\\kappa$ would still give machine zero. The failure mode of\nthe ablation is structural, not quantitative.\n\n## 2. With the computed curvature, Ca converges at second order\n\nNow let the solver estimate its own curvature. peclet's cascade [@popinet2009] is\na height function on 7-cell column sums of $C$, falling back to a PLIC-volumetric\nparaboloid fit where the columns do not close — never a derivative of the\nreconstructed normal, which does not converge. Whatever error that estimator\nmakes now enters @eq-balanced as a $\\kappa_f$ that varies from face to face, so\nthe force is no longer a discrete gradient, and the residue *is* the curvature\nerror. In cell units $\\mathrm{Ca}\\approx\\delta\\kappa\\cdot h$.\n\nWe sweep the droplet diameter over $D/\\Delta = 8, 16, 24, 32$ (boxes $16^3$ to\n$64^3$, always $D = n/2$ so the periodic images stay equally far away) and run 60\nsteps at each.\n\n::: {#sweep .cell execution_count=7}\n``` {.python .cell-code}\nrungs = [(16, 4.0), (32, 8.0), (48, 12.0), (64, 16.0)]\nsweep = [droplet(n, R) for n, R in rungs]\nD = np.array([2 * R for _, R in rungs])\nCa = np.array([MU * r[\"umax\"] / SIGMA for r in sweep])\norder = -np.polyfit(np.log(D), np.log(Ca), 1)[0]\n\nprint(f\"{'D/dx':>6} {'Ca':>11} {'ratio':>7} {'dkappa rms':>12} {'dkappa max':>11} \"\n      f\"{'orphans':>9} {'pressure':>10} {'max|div|':>10}\")\nfor i, ((n, R), r, ca) in enumerate(zip(rungs, sweep, Ca)):\n    live = (r[\"branch\"] > 0.5) & (r[\"branch\"] < 5.5)\n    dk = np.abs(r[\"kappa\"][live] - 2.0 / R)\n    ratio = f\"{Ca[i-1]/ca:.2f}\" if i else \"\"\n    print(f\"{2*R:6.0f} {ca:11.3e} {ratio:>7} \"\n          f\"{dk.std():12.2e} {dk.max():11.2e} {str(r['csf']['orphan_faces']):>9} \"\n          f\"{r['iters']:>7}/{r['cap']} {r['div']:10.1e}\")\nprint(f\"\\nfitted order of Ca in D/dx: {order:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  D/dx          Ca   ratio   dkappa rms  dkappa max   orphans   pressure   max|div|\n     8   2.543e-04             4.57e-03    3.57e-02 (0, 0, 0)      12/500    1.8e-15\n    16   5.898e-05    4.31     8.65e-04    5.54e-03 (0, 0, 0)      13/500    2.5e-16\n    24   2.649e-05    2.23     2.68e-04    1.70e-03 (1, 1, 1)      13/500    2.0e-16\n    32   1.388e-05    1.91     1.22e-04    8.06e-04 (0, 0, 0)      13/500    1.6e-16\n\nfitted order of Ca in D/dx: 2.09\n```\n:::\n:::\n\n\n::: {#cell-fig-order .cell execution_count=8}\n``` {.python .cell-code}\nfrom matplotlib.ticker import NullFormatter\nCa_exact = MU * exact[0][\"umax\"] / SIGMA\nfig, (ax, axz) = plt.subplots(2, 1, figsize=(5.0, 4.4), sharex=True,\n                              gridspec_kw=dict(height_ratios=[4, 1], hspace=0.12))\nax.loglog(D, Ca, \"o-\", color=BLUE, ms=7, lw=1.6, label=\"computed curvature\")\nfit = Ca[0] * (D / D[0]) ** (-order)\nax.loglog(D, fit, \"--\", color=\"0.35\", lw=1.2, label=f\"fitted order {order:.2f}\")\nax.set_ylim(0.6 * Ca.min(), 2.0 * Ca.max())\nax.set_ylabel(r\"$\\mathrm{Ca} = \\mu\\,\\max|u|/\\sigma$\")\nax.set_title(\"Parasitic currents vs droplet resolution\")\nax.legend(fontsize=8, loc=\"upper right\")\n\naxz.set_xscale(\"log\"); axz.set_yscale(\"log\")\naxz.plot([D[0] * 0.85, D[-1] * 1.18], [Ca_exact, Ca_exact], color=GREEN, lw=2.0)\naxz.set_ylim(0.15 * Ca_exact, 7 * Ca_exact)\naxz.set_yticks([Ca_exact]); axz.set_yticklabels([f\"{Ca_exact:.0e}\"])\naxz.set_xticks(D); axz.set_xticklabels([f\"{d:.0f}\" for d in D])\naxz.xaxis.set_minor_formatter(NullFormatter())\naxz.set_xlabel(r\"droplet resolution  $D/\\Delta$  [cells per diameter]\")\naxz.text(0.98, 0.62, \"exact κ (machine zero)\", transform=axz.transAxes,\n         ha=\"right\", va=\"bottom\", fontsize=8, color=GREEN)\n# axis break marks\nfor a, y in ((ax, 0.0), (axz, 1.0)):\n    a.plot([0, 1], [y, y], transform=a.transAxes, color=\"w\", lw=3, clip_on=False, zorder=5)\n    a.plot([-0.012, 0.012], [y - 0.02, y + 0.02], transform=a.transAxes,\n           color=\"0.3\", lw=1, clip_on=False, zorder=6)\n    a.plot([0.988, 1.012], [y - 0.02, y + 0.02], transform=a.transAxes,\n           color=\"0.3\", lw=1, clip_on=False, zorder=6)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Spurious capillary number against droplet resolution, with the computed curvature. The dashed line is the fitted power law. The strip below the axis break is what the same runs give with an *exact* curvature — machine zero, thirteen decades lower, and flat in resolution. The force discretization contributes nothing to these points — every one of them is curvature error.](index_files/figure-html/fig-order-output-1.png){#fig-order}\n:::\n:::\n\n\nThe headline: **Ca falls from\n2\\.54e\\-04 at 8 cells per diameter to\n1\\.39e\\-05 at 32, a fitted order of\n2\\.09** — second order, which is the convergence rate of the\nheight-function curvature and therefore exactly what @eq-balanced predicts once\n$\\kappa$ stops being exact.\n\n::: {.callout-note}\n## What this means for the pore scale\n$\\mathrm{Ca}\\approx\\delta\\kappa\\,h$ in cell units, so a spurious-current budget is\nreally a **curvature** requirement. A $10^{-7}$ budget is not reachable by\nrefining a static droplet forever either: with advection-realistic volume\nfractions — the ragged $C$ a real transported interface carries, rather than the\nanalytically exact fractions used here — the curvature error stops converging.\nThe force is exact; the estimator is the ceiling.\n:::\n\n## 3. The curvature branch census\n\n`compute_vof_curvature()` fills two fields: `kappa` and `kappa_branch`, and the\nsecond is not optional reading. $\\kappa$ is 0 both where there is no interface\n(branch 0, correct) and where no estimate could be made (branch 6, which must\nnever happen). Branches 1–2 are the height function, 4–5 the PLIC-volumetric\nparaboloid fallback.\n\n::: {#census .cell execution_count=9}\n``` {.python .cell-code}\nNAMES = {0: \"no interface\", 1: \"height function\", 2: \"HF, other direction\",\n         3: \"mixed height-position (off)\", 4: \"PLIC paraboloid\", 5: \"PLIC, rank-deficient\",\n         6: \"NO ESTIMATE (defect)\"}\nSHORT = {1: \"HF\", 2: \"HF (other dir)\", 4: \"PLIC paraboloid\", 5: \"PLIC rank-def\",\n         6: \"no estimate!\"}\nprint(f\"{'D/dx':>5} \" + \" \".join(f\"{SHORT[b]:>16}\" for b in (1, 2, 4, 5, 6))\n      + f\"{'fallback %':>12}\")\nfor (n, R), r in zip(rungs, sweep):\n    b = r[\"branch\"]\n    cnt = {k: int((np.abs(b - k) < 0.5).sum()) for k in (1, 2, 4, 5, 6)}\n    live = sum(cnt.values())\n    print(f\"{2*R:5.0f} \" + \" \".join(f\"{cnt[k]:>16d}\" for k in (1, 2, 4, 5, 6))\n          + f\"{100*(cnt[4]+cnt[5])/live:11.1f}%\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n D/dx               HF   HF (other dir)  PLIC paraboloid    PLIC rank-def     no estimate!  fallback %\n    8               91                0              223                0                0       71.0%\n   16              789                0              428                0                0       35.2%\n   24             1999                0              708                0                0       26.2%\n   32             3749                0             1079                0                0       22.3%\n```\n:::\n:::\n\n\n::: {#cell-fig-census .cell execution_count=10}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(5.2, 3.4))\nkeys = [1, 2, 4, 5]\ncols = {1: BLUE, 2: \"#7fb2dd\", 4: RED, 5: \"#f0928f\"}\nbottom = np.zeros(len(rungs))\nfor k in keys:\n    frac = np.array([100 * (np.abs(r[\"branch\"] - k) < 0.5).sum()\n                     / ((r[\"branch\"] > 0.5) & (r[\"branch\"] < 5.5)).sum() for r in sweep])\n    ax.bar([f\"{2*R:.0f}\" for _, R in rungs], frac, bottom=bottom, color=cols[k],\n           label=NAMES[k], width=0.6)\n    bottom += frac\nax.set(xlabel=r\"$D/\\Delta$\", ylabel=\"% of interfacial cells\", ylim=(0, 100),\n       title=\"Curvature cascade: which branch served the cell\")\nax.legend(fontsize=8, loc=\"upper center\", bbox_to_anchor=(0.5, -0.16), ncol=2,\n          frameon=False)\nax.grid(axis=\"x\", visible=False)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Which tier of the curvature cascade served each interfacial cell. The paraboloid fallback is not a failure mode — a 3×3 height patch in 3-D needs 2.5 cells of column reach along the octant diagonal, exactly the capacity of a 7-column, so the fallback always fires somewhere on a sphere and dominates below ~5 cells per diameter. Branch 6 (no estimate) is a defect and is empty at every rung.](index_files/figure-html/fig-census-output-1.png){#fig-census}\n:::\n:::\n\n\n`csf_diagnostics()` also counts **orphan faces** — faces the colour jumps across\nbut where *neither* cell carries a curvature estimate, so the force would have to\nbe dropped. An orphan is a defect, and it is counted rather than hidden; the\nsweep above reports 0–1 per component at every rung.\n\n## 4. The wisp guard: why a threshold on the *predicate* is not optional\n\nWeymouth–Yue advection is exactly conservative, and the price is round-off colour\nresidue: every cell its sweeps touch keeps a $C$ of order $10^{-30}$ (measured\ndown to $-3\\times10^{-35}$). Those cells satisfy the naive interfacial predicate\n$0 < C < 1$, so the cascade dutifully builds a PLIC polygon of area $\\sim0$ for\nthem and fits a paraboloid to it. A face between such a cell and a *real*\ninterfacial cell then has $\\Delta C = O(1)$ and a face curvature\n$(\\kappa_{\\text{real}} + 10^{11})/2$.\n\nThe fix is a threshold on the predicate — a cell carries an interface only while\n$\\varepsilon < C < 1-\\varepsilon$. `set_surface_tension` sets\n$\\varepsilon = 10^{-8}$; `set_vof_interface_eps(0)` restores the unguarded\npredicate, which is the ablation.\n\n::: {#wisp .cell execution_count=11}\n``` {.python .cell-code}\nwisp = {}\nfor eps in (1e-8, 0.0):\n    try:\n        wisp[eps] = droplet(64, 16.0, steps=60, interface_eps=eps)\n    except RuntimeError as e:                      # eps=0 can trip the WY CFL cap outright\n        print(f\"eps = {eps:g}: DIVERGED — {str(e)[:80]}\")\nW = {}\nfor eps, r in wisp.items():\n    live = (r[\"branch\"] > 0.5) & (r[\"branch\"] < 5.5)\n    W[eps] = dict(served=int(live.sum()), kmax=float(np.abs(r[\"kappa\"][live]).max()),\n                  u0=r[\"hist\"][0], u1=r[\"hist\"][-1])\n    print(f\"eps = {eps:<6g}  max|u| step 1 {r['hist'][0]:.3e} -> step 60 {r['hist'][-1]:.3e}\"\n          f\"   cells served {W[eps]['served']:5d}   max|kappa| {W[eps]['kmax']:.3e}\"\n          f\"   (physical 2/R = {2/16.0:.4f})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\neps = 1e-08   max|u| step 1 2.110e-03 -> step 60 1.388e-04   cells served  4828   max|kappa| 1.258e-01   (physical 2/R = 0.1250)\neps = 0       max|u| step 1 2.110e-03 -> step 60 1.853e-03   cells served 10018   max|kappa| 2.868e+11   (physical 2/R = 0.1250)\n```\n:::\n:::\n\n\n::: {#cell-fig-wisp .cell execution_count=12}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(5.0, 3.6))\nlbl = {1e-8: r\"$\\varepsilon = 10^{-8}$ (default, guarded)\", 0.0: r\"$\\varepsilon = 0$ (unguarded)\"}\nfor eps, col in ((1e-8, BLUE), (0.0, RED)):\n    if eps in wisp:\n        ax.semilogy(np.arange(1, len(wisp[eps][\"hist\"]) + 1), wisp[eps][\"hist\"],\n                    color=col, lw=1.7, label=lbl[eps])\nax.set(xlabel=\"step\", ylabel=r\"$\\max|\\mathbf{u}|$\",\n       title=\"Spurious velocity with and without the wisp guard\")\nax.legend(fontsize=9)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The wisp guard, 64³ droplet, 60 steps. With the guard the spurious velocity decays monotonically; without it the cascade serves twice as many 'interfacial' cells — more than the interface has — with curvatures up to 1e11, and the currents stop decaying. Exact conservation is untouched either way: the guard thresholds the *predicate*, it does not clip the colour field.](index_files/figure-html/fig-wisp-output-1.png){#fig-wisp}\n:::\n:::\n\n\nGuarded, `max|u|` decays from 2\\.11e\\-03 to\n1\\.39e\\-04 over 60 steps and the largest curvature in the\nfield is 0\\.1258, against the physical $2/R = 0.125$.\nUnguarded, the same run serves 10018 cells instead of\n4828 — more \"interfacial\" cells than the interface\nhas — reports a maximum curvature of 2\\.87e\\+11, and the\nvelocity **does not decay** (2\\.11e\\-03 at step 1 against\n1\\.85e\\-03 at step 60). This is the trap the literature knows as\n\"with surface tension some clipping is unavoidable\" [@arrufat2021], arriving in\nthe cheapest available form.\n\n## Collocated cross-check\n\npeclet also ships a cell-centred/collocated grid (`flow.SolverColocated`), and\nseveral pages in this gallery run their verification on both meshes. The\ntwo-phase path is **staggered-only today**: the variable-density collocated\nprojection is rung V8 of the VoF campaign and is not yet available —\n`SolverColocated` raises if you enable VoF on it. This section will be filled in\nwith the collocated column of the table above when that rung lands.\n\n## Adapt this yourself\n\n- **Change the density ratio.** `set_property_model(\"rho\", \"linear\", \"C\", [rho_g, rho_l-rho_g])`\n  makes this a real two-phase droplet. The equilibrium is then *approached* rather\n  than hit: the semi-implicit momentum operator $A = \\rho_f/\\Delta t - \\mu\\nabla^2$\n  commutes with the discrete gradient only at constant $\\rho_f$, so a residue of\n  order $\\mu\\,\\Delta t^2$ appears at the first step and then decays.\n- **Change the viscosity.** With an exact curvature the machine-zero result is\n  independent of $\\mu$ over four decades — a good check that your build is healthy.\n- **Freeze the curvature instead of making it exact.** `set_vof_kappa_frozen(True)`\n  keeps whatever is in the `kappa` field, which separates \"the estimator is wrong\"\n  from \"the estimator is fed back through the transport\".\n- **Push the resolution.** $D/\\Delta = 48$ needs a $96^3$ box; on a CUDA build that\n  is still seconds per run, and it extends the log-log fit by another point.\n- **Go multi-rank.** The identical script runs under `mpirun -np N python …`; the\n  curvature cascade reaches exactly $\\pm3$ cells, which is the colour field's own\n  ghost depth, so no reduction appears anywhere in it and the result is *bitwise*\n  decomposition-independent at np = 1.\n\n## Reproduce this\n\nThe compiled solver runs this, so its outputs are **frozen** into the site. To\nregenerate:\n\n```bash\npip install peclet            # the solver, from PyPI\nquarto render examples/parasitic-currents/index.qmd --execute\n# ...or against a local source build of the suite (GPU):\nPECLET_LOCAL_BUILD=/path/to/suite/flow/build_cuda OMP_NUM_THREADS=8 OMP_PROC_BIND=false \\\n  quarto render examples/parasitic-currents/index.qmd --execute\n```\n\nThe same battery is available inside the solver repo as\n`tests/study/vof_surface_tension.py static`, and its algebraic siblings (the\nexactness gate, Young–Laplace to $2\\times10^{-16}$, the capillary time step,\ninertness when surface tension is off) run in the `vof_surface_tension` ctest.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}